// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.OrdinalWeekOfMonth.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.DayOfWeekOccurrenceInMonth" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DayOfWeekOccurrenceInMonthTestData))]
    public void DayOfWeekOccurrenceInMonth_WhenCalled_ShouldReturnExpectedOrdinal(DateTime input, WeekOrdinal expected)
    {
        var actual = input.WeekOrdinalOfMonth();

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.DayOfWeekOccurrenceInMonth" />, when LeapDay, returns the expected value.
    /// </summary>
    [TestMethod]
    public void DayOfWeekOccurrenceInMonth_WhenLeapDay_ShouldReturnCorrectOrdinal()
    {
        DateTime leapDay = new DateTime(2024, 2, 29); // Thursday
        WeekOrdinal actual = leapDay.WeekOrdinalOfMonth();

        Assert.AreEqual(WeekOrdinal.Fifth, actual); // 1st = 1st, 8th = 2nd, ..., 29th = 5th Thursday
    }

}
