// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.DayName.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

﻿// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Bodu.Extensions
{
    public partial class DateOnlyExtensionsTests
    {

        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.DayNameTestData), typeof(DateTimeExtensionsTests),DynamicDataSourceType.Method)]
        public void DayName_WithCulture_ShouldReturnLocalizedName(DateTime inputDateTime, CultureInfo culture, string expected)
        {
            var input=DateOnly.FromDateTime(inputDateTime);

            string actual = input.DayName(culture);

            Assert.AreEqual(expected, actual);
        }

        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.DayNameFrenchTestData), typeof(DateTimeExtensionsTests),DynamicDataSourceType.Method)]
        public void DayName_WhenCultureIsNull_ShouldFallbackToCurrentCulture(DateTime inputDateTime, string expected)
        {
            var original = CultureInfo.CurrentCulture;
            try
            {
                CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
                var input = DateOnly.FromDateTime(inputDateTime);

                string actual = input.DayName(null!);

                Assert.AreEqual(expected, actual);
            }
            finally
            {
                CultureInfo.CurrentCulture = original;
            }
        }
    }
}
