// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.NthDateOfWeekInMonth.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that the instance overload returns the expected nth-occurrence date for each <c>(input, dayOfWeek, ordinal)</c> tuple.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.NthDateOfWeekInMonthTestData), typeof(DateTimeExtensionsTests))]
    public void NthDateOfWeekInMonth_WhenCalled_ShouldReturnExpected(DateTime inputDateTime, DayOfWeek dayOfWeek, WeekOrdinal ordinal, DateTime expectedDateTime)
    {
        var input = DateOnly.FromDateTime(inputDateTime);
        var expected = DateOnly.FromDateTime(expectedDateTime);

        var actual = input.NthDateOfWeekInMonth(dayOfWeek, ordinal);

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that an undefined <see cref="DayOfWeek" /> value throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void NthDateOfWeekInMonth_WhenDayOfWeekIsInvalidEnum_ShouldThrowExactly()
    {
        var input = new DateOnly(2024, 1, 1);
        DayOfWeek invalidDay = (DayOfWeek)999;

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            input.NthDateOfWeekInMonth(invalidDay, WeekOrdinal.First);
        });
    }

    /// <summary>
    /// Verifies that requesting <see cref="WeekOrdinal.Fifth" /> in a month that has only four occurrences throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void NthDateOfWeekInMonth_WhenFifthDoesNotExist_ShouldThrowExactly()
    {
        var input = new DateOnly(2023, 2, 1); // February 2023 has only 4 Wednesdays

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            input.NthDateOfWeekInMonth(DayOfWeek.Wednesday, WeekOrdinal.Fifth);
        });
    }

    /// <summary>
    /// Verifies that an undefined <see cref="WeekOrdinal" /> value throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void NthDateOfWeekInMonth_WhenOrdinalIsInvalidEnum_ShouldThrowExactly()
    {
        var input = new DateOnly(2024, 1, 1);
        WeekOrdinal invalidOrdinal = (WeekOrdinal)999;

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            input.NthDateOfWeekInMonth(DayOfWeek.Monday, invalidOrdinal);
        });
    }

    /// <summary>
    /// Verifies that the static <see cref="DateOnlyExtensions.GetNthDateOfWeekInMonth(int, int, DayOfWeek, WeekOrdinal)" /> overload returns the same nth-occurrence date as the instance overload.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.NthDateOfWeekInMonthTestData), typeof(DateTimeExtensionsTests))]
    public void NthDateOfWeekInMonth_WhenUsingYearMonth_ShouldReturnExpected(DateTime inputDateTime, DayOfWeek dayOfWeek, WeekOrdinal ordinal, DateTime expectedDateTime)
    {
        int year = inputDateTime.Year, month = inputDateTime.Month;
        var expected = DateOnly.FromDateTime(expectedDateTime);

        var actual = DateOnlyExtensions.GetNthDateOfWeekInMonth(year, month, dayOfWeek, ordinal);

        Assert.AreEqual(expected, actual);
    }

}
