// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.NextDateOfWeek.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{
    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.NextDateOfWeek(DateTime, DayOfWeek)" /> returns the next occurrence of the requested <see cref="DayOfWeek" /> for each <c>(input, target)</c> pair.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(NextDateOfWeekTestData))]
    public void NextDateOfWeek_WhenCalled_ShouldReturnExpectedDate(DateTime input, DayOfWeek targetDay, DateTime expected)
    {
            var actual = input.NextDateOfWeek(targetDay);

            Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that targeting the input's own <see cref="DateTime.DayOfWeek" /> advances by exactly one week and preserves the input's <see cref="DateTime.TimeOfDay" />.
    /// </summary>
    [TestMethod]
    public void NextDateOfWeek_WhenTimeIsSet_ShouldPreserveTime()
    {
        var input = DateTime.Now;
        var actual = input.NextDateOfWeek(input.DayOfWeek); // Move one week

        Assert.AreEqual(input.TimeOfDay, actual.TimeOfDay);
    }

    /// <summary>
    /// Verifies that an undefined <see cref="DayOfWeek" /> value throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void NextDateOfWeek_WhenInvalidEnum_ShouldThrowExactly()
    {
        DateTime input = new DateTime(2024, 4, 18);

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            _ = input.NextDateOfWeek((DayOfWeek)999);
        });
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.NextDateOfWeek(DateTime, DayOfWeek)" /> preserves the input's <see cref="DateTime.Kind" /> across all <see cref="DateTimeKind" /> values.
    /// </summary>
    [TestMethod]
    [DataRow(DateTimeKind.Unspecified)]
    [DataRow(DateTimeKind.Utc)]
    [DataRow(DateTimeKind.Local)]
    public void NextDateOfWeek_WhenKindIsSet_ShouldPreserveKind(DateTimeKind kind)
    {
        DateTime input = new DateTime(2024, 4, 18, 10, 0, 0, kind);
        DateTime actual = input.NextDateOfWeek(DayOfWeek.Wednesday);

        Assert.AreEqual(kind, actual.Kind);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.NextDateOfWeek(DateTime, DayOfWeek)" /> preserves a sub-second-precision <see cref="DateTime.TimeOfDay" /> on the resulting date.
    /// </summary>
    [TestMethod]
    public void NextDateOfWeek_WhenTimeIsSet_ShouldPreserveTimed()
    {
        var time = new TimeSpan(0, 12, 32, 55, 34, 903);
        var input = new DateTime(2024, 4, 18).Add(time);

        var actual = input.NextDateOfWeek(DayOfWeek.Monday).TimeOfDay;

        Assert.AreEqual(time, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTime.MinValue" /> returns a date on or after <see cref="DateTime.MinValue" /> (does not underflow).
    /// </summary>
    [TestMethod]
    public void NextDateOfWeek_WhenUsingMinValue_ShouldReturnNextValidDate()
    {
        DateTime actual = DateTime.MinValue.NextDateOfWeek(DayOfWeek.Friday);

        Assert.IsTrue(actual >= DateTime.MinValue);
    }

    /// <summary>
    /// Verifies that an input one week before <see cref="DateTime.MaxValue" /> targeting its own <see cref="DateTime.DayOfWeek" /> stays within the valid range.
    /// </summary>
    [TestMethod]
    public void NextDateOfWeek_WhenUsingMaxValueMinus7_ShouldReturnWithinRange()
    {
        DateTime input = DateTime.MaxValue.AddDays(-7);
        DateTime actual = input.NextDateOfWeek(input.DayOfWeek);

        Assert.IsTrue(actual <= DateTime.MaxValue);
    }
}
