// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;
using System.Data;

namespace Bodu.Extensions
{
	public partial class DateTimeExtensionsTests
	{

		private static IEnumerable<object[]> WeekendTestData
		{
			get
			{
				yield return new object[] { new DateTime(2024,04,20), StandardWeekend.SaturdaySunday, null, true}; // Saturday
				yield return new object[] { new DateTime(2024,04,21), StandardWeekend.SaturdaySunday, null, true}; // Sunday
				yield return new object[] { new DateTime(2024,04,22), StandardWeekend.SaturdaySunday, null, false}; // Monday

				yield return new object[] { new DateTime(2024,04,19), StandardWeekend.FridaySaturday, null, true}; // Friday
				yield return new object[] { new DateTime(2024,04,20), StandardWeekend.FridaySaturday, null, true}; // Saturday
				yield return new object[] { new DateTime(2024,04,21), StandardWeekend.FridaySaturday, null, false}; // Sunday

				yield return new object[] { new DateTime(2024,04,18), StandardWeekend.ThursdayFriday, null, true}; // Thursday
				yield return new object[] { new DateTime(2024,04,19), StandardWeekend.ThursdayFriday, null, true}; // Friday
				yield return new object[] { new DateTime(2024,04,20), StandardWeekend.ThursdayFriday, null, false}; // Saturday

				yield return new object[] { new DateTime(2024,04,21), StandardWeekend.SundayOnly, null, true}; // Sunday
				yield return new object[] { new DateTime(2024,04,22), StandardWeekend.SundayOnly, null, false}; // Monday

				yield return new object[] { new DateTime(2024,04,19), StandardWeekend.FridayOnly, null, true}; // Friday
				yield return new object[] { new DateTime(2024,04,20), StandardWeekend.FridayOnly, null, false}; // Saturday

				yield return new object[] { new DateTime(2024,04,19), StandardWeekend.Custom, typeof(FridayOnlyWeekendProvider), true};
				yield return new object[] { new DateTime(2024,04,20), StandardWeekend.Custom, typeof(FridayOnlyWeekendProvider), false};
			}
		}

		[DataTestMethod]
		[DynamicData(nameof(WeekendTestData), typeof(DateTimeExtensionsTests))]
		public void IsWeekend_WhenUsingStandardWeekend_ShouldReturnExpected(DateTime input, StandardWeekend weekend, Type? providerType, bool expected)
		{
			IWeekendProvider? provider = providerType is null ? null : (IWeekendProvider)Activator.CreateInstance(providerType)!;

			bool result = input.IsWeekend(weekend, provider);
			Assert.AreEqual(expected, result, $"Failed for {input} with weekend {weekend}");
		}

		[TestMethod]
		public void IsWeekend_WhenCustomRuleMissingProvider_ShouldThrow()
		{
			DateTime date = new DateTime(2024, 4, 19);
			Assert.ThrowsException<ArgumentOutOfRangeException>(() =>
			{
				_ = date.IsWeekend(StandardWeekend.Custom, null!);
			});
		}

		[TestMethod]
		public void IsWeekend_WhenInvalidEnum_ShouldThrow()
		{
			Assert.ThrowsException<ArgumentOutOfRangeException>(() =>
			{
				_ = DateTimeExtensions.IsWeekend((DayOfWeek)99, StandardWeekend.SaturdaySunday);
			});
		}


	}
}