// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.LastDayOfYear.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
    public partial class DateTimeExtensionsTests
    {

        [TestMethod]
        [DynamicData(nameof(LastDayOfYearTestData), DynamicDataSourceType.Method)]
        public void LastDayOfYear_WhenCalled_ShouldReturnDecember31(DateTime input, DateTime expected)
        {
            DateTime actual = input.LastDayOfYear();

            Assert.AreEqual(expected, actual);
        }

        [TestMethod]
        [DataRow(DateTimeKind.Unspecified)]
        [DataRow(DateTimeKind.Utc)]
        [DataRow(DateTimeKind.Local)]
        public void LastDayOfYear_WhenKindIsSet_ShouldPreserveKind(DateTimeKind kind)
        {
            DateTime input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
            DateTime actual = input.LastDayOfYear();

            Assert.AreEqual(kind, actual.Kind);
        }

        [TestMethod]
        public void LastDayOfYear_WhenMinValue_ShouldReturnEndOfYear1()
        {
            DateTime input = DateTime.MinValue;
            DateTime actual = input.LastDayOfYear();

            Assert.AreEqual(new DateTime(DateTime.MinValue.Year, 12, 31), actual);
        }

        [TestMethod]
        public void LastDayOfYear_WhenMaxValue_ShouldReturnItself()
        {
            DateTime input = DateTime.MaxValue;
            DateTime actual = input.LastDayOfYear();

            Assert.AreEqual(DateTime.MaxValue.Date, actual);
        }
    }
}
