// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.FirstDayOfWeekInQuarter.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions
{
    public partial class DateTimeExtensionsTests
    {

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter(DateTime, DayOfWeek, CalendarQuarterDefinition)" /> returns the expected first occurrence of the given <see cref="DayOfWeek" /> within each <see cref="CalendarQuarterDefinition" /> boundary.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(FirstDayOfWeekInQuarterDateTimeTestData), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenUsingQuarterDefinition_ShouldReturnExpectedDate(DateTime input, CalendarQuarterDefinition definition, DayOfWeek dayOfWeek, DateTime expected)
        {
            var actual = input.FirstDayOfWeekInQuarter(dayOfWeek, definition);
            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that the parameterless-definition <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter(DateTime, DayOfWeek)" /> overload returns the expected first-weekday occurrence using the January-to-December quarter boundaries.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(FirstDayOfWeekInQuarterDateTimeJanuaryDecemberTestData), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenUsingDateOnly_ShouldReturnExpectedStartOfCalendarQuarter(DateTime input, DayOfWeek dayOfWeek, DateTime expected)
        {
            var actual = input.FirstDayOfWeekInQuarter(dayOfWeek);
            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.GetFirstDayOfWeekInQuarter(int, int, DayOfWeek, CalendarQuarterDefinition)" /> computes the expected first-weekday occurrence for each <c>(year, quarter, dayOfWeek, definition)</c> tuple.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(FirstDayOfWeekInQuarterTestData), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenUsingQuarterAndDefinition_ShouldReturnExpectedDate(int year, int quarter, CalendarQuarterDefinition definition, DayOfWeek dayOfWeek, DateTime expected)
        {
            var actual = DateTimeExtensions.GetFirstDayOfWeekInQuarter(year, quarter, dayOfWeek, definition);
            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.GetFirstDayOfWeekInQuarter(int, int, DayOfWeek)" /> with the default January-to-December definition returns the expected first-weekday occurrence.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(FirstDayOfWeekInQuarterYearQuarterJanuaryDecemberTestData), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenUsingQuarterAndCalendarDefinition_ShouldReturnExpectedDate(int year, int quarter, DayOfWeek dayOfWeek, DateTime expected)
        {
            var actual = DateTimeExtensions.GetFirstDayOfWeekInQuarter(year, quarter, dayOfWeek);
            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that a custom <c>IQuarterProvider</c> returning out-of-range month values causes <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter{T}" /> to throw <see cref="ArgumentOutOfRangeException" />.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenUsingInvalidProvider_ShouldThrowArgumentOutOfRange()
        {
            var input = new DateTime(2024, 4, 20);
            var provider = new InValidQuarterProvider();

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = input.FirstDayOfWeekInQuarter(DayOfWeek.Monday, provider);
            });
        }

        /// <summary>
        /// Verifies that passing <see cref="CalendarQuarterDefinition.Custom" /> without supplying a provider throws <see cref="InvalidOperationException" />.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenUsingCustomQuarterDefinitionWithoutProvider_ShouldThrowInvalidOperation()
        {
            var input = new DateTime(2024, 4, 20);

            Assert.ThrowsExactly<InvalidOperationException>(() =>
            {
                _ = input.FirstDayOfWeekInQuarter(DayOfWeek.Monday, CalendarQuarterDefinition.Custom);
            });
        }

        /// <summary>
        /// Verifies that FirstDayOfWeekInQuarter returns the correct date using a valid quarter provider.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.ValidQuarterProvider.FirstDayOfWeekInQuarterTestData), typeof(DateTimeExtensionsTests.ValidQuarterProvider), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenUsingValidQuarterProvider_ShouldReturnExpectedDate(DateTime input, DayOfWeek dayOfWeek, DateTime expected)
        {
            var provider = new ValidQuarterProvider();
            var actual = input.FirstDayOfWeekInQuarter(dayOfWeek, provider);
            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that <see cref="DateTime.MinValue" /> with <see cref="DayOfWeek.Monday" /> yields <c>0001-01-01</c> (which is a Monday) under January-to-December boundaries.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenInputIsMinValue_ShouldReturnExpectedDate()
        {
            var actual = DateTime.MinValue.FirstDayOfWeekInQuarter(DayOfWeek.Monday, CalendarQuarterDefinition.JanuaryToDecember);
            Assert.AreEqual(new DateTime(1, 1, 1), actual);
        }

        /// <summary>
        /// Verifies that <see cref="DateTime.MaxValue" /> with <see cref="DayOfWeek.Friday" /> yields the first Friday of Q4 of year 9999 under January-to-December boundaries.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenInputIsMaxValue_ShouldReturnExpectedDate()
        {
            var actual = DateTime.MaxValue.FirstDayOfWeekInQuarter(DayOfWeek.Friday, CalendarQuarterDefinition.JanuaryToDecember);
            Assert.AreEqual(new DateTime(9999, 10, 1), actual); // Q4 of 9999
        }

        /// <summary>
        /// Verifies that an undefined <see cref="CalendarQuarterDefinition" /> value throws <see cref="ArgumentOutOfRangeException" />.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenDefinitionIsInvalid_ShouldThrowExactly()
        {
            var input = new DateTime(2024, 4, 20);
            var definition = (CalendarQuarterDefinition)999;

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = input.FirstDayOfWeekInQuarter(DayOfWeek.Sunday, definition);
            });
        }

        /// <summary>
        /// Verifies that the static <see cref="DateTimeExtensions.GetFirstDayOfWeekInQuarter(int, int, DayOfWeek, CalendarQuarterDefinition)" /> overload throws <see cref="ArgumentOutOfRangeException" /> for an undefined definition even when the quarter index is valid.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenDefinitionIsInvalidAndQuarterIsValid_ShouldThrowExactly()
        {
            var definition = (CalendarQuarterDefinition)999;

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(2025, 1, DayOfWeek.Sunday, definition);
            });
        }

        /// <summary>
        /// Verifies that a quarter index outside <c>1..4</c> throws <see cref="ArgumentOutOfRangeException" /> when an otherwise-valid definition is supplied.
        /// </summary>
        [TestMethod]
        [DataRow(-1)]
        [DataRow(0)]
        [DataRow(5)]
        public void FirstDayOfWeekInQuarter_WhenQuarterIsOutOfRangeAndDefinitionIsValid_ShouldThrowExactly(int quarter)
        {
            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(2025, quarter, DayOfWeek.Sunday, CalendarQuarterDefinition.JanuaryToDecember);
            });
        }

        /// <summary>
        /// Verifies that the default January-to-December overload throws <see cref="ArgumentOutOfRangeException" /> for quarter values outside <c>1..4</c>.
        /// </summary>
        [TestMethod]
        [DataRow(-1)]
        [DataRow(0)]
        [DataRow(5)]
        public void FirstDayOfWeekInQuarter_WhenQuarterIsOutOfRange_ShouldThrowExactly(int quarter)
        {
            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(2025, quarter, DayOfWeek.Sunday);
            });
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter(DateTime, DayOfWeek)" /> preserves the input's <see cref="DateTime.Kind" /> for every <see cref="DateTimeKind" /> value.
        /// </summary>
        [TestMethod]
        [DataRow(DateTimeKind.Unspecified)]
        [DataRow(DateTimeKind.Utc)]
        [DataRow(DateTimeKind.Local)]
        public void FirstDayOfWeekInQuarter_WhenKindIsSet_ShouldPreserveKind(DateTimeKind kind)
        {
            DateTime input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
            DateTime actual = input.FirstDayOfWeekInQuarter(DayOfWeek.Sunday);

            Assert.AreEqual(kind, actual.Kind);
        }

        /// <summary>
        /// Verifies that the provider-based <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter{T}" /> overload preserves the input's <see cref="DateTime.Kind" /> for every <see cref="DateTimeKind" /> value.
        /// </summary>
        [TestMethod]
        [DataRow(DateTimeKind.Unspecified)]
        [DataRow(DateTimeKind.Utc)]
        [DataRow(DateTimeKind.Local)]
        public void FirstDayOfWeekInQuarter_WhenKindIsSet_WithValidQuarterProvider_ShouldPreserveKind(DateTimeKind kind)
        {
            var provider = new ValidQuarterProvider();
            DateTime input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
            DateTime actual = input.FirstDayOfWeekInQuarter(DayOfWeek.Sunday, provider);

            Assert.AreEqual(kind, actual.Kind);
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.FirstDayOfWeekInQuarter(DateTime, DayOfWeek, CalendarQuarterDefinition)" /> preserves the input's <see cref="DateTime.Kind" /> across every <c>(definition, kind)</c> combination.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(CalendarQuarterDefinitionDateTimeKindTestData), DynamicDataSourceType.Method)]
        public void FirstDayOfWeekInQuarter_WhenQuarterAndDefinitionAndKindIsSet_ShouldPreserveKind(CalendarQuarterDefinition definition, DateTimeKind kind)
        {
            DateTime input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
            DateTime actual = input.FirstDayOfWeekInQuarter(DayOfWeek.Sunday, definition);

            Assert.AreEqual(kind, actual.Kind);
        }


        /// <summary>
        /// Verifies that an undefined <see cref="DayOfWeek" /> value throws <see cref="ArgumentOutOfRangeException" /> even when quarter and definition are valid.
        /// </summary>
        [TestMethod]
        public void FirstDayOfWeekInQuarter_WhenDayOfWeekIsInvalidAndQuarterAndDefinitionIsValid_ShouldThrowExactly()
        {
            var dayOfWeek = (DayOfWeek)999;

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(2025, 1, dayOfWeek, CalendarQuarterDefinition.JanuaryToDecember);
            });
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.GetFirstDayOfWeekInQuarter(int, int, DayOfWeek, CalendarQuarterDefinition)" /> throws <see cref="ArgumentOutOfRangeException" /> for year values outside <c>1..9999</c>.
        /// </summary>
        [TestMethod]
        [DataRow(-1)]
        [DataRow(0)]
        [DataRow(10_000)]
        public void GetFirstDayOfWeekInQuarter_WhenYearIsInvalid_WithDefinition_ShouldThrowExactly(int year)
        {
            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(year, 1, DayOfWeek.Monday, CalendarQuarterDefinition.JanuaryToDecember);
            });
        }

        /// <summary>
        /// Verifies that <see cref="DateTimeExtensions.GetFirstDayOfWeekInQuarter(int, int, DayOfWeek)" /> throws <see cref="ArgumentOutOfRangeException" /> for year values outside <c>1..9999</c>.
        /// </summary>
        [TestMethod]
        [DataRow(-1)]
        [DataRow(0)]
        [DataRow(10_000)]
        public void GetFirstDayOfWeekInQuarter_WhenYearIsInvalid_ShouldThrowExactly(int year)
        {
            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.GetFirstDayOfWeekInQuarter(year, 1, DayOfWeek.Monday);
            });
        }

    }
}