// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.Midnight.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.Midnight" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(MidnightTestData))]
    public void Midnight_WhenCalled_ShouldSetTimeToNoon(DateTime input, DateTime expected)
    {
        DateTime actual = input.Midnight();

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.Midnight" />, when KindIsSet, returns the expected value.
    /// </summary>
    [TestMethod]
    [DataRow(DateTimeKind.Unspecified)]
    [DataRow(DateTimeKind.Utc)]
    [DataRow(DateTimeKind.Local)]
    public void Midnight_WhenKindIsSet_ShouldPreserveKind(DateTimeKind kind)
    {
        var input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
        var actual = input.Midnight();

        Assert.AreEqual(kind, actual.Kind);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.Midnight" />, when UsingMaxValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void Midnight_WhenUsingMaxValue_ShouldReturnMidnight()
    {
        DateTime input = DateTime.MaxValue.Date;
        DateTime actual = input.Midnight();

        Assert.AreEqual(new DateTime(9999, 12, 31, 0, 0, 0), actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.Midnight" />, when UsingMinValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void Midnight_WhenUsingMinValue_ShouldReturnMidnight()
    {
        DateTime input = DateTime.MinValue.Date;
        DateTime actual = input.Midnight();

        Assert.AreEqual(new DateTime(1, 1, 1, 0, 0, 0), actual);
    }

}
