// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.NextDayOfWeek.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

﻿// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions
{
    public partial class DateOnlyExtensionsTests
    {
        /// <summary>
        /// Verifies that Next Day Of Week, when Called, returns Expected Date.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests. NextDayOfWeekTestData),typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
        public void NextDayOfWeek_WhenCalled_ShouldReturnExpectedDate(DateTime inputDateTime, DayOfWeek targetDay, DateTime expectedDateTime)
        {
            var input = DateOnly.FromDateTime(inputDateTime);
            var expected = DateOnly.FromDateTime(expectedDateTime);

            var actual = input.NextDayOfWeek(targetDay);

                Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that Next Day Of Week, when Invalid Enum, throws Exactly.
        /// </summary>
        [TestMethod]
        public void NextDayOfWeek_WhenInvalidEnum_ShouldThrowExactly()
        {
            var input = new DateOnly(2024, 4, 18);

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = input.NextDayOfWeek((DayOfWeek)999);
            });
        }

        /// <summary>
        /// Verifies that Next Day Of Week, when Using Min Value, returns Next Valid Date.
        /// </summary>
        [TestMethod]
        public void NextDayOfWeek_WhenUsingMinValue_ShouldReturnNextValidDate()
        {
            var actual = DateOnly.MinValue.NextDayOfWeek(DayOfWeek.Friday);

            Assert.IsTrue(actual >= DateOnly.MinValue);
        }

        /// <summary>
        /// Verifies that Next Day Of Week, when Using Max Value Minus7, returns Within Range.
        /// </summary>
        [TestMethod]
        public void NextDayOfWeek_WhenUsingMaxValueMinus7_ShouldReturnWithinRange()
        {
            var input = DateOnly.MaxValue.AddDays(-7);
            var actual = input.NextDayOfWeek(input.DayOfWeek);

            Assert.IsTrue(actual <= DateOnly.MaxValue);
        }
    }
}