// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.IsLeapYear.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.IsLeapYear" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.LeapYearTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
    public void IsLeapYear_WhenCalled_ShouldReturnExpected(int year, bool expected)
    {
        DateTime input = new DateTime(year, 1, 1);
        bool actual = input.IsLeapYear();

        Assert.AreEqual(expected, actual, $"Expected leap year check for {year} to be {expected}.");
    }

}
