// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.DaysInMonth.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.DaysInMonth" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DaysInMonthTestData))]
    public void DaysInMonth_WhenCalled_ShouldReturnDaysInMonth(DateTime input, int expected)
    {
        var actual = input.DaysInMonth();
        Assert.AreEqual(expected, actual);
    }

}
