// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
	public partial class DateTimeExtensionsTests
	{
		[DataTestMethod]
		[DataRow("2024-04-01", WeekOfMonthOrdinal.First)]		// First Monday
		[DataRow("2024-04-08", WeekOfMonthOrdinal.Second)]	// Second Monday
		[DataRow("2024-04-15", WeekOfMonthOrdinal.Third)]		// Third Monday
		[DataRow("2024-04-22", WeekOfMonthOrdinal.Fourth)]	// Fourth Monday
		[DataRow("2024-04-29", WeekOfMonthOrdinal.Fifth)]		// Fifth (rare)
		public void WeekdayOrdinalInMonth_WhenCalled_ShouldReturnExpectedOrdinal(string inputDate, WeekOfMonthOrdinal expectedOrdinal)
		{
			DateTime input = DateTime.Parse(inputDate);
			WeekOfMonthOrdinal actual = input.WeekdayOrdinal();

			Assert.AreEqual(expectedOrdinal, actual);
		}

		[TestMethod]
		public void WeekdayOrdinalInMonth_WhenLeapDay_ShouldReturnCorrectOrdinal()
		{
			DateTime leapDay = new DateTime(2024, 2, 29); // Thursday
			WeekOfMonthOrdinal result = leapDay.WeekdayOrdinal();

			Assert.AreEqual(WeekOfMonthOrdinal.Fifth, result); // 1st = 1st, 8th = 2nd, ..., 29th = 5th Thursday
		}
	}
}