// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.DayName.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.Globalization;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.DayName" />, when CultureIsNull, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.DayNameFrenchTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
    public void DayName_WhenCultureIsNull_ShouldFallbackToCurrentCulture(DateTime inputDateTime, string expected)
    {
        var original = CultureInfo.CurrentCulture;
        try
        {
            CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
            var input = DateOnly.FromDateTime(inputDateTime);

            string actual = input.DayName(null!);

            Assert.AreEqual(expected, actual);
        }
        finally
        {
            CultureInfo.CurrentCulture = original;
        }
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.DayName" />, with Culture, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.DayNameTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
    public void DayName_WithCulture_ShouldReturnLocalizedName(DateTime inputDateTime, CultureInfo culture, string expected)
    {
        var input = DateOnly.FromDateTime(inputDateTime);

        string actual = input.DayName(culture);

        Assert.AreEqual(expected, actual);
    }

}
