// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
	public partial class DateTimeExtensionsTests
	{
		[DataTestMethod]
		[DataRow("2024-04-18T05:00:00", "2024-04-18T00:00:00")]
		[DataRow("2024-04-18T23:59:59", "2024-04-18T00:00:00")]
		[DataRow("2000-01-01T12:00:00", "2000-01-01T00:00:00")]
		[DataRow("0001-01-01T03:30:00", "0001-01-01T00:00:00")]
		[DataRow("9999-12-31T22:00:00", "9999-12-31T00:00:00")]
		public void Midnight_WhenCalled_ShouldReturnMidnightOnSameDate(string inputDate, string expectedDate)
		{
			DateTime input = DateTime.Parse(inputDate);
			DateTime expected = DateTime.Parse(expectedDate);
			DateTime result = input.ToMidnight();

			Assert.AreEqual(expected, result);
			Assert.AreEqual(input.Kind, result.Kind);
		}

		[TestMethod]
		public void Midnight_WhenKindIsUtc_ShouldPreserveKind()
		{
			DateTime input = new DateTime(2024, 4, 18, 9, 30, 0, DateTimeKind.Utc);
			DateTime result = input.ToMidnight();

			Assert.AreEqual(DateTimeKind.Utc, result.Kind);
			Assert.AreEqual(new DateTime(2024, 4, 18, 0, 0, 0, DateTimeKind.Utc), result);
		}

		[TestMethod]
		public void Midnight_WhenKindIsLocal_ShouldPreserveKind()
		{
			DateTime input = new DateTime(2024, 4, 18, 22, 15, 0, DateTimeKind.Local);
			DateTime result = input.ToMidnight();

			Assert.AreEqual(DateTimeKind.Local, result.Kind);
			Assert.AreEqual(new DateTime(2024, 4, 18, 0, 0, 0, DateTimeKind.Local), result);
		}

		[TestMethod]
		public void Midnight_WhenKindIsUnspecified_ShouldPreserveKind()
		{
			DateTime input = new DateTime(2024, 4, 18, 18, 45, 0, DateTimeKind.Unspecified);
			DateTime result = input.ToMidnight();

			Assert.AreEqual(DateTimeKind.Unspecified, result.Kind);
			Assert.AreEqual(new DateTime(2024, 4, 18, 0, 0, 0, DateTimeKind.Unspecified), result);
		}

		[TestMethod]
		public void Midnight_WhenUsingMinValue_ShouldReturnMidnight()
		{
			DateTime input = DateTime.MinValue.Date;
			DateTime result = input.ToMidnight();

			Assert.AreEqual(new DateTime(1, 1, 1, 0, 0, 0), result);
		}

		[TestMethod]
		public void Midnight_WhenUsingMaxValue_ShouldReturnMidnight()
		{
			DateTime input = DateTime.MaxValue.Date;
			DateTime result = input.ToMidnight();

			Assert.AreEqual(new DateTime(9999, 12, 31, 0, 0, 0), result);
		}
	}
}
