// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.FirstDateOfYear.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.FirstDateOfYear" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.FirstDateOfYearTestData), typeof(DateTimeExtensionsTests))]
    public void FirstDateOfYear_WhenCalled_ShouldReturnExpectedStartOfYear(DateTime inputDateTime, DateTime expectedDateTime)
    {
        DateOnly input = DateOnly.FromDateTime(inputDateTime);
        DateOnly expected = DateOnly.FromDateTime(expectedDateTime);

        DateOnly actual = input.FirstDateOfYear();

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.FirstDateOfYear" />, when MaxValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void FirstDateOfYear_WhenMaxValue_ShouldReturnExpected()
    {
        DateOnly max = DateOnly.MaxValue; // 9999-12-31
        DateOnly actual = max.FirstDateOfYear();

        Assert.AreEqual(new DateOnly(9999, 1, 1), actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.FirstDateOfYear" />, when MinValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void FirstDateOfYear_WhenMinValue_ShouldReturnExpected()
    {
        DateOnly min = DateOnly.MinValue; // 0001-01-01
        DateOnly actual = min.FirstDateOfYear();

        Assert.AreEqual(new DateOnly(1, 1, 1), actual);
    }

}
