// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.FromUnixTimeSeconds.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions
{
    public partial class DateOnlyExtensionsTests
    {

        /// <summary>
        /// Verifies that From Unix Time Seconds, when Valid Input, returns Expected.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.FromUnixTimeSecondsTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Property)]
        public void FromUnixTimeSeconds_WhenValidInput_ShouldReturnExpected(long input, DateTime expectedDateTime)
        {
            var expected = DateOnly.FromDateTime(expectedDateTime);
            var actual = DateOnlyExtensions.FromUnixTimeSeconds(input);

            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that From Unix Time Seconds, when Below Minimum, throws Exactly.
        /// </summary>
        [TestMethod]
        public void FromUnixTimeSeconds_WhenBelowMinimum_ShouldThrowExactly()
        {
            long belowMin = -62135596801; // 1 second before DateTime.MinValue

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.FromUnixTimeSeconds(belowMin);
            });
        }

        /// <summary>
        /// Verifies that From Unix Time Seconds, when Above Maximum, throws Exactly.
        /// </summary>
        [TestMethod]
        public void FromUnixTimeSeconds_WhenAboveMaximum_ShouldThrowExactly()
        {
            long aboveMax = 253402300800; // 1 second after DateTime.MaxValue

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.FromUnixTimeSeconds(aboveMax);
            });
        }
    }
}