// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
	public partial class DateTimeExtensionsTests
	{

		[DataTestMethod]
		[DataRow("2023-02-15", 28)]
		[DataRow("2024-02-15", 29)]
		[DataRow("2023-02-15", 28)]
        [DataRow("2023-01-01", 31)]
        public void DaysInMonth_WhenCalled_ShouldReturnDaysInMonth(string inputDate, int expected)
        {
            DateTime input = DateTime.Parse(inputDate);

            Assert.AreEqual(expected, input.DaysInMonth());
        }
        
    }
}
