// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.ToUnixTimeSeconds.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.ToUnixTimeSeconds" />, RoundTripWithFromUnixTimeSeconds, returns the expected value.
    /// </summary>
    [TestMethod]
    public void ToUnixTimeSeconds_RoundTripWithFromUnixTimeSeconds_ShouldMatchUtc()
    {
        DateOnly input = new DateOnly(2024, 4, 18);
        long seconds = input.ToUnixTimeSeconds();

        DateOnly roundTrip = DateOnlyExtensions.FromUnixTimeSeconds(seconds);

        Assert.AreEqual(input, roundTrip);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.ToUnixTimeSeconds" />, when UsingMaxValue, returns <see langword="true" />.
    /// </summary>
    [TestMethod]
    public void ToUnixTimeSeconds_WhenUsingMaxValue_ShouldBePositiveLarge()
    {
        long actual = DateOnly.MaxValue.ToUnixTimeSeconds();

        Assert.IsTrue(actual > 0);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.ToUnixTimeSeconds" />, when UsingMinValue, returns <see langword="true" />.
    /// </summary>
    [TestMethod]
    public void ToUnixTimeSeconds_WhenUsingMinValue_ShouldBeNegativeLarge()
    {
        long actual = DateOnly.MinValue.ToUnixTimeSeconds();

        Assert.IsTrue(actual < 0);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.ToUnixTimeSeconds" />, when UtcInput, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.FromUnixTimeSecondsTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Property)]
    public void ToUnixTimeSeconds_WhenUtcInput_ShouldReturnExpected(long expected, DateTime inputDateTime)
    {
        DateOnly input = DateOnly.FromDateTime(inputDateTime);
        long remainder = expected % 86400L;
        long flooredExpected = expected >= 0
            ? expected - remainder                                      // floor to 00:00 UTC
            : expected - remainder - (remainder != 0 ? 86400L : 0);        // ceil toward earlier day

        long actual = input.ToUnixTimeSeconds();

        Assert.AreEqual(flooredExpected, actual);
    }

}
