// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.FromUnixTimeMilliseconds.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
    public partial class DateOnlyExtensionsTests
    {
        /// <summary>
        /// Verifies that From Unix Time Milliseconds, when Valid Input, returns Expected.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.FromUnixTimeMillisecondsTestData), typeof(DateTimeExtensionsTests),DynamicDataSourceType.Property)]
        public void FromUnixTimeMilliseconds_WhenValidInput_ShouldReturnExpected(long input, DateTime expectedDateTime)
        {
            var expected=DateOnly.FromDateTime(expectedDateTime);
            var actual = DateOnlyExtensions.FromUnixTimeMilliseconds(input);

            Assert.AreEqual(expected, actual);
        }

        /// <summary>
        /// Verifies that From Unix Time Milliseconds, when Below Minimum, throws Exactly.
        /// </summary>
        [TestMethod]
        public void FromUnixTimeMilliseconds_WhenBelowMinimum_ShouldThrowExactly()
        {
            long belowMin = -62135596800001; // 1 ms before DateOnly.MinValue

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.FromUnixTimeMilliseconds(belowMin);
            });
        }

        /// <summary>
        /// Verifies that From Unix Time Milliseconds, when Above Maximum, throws Exactly.
        /// </summary>
        [TestMethod]
        public void FromUnixTimeMilliseconds_WhenAboveMaximum_ShouldThrowExactly()
        {
            long aboveMax = 253402300800000; // 1 ms after DateOnly.MaxValue

            Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
            {
                _ = DateTimeExtensions.FromUnixTimeMilliseconds(aboveMax);
            });
        }
    }
}