// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.FirstDateOfWeekInMonth.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfWeekInMonth" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DataRow(DateTimeKind.Unspecified)]
    [DataRow(DateTimeKind.Utc)]
    [DataRow(DateTimeKind.Local)]
    public void FirstDateOfWeekInMonth_WhenCalled_ShouldPreserveDateTimeKind(DateTimeKind kind)
    {
        DateTime input = new DateTime(2024, 7, 5, 10, 0, 0, kind);
        DateTime actual = input.FirstDateOfWeekInMonth(DayOfWeek.Saturday);

        Assert.AreEqual(kind, actual.Kind);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfWeekInMonth" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(FirstDateOfWeekInMonthTestData))]
    public void FirstDateOfWeekInMonth_WhenCalled_ShouldReturnExpectedDate(DateTime input, DayOfWeek dayOfWeek, DateTime expected)
    {
        DateTime actual = input.FirstDateOfWeekInMonth(dayOfWeek);

        Assert.AreEqual(expected, actual);
    }

    public void FirstDateOfWeekInMonth_WhenCalled_ShouldTruncateTime()
    {
        DateTime input = new DateTime(2024, 7, 5, 10, 5, 0, DateTimeKind.Local);
        DateTime actual = input.FirstDateOfWeekInMonth(DayOfWeek.Saturday);

        Assert.AreEqual(TimeSpan.Zero, actual.TimeOfDay);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfWeekInMonth" />, when InvalidDayOfWeek, throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void FirstDateOfWeekInMonth_WhenInvalidDayOfWeek_ShouldThrowExactly()
    {
        DateTime input = new DateTime(2024, 4, 1);
        var invalidDay = (DayOfWeek)999;

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            _ = input.FirstDateOfWeekInMonth(invalidDay);
        });
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfWeekInMonth" />, when UsingMaxValue, returns <see langword="true" />.
    /// </summary>
    [TestMethod]
    public void FirstDateOfWeekInMonth_WhenUsingMaxValue_ShouldReturnValidResult()
    {
        DateTime actual = DateTime.MaxValue.FirstDateOfWeekInMonth(DayOfWeek.Friday);

        Assert.IsTrue(actual <= DateTime.MaxValue);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfWeekInMonth" />, when UsingMinValue, returns <see langword="true" />.
    /// </summary>
    [TestMethod]
    public void FirstDateOfWeekInMonth_WhenUsingMinValue_ShouldReturnValidResult()
    {
        DateTime actual = DateTime.MinValue.FirstDateOfWeekInMonth(DayOfWeek.Monday);

        Assert.IsTrue(actual >= DateTime.MinValue && actual <= DateTime.MinValue.AddMonths(1).AddDays(-1));
    }

}
