// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.Quarter.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{
    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.GetQuarter" />, when UsingQuarterDefinition, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(QuarterTestData), DynamicDataSourceType.Method)]
    public void GetQuarter_WhenUsingQuarterDefinition_ShouldReturnExpectedQuarter(DateTime input, CalendarQuarterDefinition definition, int expected)
    {
        int actual = input.Quarter(definition);

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.GetQuarter" />, when OnlyDateTime, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(QuarterJanuaryDecemberTestData), DynamicDataSourceType.Method)]
    public void GetQuarter_WhenOnlyDateTime_ShouldReturnExpectedQuarter(DateTime input, int expected)
    {
        int actual = input.Quarter();

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.GetQuarter" />, when UsingValidProvider, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.ValidQuarterProvider.QuarterTestData), typeof(DateTimeExtensionsTests.ValidQuarterProvider), DynamicDataSourceType.Method)]
    public void GetQuarter_WhenUsingValidProvider_ShouldReturnExpectedQuarter(DateTime input, int expected)
    {
        var provider = new DateTimeExtensionsTests.ValidQuarterProvider();
        int actual = input.Quarter(provider);

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.GetQuarter" />, when UsingInvalidProvider, throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void GetQuarter_WhenUsingInvalidProvider_ShouldThrowExactly()
    {
        var input = new DateTime(2024, 4, 20);
        var provider = new DateTimeExtensionsTests.InValidQuarterProvider();

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            _ = input.Quarter(provider);
        });
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.GetQuarter" />, when UsingCustomQuarterDefinitionWithoutProvider, throws <see cref="InvalidOperationException" />.
    /// </summary>
    [TestMethod]
    public void GetQuarter_WhenUsingCustomQuarterDefinitionWithoutProvider_ShouldThrowExactly()
    {
        var input = new DateTime(2024, 4, 20);

        Assert.ThrowsExactly<InvalidOperationException>(() =>
        {
            _ = input.Quarter(CalendarQuarterDefinition.Custom);
        });
    }
}
