// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensionsTests.FirstDateOfYear.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions;

public partial class DateTimeExtensionsTests
{
    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfYear" />, when Called, returns the expected value.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(FirstDateOfYearTestData))]
    public void FirstDateOfYear_WhenCalled_ShouldReturnExpectedStartOfYear(DateTime input, DateTime expected)
    {
        DateTime actual = input.FirstDateOfYear();

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfYear" /> returns the expected value.
    /// </summary>
    [TestMethod]
    [DataRow(DateTimeKind.Unspecified)]
    [DataRow(DateTimeKind.Utc)]
    [DataRow(DateTimeKind.Local)]
    public void FirstDateOfYear_ShouldPreserveDateTimeKind(DateTimeKind kind)
    {
        var input = new DateTime(2024, 4, 18, 12, 0, 0, kind);
        var actual = input.FirstDateOfYear();

        Assert.AreEqual(kind, actual.Kind);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfYear" />, when MinValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void FirstDateOfYear_WhenMinValue_ShouldReturnExpected()
    {
        DateTime min = DateTime.MinValue; // 0001-01-01
        DateTime actual = min.FirstDateOfYear();

        Assert.AreEqual(new DateTime(1, 1, 1), actual);
    }

    /// <summary>
    /// Verifies that <see cref="DateTimeExtensions.FirstDateOfYear" />, when MaxValue, returns the expected value.
    /// </summary>
    [TestMethod]
    public void FirstDateOfYear_WhenMaxValue_ShouldReturnExpected()
    {
        DateTime max = DateTime.MaxValue; // 9999-12-31
        DateTime actual = max.FirstDateOfYear();

        Assert.AreEqual(new DateTime(9999, 1, 1), actual);
    }
}
