// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.PreviousDayOfWeek.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

﻿// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions;

public partial class DateOnlyExtensionsTests
{

    /// <summary>
    /// Verifies that <see cref="DateOnlyExtensions.PreviousDayOfWeek(DateOnly, DayOfWeek)" /> returns the prior occurrence of the requested <see cref="DayOfWeek" /> for each <c>(input, target)</c> pair.
    /// </summary>
    [TestMethod]
    [DynamicData(nameof(DateTimeExtensionsTests.PreviousDayOfWeekTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
    public void PreviousDayOfWeek_WhenCalled_ShouldReturnExpectedDate(DateTime inputDateOnly, DayOfWeek targetDay, DateTime expectedDateOnly)
    {
        var input = DateOnly.FromDateTime(inputDateOnly);
        var expected = DateOnly.FromDateTime(expectedDateOnly);

        var actual = input.PreviousDayOfWeek(targetDay);

        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Verifies that an undefined <see cref="DayOfWeek" /> value throws <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    [TestMethod]
    public void PreviousDayOfWeek_WhenEnumIsInvalid_ShouldThrowExactly()
    {
        var input = new DateOnly(2024, 4, 18);

        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            _ = input.PreviousDayOfWeek((DayOfWeek)999);
        });
    }

    /// <summary>
    /// Verifies that <see cref="DateOnly.MinValue" /> + 7 days returning the prior Monday yields a result on or after <see cref="DateOnly.MinValue" />.
    /// </summary>
    [TestMethod]
    public void PreviousDayOfWeek_WhenUsingMinValue_ShouldReturnSameOrGreater()
    {
        var actual = DateOnly.MinValue.AddDays(7).PreviousDayOfWeek(DayOfWeek.Monday);

        Assert.IsTrue(actual >= DateOnly.MinValue);
    }

    /// <summary>
    /// Verifies that <see cref="DateOnly.MaxValue" /> targeting Saturday returns a valid result on or before <see cref="DateOnly.MaxValue" />.
    /// </summary>
    [TestMethod]
    public void PreviousDayOfWeek_WhenUsingMaxValue_ShouldSucceed()
    {
        var input = DateOnly.MaxValue;
        var actual = input.PreviousDayOfWeek(DayOfWeek.Saturday);

        Assert.IsTrue(actual <= DateOnly.MaxValue);
    }
}
