// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;
using System.Globalization;

namespace Bodu.Extensions
{
	public partial class DateOnlyExtensionsTests
	{

		[DataTestMethod]
		[DataRow("2024-04-17", "en-US", "2024-04-20")] // Wednesday → Saturday (en-US = Sunday start)
		[DataRow("2024-04-17", "en-GB", "2024-04-21")] // Wednesday → Sunday (en-GB = Monday start)
		[DataRow("2024-04-15", "en-US", "2024-04-20")] // Monday → Saturday
		[DataRow("2024-04-14", "en-US", "2024-04-20")] // Sunday → Saturday
		[DataRow("2024-04-15", "fr-FR", "2024-04-21")] // Monday → Sunday
		public void LastDayOfTheWeek_WithCulture_ShouldReturnExpected(string inputDate, string cultureName, string expectedDate)
		{
			DateOnly input = DateOnly.Parse(inputDate);
			CultureInfo culture = new CultureInfo(cultureName);
			DateOnly expected = DateOnly.Parse(expectedDate);
			DateOnly result = input.LastDayOfWeek(culture);

			Assert.AreEqual(expected, result);
		}

		[TestMethod]
		public void LastDayOfTheWeek_WhenCultureIsNull_ShouldUseCurrentCulture()
		{
			var originalCulture = CultureInfo.CurrentCulture;
			try
			{
				CultureInfo.CurrentCulture = DateTimeExtensionsTests.TestCulture; //FirstDayOfWeek = Wednesday

				DateOnly input = new DateOnly(2024, 4, 18); // Thursday
															// Forward to next Tuesday → 2024-04-23
				DateOnly expected = new DateOnly(2024, 4, 23);

				DateOnly result = input.LastDayOfWeek(null!);

				Assert.AreEqual(expected, result, "Expected fallback to CultureInfo.CurrentCulture with Wednesday as start of week.");
			}
			finally
			{
				CultureInfo.CurrentCulture = originalCulture; // Always restore
			}
		}

		[TestMethod]
		public void LastDayOfTheWeek_WhenUsingMinValue_ShouldSucceed()
		{
			DateOnly input = DateOnly.MinValue;
			DateOnly result = input.LastDayOfWeek(CultureInfo.InvariantCulture);

			Assert.IsTrue(result >= DateOnly.MinValue);
		}


		[TestMethod]
		public void LastDayOfTheWeek_WhenMinValueAndCultureIsUS_ShouldReturnThrowArgumentOutOfRangeException()
		{
			DateOnly min = DateOnly.MaxValue;
			var culture = new CultureInfo("en-US");// Sunday is first day

			Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
			{
				_ = min.LastDayOfWeek(culture); // is outside the range for a DateOnly value
			});
		}

		[TestMethod]
		public void LastDayOfTheWeek_WhenUsingMaxValue_ShouldSucceed()
		{
			DateOnly max = DateOnly.MaxValue;
			var result = max.LastDayOfWeek(new CultureInfo("fa-IR")); // Friday is last day of week

			Assert.AreEqual(max, result);
		}
	}
}
