// ---------------------------------------------------------------------------------------------------------------
// <copyright file="DateOnlyExtensionsTests.FirstDayOfMonth.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

// ---------------------------------------------------------------------------------------------------------------
// <auto-generated />
// ---------------------------------------------------------------------------------------------------------------

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Bodu.Extensions;

namespace Bodu.Extensions
{
    public partial class DateOnlyExtensionsTests
    {

        /// <summary>
        /// Verifies that <see cref="DateOnlyExtensions.FirstDayOfMonth" />, when Called, returns the expected value.
        /// </summary>
        [TestMethod]
        [DynamicData(nameof(DateTimeExtensionsTests.FirstDayOfMonthDataTestData), typeof(DateTimeExtensionsTests), DynamicDataSourceType.Method)]
        public void FirstDayOfMonth_WhenCalled_ShouldReturnExpectedDate(DateTime inputDateTime, DateTime expectedDateTime)
        {
            var input = DateOnly.FromDateTime(inputDateTime);
            var expected = DateOnly.FromDateTime(expectedDateTime);
            var actual = input.FirstDayOfMonth();

            Assert.AreEqual(expected, actual);
        }
    }
}
