//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} action must be initialized with no {1} items..
        /// </summary>
        internal static string Arg_Invalid_ActionRequiresNull {
            get {
                return ResourceManager.GetString("Arg_Invalid_ActionRequiresNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array must not be empty..
        /// </summary>
        internal static string Arg_Invalid_ArrayIsZeroLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayIsZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array length must be exactly {0}..
        /// </summary>
        internal static string Arg_Invalid_ArrayLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements to copy exceeds the capacity available..
        /// </summary>
        internal static string Arg_Invalid_ArrayLengthExceedsCapacity {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayLengthExceedsCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the array must be a multiple of {0}..
        /// </summary>
        internal static string Arg_Invalid_ArrayLengthMultipleOf {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayLengthMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound of the target array must be zero..
        /// </summary>
        internal static string Arg_Invalid_ArrayNonZeroLowerBound {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayNonZeroLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array contains non-numeric values..
        /// </summary>
        internal static string Arg_Invalid_ArrayNumericOnly {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero or positive, and less than the number of elements in the {0}..
        /// </summary>
        internal static string Arg_Invalid_ArrayOffset {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of {0} and {1} exceeds the number of elements in the {2}..
        /// </summary>
        internal static string Arg_Invalid_ArrayOffsetOrLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayOffsetOrLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array is too short. The minimum required length from the specified index is {0}..
        /// </summary>
        internal static string Arg_Invalid_ArrayTooShort {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target array type is not compatible with the type of items in the collection..
        /// </summary>
        internal static string Arg_Invalid_ArrayType {
            get {
                return ResourceManager.GetString("Arg_Invalid_ArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string Arg_Invalid_CollectionIsEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection must not be read-only..
        /// </summary>
        internal static string Arg_Invalid_CollectionReadOnly {
            get {
                return ResourceManager.GetString("Arg_Invalid_CollectionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection contains insufficient elements. At least {0} element(s) are required..
        /// </summary>
        internal static string Arg_Invalid_CollectionTooSmall {
            get {
                return ResourceManager.GetString("Arg_Invalid_CollectionTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be converted to type {0}..
        /// </summary>
        internal static string Arg_Invalid_Conversion {
            get {
                return ResourceManager.GetString("Arg_Invalid_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom has no canonical WeekPattern; pass a WeekPattern directly..
        /// </summary>
        internal static string Arg_Invalid_CustomHasNoCanonicalWeekPattern {
            get {
                return ResourceManager.GetString("Arg_Invalid_CustomHasNoCanonicalWeekPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination must be exactly the size required for the decoded characters..
        /// </summary>
        internal static string Arg_Invalid_DestinationNotExactSizeForDecoded {
            get {
                return ResourceManager.GetString("Arg_Invalid_DestinationNotExactSizeForDecoded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination must be exactly the size required for the encoded bytes..
        /// </summary>
        internal static string Arg_Invalid_DestinationNotExactSizeForEncoded {
            get {
                return ResourceManager.GetString("Arg_Invalid_DestinationNotExactSizeForEncoded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The destination {0} must be at least as long as the source {1}..
        /// </summary>
        internal static string Arg_Invalid_DestinationTooSmall {
            get {
                return ResourceManager.GetString("Arg_Invalid_DestinationTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination is too small to receive the decoded characters..
        /// </summary>
        internal static string Arg_Invalid_DestinationTooSmallForDecoded {
            get {
                return ResourceManager.GetString("Arg_Invalid_DestinationTooSmallForDecoded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination is too small to receive the encoded characters..
        /// </summary>
        internal static string Arg_Invalid_DestinationTooSmallForEncoded {
            get {
                return ResourceManager.GetString("Arg_Invalid_DestinationTooSmallForEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain duplicate keys..
        /// </summary>
        internal static string Arg_Invalid_DuplicateDictionaryKey {
            get {
                return ResourceManager.GetString("Arg_Invalid_DuplicateDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set already contains the specified value..
        /// </summary>
        internal static string Arg_Invalid_DuplicateSetValue {
            get {
                return ResourceManager.GetString("Arg_Invalid_DuplicateSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot contain empty elements..
        /// </summary>
        internal static string Arg_Invalid_EmptyCollectionElement {
            get {
                return ResourceManager.GetString("Arg_Invalid_EmptyCollectionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain empty keys..
        /// </summary>
        internal static string Arg_Invalid_EmptyDictionaryKey {
            get {
                return ResourceManager.GetString("Arg_Invalid_EmptyDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format string is invalid..
        /// </summary>
        internal static string Arg_Invalid_FormatString {
            get {
                return ResourceManager.GetString("Arg_Invalid_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be greater than or equal to the value of {0}..
        /// </summary>
        internal static string Arg_Invalid_GreaterThanOrEqualOtherParameter {
            get {
                return ResourceManager.GetString("Arg_Invalid_GreaterThanOrEqualOtherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be greater than the value of {0}..
        /// </summary>
        internal static string Arg_Invalid_GreaterThanOtherParameter {
            get {
                return ResourceManager.GetString("Arg_Invalid_GreaterThanOtherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is too short. At least {0} elements are required..
        /// </summary>
        internal static string Arg_Invalid_InputTooShort {
            get {
                return ResourceManager.GetString("Arg_Invalid_InputTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inner arrays must have the same length..
        /// </summary>
        internal static string Arg_Invalid_JaggedArrayInnerLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_JaggedArrayInnerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be less than or equal to the value of {0}..
        /// </summary>
        internal static string Arg_Invalid_LessThanOrEqualOtherParameter {
            get {
                return ResourceManager.GetString("Arg_Invalid_LessThanOrEqualOtherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be less than the value of {0}..
        /// </summary>
        internal static string Arg_Invalid_LessThanOtherParameter {
            get {
                return ResourceManager.GetString("Arg_Invalid_LessThanOtherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of the string is less than the length of the suffix..
        /// </summary>
        internal static string Arg_Invalid_MaxIsLessThanSuffixLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_MaxIsLessThanSuffixLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0} to be compared..
        /// </summary>
        internal static string Arg_Invalid_MustBeComparableType {
            get {
                return ResourceManager.GetString("Arg_Invalid_MustBeComparableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}..
        /// </summary>
        internal static string Arg_Invalid_MustBeOfType {
            get {
                return ResourceManager.GetString("Arg_Invalid_MustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot contain null elements..
        /// </summary>
        internal static string Arg_Invalid_NullCollectionElement {
            get {
                return ResourceManager.GetString("Arg_Invalid_NullCollectionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain null keys..
        /// </summary>
        internal static string Arg_Invalid_NullDictionaryKey {
            get {
                return ResourceManager.GetString("Arg_Invalid_NullDictionaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain null values..
        /// </summary>
        internal static string Arg_Invalid_NullDictionaryValue {
            get {
                return ResourceManager.GetString("Arg_Invalid_NullDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list cannot contain null elements..
        /// </summary>
        internal static string Arg_Invalid_NullListElement {
            get {
                return ResourceManager.GetString("Arg_Invalid_NullListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordinal &apos;{0}&apos; does not exist for {1} in {2}..
        /// </summary>
        internal static string Arg_Invalid_OrdinalDoesNotExistForMonth {
            get {
                return ResourceManager.GetString("Arg_Invalid_OrdinalDoesNotExistForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output buffer is too small. At least {0} elements are required..
        /// </summary>
        internal static string Arg_Invalid_OutputBufferTooSmall {
            get {
                return ResourceManager.GetString("Arg_Invalid_OutputBufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is required when &apos;{1}&apos; is set to {2}..
        /// </summary>
        internal static string Arg_Invalid_ParameterRequiredIf {
            get {
                return ResourceManager.GetString("Arg_Invalid_ParameterRequiredIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value collection contains one or more null elements..
        /// </summary>
        internal static string Arg_Invalid_ParamsContainsNullValue {
            get {
                return ResourceManager.GetString("Arg_Invalid_ParamsContainsNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a positive number and a multiple of {0}..
        /// </summary>
        internal static string Arg_Invalid_PositiveMultipleOf {
            get {
                return ResourceManager.GetString("Arg_Invalid_PositiveMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a positive power of two..
        /// </summary>
        internal static string Arg_Invalid_PowerOfTwo {
            get {
                return ResourceManager.GetString("Arg_Invalid_PowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom definitions require an external provider that implements {0}..
        /// </summary>
        internal static string Arg_Invalid_ProviderInterface {
            get {
                return ResourceManager.GetString("Arg_Invalid_ProviderInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified range overlaps an existing range..
        /// </summary>
        internal static string Arg_Invalid_RangeOverlap {
            get {
                return ResourceManager.GetString("Arg_Invalid_RangeOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range start must be less than the range end..
        /// </summary>
        internal static string Arg_Invalid_RangeStartNotLessThanEnd {
            get {
                return ResourceManager.GetString("Arg_Invalid_RangeStartNotLessThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single-dimension arrays are supported..
        /// </summary>
        internal static string Arg_Invalid_RankMultiDimensionArray {
            get {
                return ResourceManager.GetString("Arg_Invalid_RankMultiDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The replacement string '{0}' cannot be encoded by the specified encoding..
        /// </summary>
        internal static string Arg_Invalid_ReplacementNotEncodable {
            get {
                return ResourceManager.GetString("Arg_Invalid_ReplacementNotEncodable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value is a single Unicode surrogate character, which must be written as a pair. Consider passing a character array instead..
        /// </summary>
        internal static string Arg_Invalid_SingleSurrogateCharacter {
            get {
                return ResourceManager.GetString("Arg_Invalid_SingleSurrogateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The span length must be exactly {0}..
        /// </summary>
        internal static string Arg_Invalid_SpanLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_SpanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the span must be a multiple of {0}..
        /// </summary>
        internal static string Arg_Invalid_SpanLengthMultipleOf {
            get {
                return ResourceManager.GetString("Arg_Invalid_SpanLengthMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The span is too short. The minimum required length from the specified index is {0}..
        /// </summary>
        internal static string Arg_Invalid_SpanTooShort {
            get {
                return ResourceManager.GetString("Arg_Invalid_SpanTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write beyond the end of the stream..
        /// </summary>
        internal static string Arg_Invalid_StreamLengthExceeded {
            get {
                return ResourceManager.GetString("Arg_Invalid_StreamLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string comparison type is not supported..
        /// </summary>
        internal static string Arg_Invalid_StringComparison {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be empty or consist only of white-space characters..
        /// </summary>
        internal static string Arg_Invalid_StringEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be empty..
        /// </summary>
        internal static string Arg_Invalid_StringIsEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string length must be exactly {0} characters..
        /// </summary>
        internal static string Arg_Invalid_StringLength {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string length must be between {0} and {1} characters..
        /// </summary>
        internal static string Arg_Invalid_StringLengthRange {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must contain numeric digits only..
        /// </summary>
        internal static string Arg_Invalid_StringMustBeDigits {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringMustBeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null or empty..
        /// </summary>
        internal static string Arg_Invalid_StringNullOrEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must not exceed {0} characters..
        /// </summary>
        internal static string Arg_Invalid_StringTooLong {
            get {
                return ResourceManager.GetString("Arg_Invalid_StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for &apos;{0}&apos; must be {1}, but was {2}..
        /// </summary>
        internal static string Arg_Invalid_ValueForOperation {
            get {
                return ResourceManager.GetString("Arg_Invalid_ValueForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must equal {0}..
        /// </summary>
        internal static string Arg_Invalid_ValuesNotEqual {
            get {
                return ResourceManager.GetString("Arg_Invalid_ValuesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor supports only the &apos;{0}&apos; or &apos;{1}&apos; actions..
        /// </summary>
        internal static string Arg_Invalid_WrongAction2ForCtor {
            get {
                return ResourceManager.GetString("Arg_Invalid_WrongAction2ForCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor supports only the &apos;{0}&apos;, &apos;{1}&apos;, or &apos;{2}&apos; actions..
        /// </summary>
        internal static string Arg_Invalid_WrongAction3ForCtor {
            get {
                return ResourceManager.GetString("Arg_Invalid_WrongAction3ForCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor supports only the &apos;{0}&apos; action..
        /// </summary>
        internal static string Arg_Invalid_WrongActionForCtor {
            get {
                return ResourceManager.GetString("Arg_Invalid_WrongActionForCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot advance past the end of the current buffer..
        /// </summary>
        internal static string Arg_OutOfRange_AdvancePastBufferEnd {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_AdvancePastBufferEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour, Minute, and Second parameters describe an unrepresentable DateTime..
        /// </summary>
        internal static string Arg_OutOfRange_BadHourMinuteSecond {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_BadHourMinuteSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year, Month, and Day parameters describe an unrepresentable DateTime..
        /// </summary>
        internal static string Arg_OutOfRange_BadYearMonthDay {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_BadYearMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count must be non-negative and must not exceed the number of available items ({0})..
        /// </summary>
        internal static string Arg_OutOfRange_CountExceedsAvailable {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_CountExceedsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source has fewer elements than requested..
        /// </summary>
        internal static string Arg_OutOfRange_CountGreaterThanSource {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_CountGreaterThanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified date {0:d} is outside the range of the configured fiscal year starting on {1:d}..
        /// </summary>
        internal static string Arg_OutOfRange_DateOutsideFiscalYear {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_DateOutsideFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; is not a defined member of the {0} enumeration..
        /// </summary>
        internal static string Arg_OutOfRange_EnumValue {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the fiscal year for date &apos;{0:yyyy-MM-dd}&apos;..
        /// </summary>
        internal static string Arg_OutOfRange_FiscalYearUndeterminable {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_FiscalYearUndeterminable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be non-negative and less than the size of {0}..
        /// </summary>
        internal static string Arg_OutOfRange_IndexValidRange {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_IndexValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month number must be between 1 and 12..
        /// </summary>
        internal static string Arg_OutOfRange_InvalidMonthNumber {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_InvalidMonthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quarter number must be between 1 and 4..
        /// </summary>
        internal static string Arg_OutOfRange_InvalidQuarterNumber {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_InvalidQuarterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length must be at least the length of the truncation marker..
        /// </summary>
        internal static string Arg_OutOfRange_MaxLengthLessThanMarker {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_MaxLengthLessThanMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be greater than the value of &apos;{0}&apos;..
        /// </summary>
        internal static string Arg_OutOfRange_MinCannotExceedMax {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_MinCannotExceedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; (U+{1:X4}) is not an ASCII uppercase alphanumeric character (&apos;0&apos; to &apos;9&apos; or &apos;A&apos; to &apos;Z&apos;)..
        /// </summary>
        internal static string Arg_OutOfRange_NotAsciiAlphanumericUppercase {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_NotAsciiAlphanumericUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; (U+{1:X4}) is not an ASCII decimal digit (&apos;0&apos; to &apos;9&apos;)..
        /// </summary>
        internal static string Arg_OutOfRange_NotAsciiDecimalDigit {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_NotAsciiDecimalDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; (U+{1:X4}) is not a hex digit (&apos;0&apos;–&apos;9&apos;, &apos;A&apos;–&apos;F&apos;, or &apos;a&apos;–&apos;f&apos;)..
        /// </summary>
        internal static string Arg_OutOfRange_NotAsciiHexDigit {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_NotAsciiHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a finite number (not NaN or infinity)..
        /// </summary>
        internal static string Arg_OutOfRange_NotFinite {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_NotFinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than {0} and less than {1}..
        /// </summary>
        internal static string Arg_OutOfRange_RequireBetweenExclusive {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireBetweenExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}, inclusive..
        /// </summary>
        internal static string Arg_OutOfRange_RequireBetweenInclusive {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireBetweenInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than {0}..
        /// </summary>
        internal static string Arg_OutOfRange_RequireGreaterThan {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to {0}..
        /// </summary>
        internal static string Arg_OutOfRange_RequireGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than {0}..
        /// </summary>
        internal static string Arg_OutOfRange_RequireLessThan {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than or equal to {0}..
        /// </summary>
        internal static string Arg_OutOfRange_RequireLessThanOrEqual {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a negative number..
        /// </summary>
        internal static string Arg_OutOfRange_RequireNegative {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero or positive..
        /// </summary>
        internal static string Arg_OutOfRange_RequireNonNegative {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero or negative..
        /// </summary>
        internal static string Arg_OutOfRange_RequireNonPositive {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireNonPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be zero..
        /// </summary>
        internal static string Arg_OutOfRange_RequireNonZero {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a positive number..
        /// </summary>
        internal static string Arg_OutOfRange_RequirePositive {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequirePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero..
        /// </summary>
        internal static string Arg_OutOfRange_RequireZero {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RequireZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting value is outside the supported range for {0}..
        /// </summary>
        internal static string Arg_OutOfRange_ResultingValueOutOfRangeForType {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_ResultingValueOutOfRangeForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified sequence range would exceed the maximum allowed value for {0}..
        /// </summary>
        internal static string Arg_OutOfRange_SequenceRangeOverflow {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_SequenceRangeOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not equal {0}..
        /// </summary>
        internal static string Arg_OutOfRange_ValuesEqual {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_ValuesEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0} is not valid for the year {1} using culture {2}..
        /// </summary>
        internal static string Arg_OutOfRange_WeekNotValidForYearAndCulture {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_WeekNotValidForYearAndCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working week must select at least one day..
        /// </summary>
        internal static string Arg_OutOfRange_WorkingWeekEmpty {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_WorkingWeekEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported {0} pattern: {1}..
        /// </summary>
        internal static string Arg_OutOfRange_WorkingWeekPatternUnsupported {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_WorkingWeekPatternUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        internal static string BufferKind_Array {
            get {
                return ResourceManager.GetString("BufferKind_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span.
        /// </summary>
        internal static string BufferKind_Span {
            get {
                return ResourceManager.GetString("BufferKind_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes in what should have been a 7 bit encoded Int32..
        /// </summary>
        internal static string Format_Invalid_7BitInt32 {
            get {
                return ResourceManager.GetString("Format_Invalid_7BitInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string contains an invalid character &apos;{0}&apos; at position {1}..
        /// </summary>
        internal static string Format_Invalid_Character {
            get {
                return ResourceManager.GetString("Format_Invalid_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file size format..
        /// </summary>
        internal static string Format_Invalid_FileSize {
            get {
                return ResourceManager.GetString("Format_Invalid_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in the correct format..
        /// </summary>
        internal static string Format_Invalid_String {
            get {
                return ResourceManager.GetString("Format_Invalid_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in the correct format. The value must be {0} characters in length..
        /// </summary>
        internal static string Format_Invalid_StringLength {
            get {
                return ResourceManager.GetString("Format_Invalid_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unselected day character must be consistent. Found &apos;{0}&apos; but expected &apos;{1}&apos;..
        /// </summary>
        internal static string Format_Invalid_UnselectedCharacter {
            get {
                return ResourceManager.GetString("Format_Invalid_UnselectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized week days format..
        /// </summary>
        internal static string Format_Invalid_WeekDays {
            get {
                return ResourceManager.GetString("Format_Invalid_WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find directory &apos;{0}&apos;..
        /// </summary>
        internal static string IO_DirNotFound_Path {
            get {
                return ResourceManager.GetString("IO_DirNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a disposed stream..
        /// </summary>
        internal static string IO_Disposed_Stream {
            get {
                return ResourceManager.GetString("IO_Disposed_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed stream..
        /// </summary>
        internal static string IO_Disposed_StreamClosed {
            get {
                return ResourceManager.GetString("IO_Disposed_StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the stream before the operation could complete..
        /// </summary>
        internal static string IO_EndOfStream_Reached {
            get {
                return ResourceManager.GetString("IO_EndOfStream_Reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read beyond the end of the stream..
        /// </summary>
        internal static string IO_EndOfStream_Read {
            get {
                return ResourceManager.GetString("IO_EndOfStream_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading from the stream..
        /// </summary>
        internal static string IO_Failed_StreamRead {
            get {
                return ResourceManager.GetString("IO_Failed_StreamRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing to the stream..
        /// </summary>
        internal static string IO_Failed_StreamWrite {
            get {
                return ResourceManager.GetString("IO_Failed_StreamWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string IO_FileNotFound_Path {
            get {
                return ResourceManager.GetString("IO_FileNotFound_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not readable..
        /// </summary>
        internal static string IO_NotSupported_StreamRead {
            get {
                return ResourceManager.GetString("IO_NotSupported_StreamRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support seeking..
        /// </summary>
        internal static string IO_NotSupported_StreamSeek {
            get {
                return ResourceManager.GetString("IO_NotSupported_StreamSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support setting its length..
        /// </summary>
        internal static string IO_NotSupported_StreamSetLength {
            get {
                return ResourceManager.GetString("IO_NotSupported_StreamSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support timeouts..
        /// </summary>
        internal static string IO_NotSupported_StreamTimeout {
            get {
                return ResourceManager.GetString("IO_NotSupported_StreamTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not writable..
        /// </summary>
        internal static string IO_NotSupported_StreamWrite {
            get {
                return ResourceManager.GetString("IO_NotSupported_StreamWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given key &apos;{0}&apos; was not present in the dictionary..
        /// </summary>
        internal static string KeyNotFound_Dictionary {
            get {
                return ResourceManager.GetString("KeyNotFound_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key was not contained in any range..
        /// </summary>
        internal static string KeyNotFound_Range {
            get {
                return ResourceManager.GetString("KeyNotFound_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activator.CreateInstance returned null for type &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_ActivatorReturnedNull {
            get {
                return ResourceManager.GetString("Op_Invalid_ActivatorReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has already been finalized and cannot be reused..
        /// </summary>
        internal static string Op_Invalid_AlreadyFinalized {
            get {
                return ResourceManager.GetString("Op_Invalid_AlreadyFinalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance has already been initialized..
        /// </summary>
        internal static string Op_Invalid_AlreadyInitialized {
            get {
                return ResourceManager.GetString("Op_Invalid_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type could not be resolved..
        /// </summary>
        internal static string Op_Invalid_ArrayElementTypeUnresolved {
            get {
                return ResourceManager.GetString("Op_Invalid_ArrayElementTypeUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for attribute &apos;{1}&apos;..
        /// </summary>
        internal static string Op_Invalid_AttributeValue {
            get {
                return ResourceManager.GetString("Op_Invalid_AttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capacity has been exhausted..
        /// </summary>
        internal static string Op_Invalid_CapacityExhausted {
            get {
                return ResourceManager.GetString("Op_Invalid_CapacityExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected for &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_CircularDependency {
            get {
                return ResourceManager.GetString("Op_Invalid_CircularDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular reference detected for &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_CircularReference {
            get {
                return ResourceManager.GetString("Op_Invalid_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string Op_Invalid_CollectionEmpty {
            get {
                return ResourceManager.GetString("Op_Invalid_CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection was modified; enumerator operations may not execute..
        /// </summary>
        internal static string Op_Invalid_CollectionModified {
            get {
                return ResourceManager.GetString("Op_Invalid_CollectionModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection could not produce a stable snapshot under sustained concurrent modification..
        /// </summary>
        internal static string Op_Invalid_ConcurrentSnapshotUnstable {
            get {
                return ResourceManager.GetString("Op_Invalid_ConcurrentSnapshotUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert type {0} to {1}..
        /// </summary>
        internal static string Op_Invalid_Conversion {
            get {
                return ResourceManager.GetString("Op_Invalid_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the key &apos;{0}&apos; has already been added..
        /// </summary>
        internal static string Op_Invalid_DuplicateKey {
            get {
                return ResourceManager.GetString("Op_Invalid_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence is empty..
        /// </summary>
        internal static string Op_Invalid_EmptySequence {
            get {
                return ResourceManager.GetString("Op_Invalid_EmptySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator has been exhausted..
        /// </summary>
        internal static string Op_Invalid_EnumeratorExhausted {
            get {
                return ResourceManager.GetString("Op_Invalid_EnumeratorExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has either not started or has already finished..
        /// </summary>
        internal static string Op_Invalid_EnumeratorNotOnElement {
            get {
                return ResourceManager.GetString("Op_Invalid_EnumeratorNotOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eviction policy &apos;{0}&apos; produced no candidate while the dictionary is at capacity..
        /// </summary>
        internal static string Op_Invalid_EvictionProducedNoCandidate {
            get {
                return ResourceManager.GetString("Op_Invalid_EvictionProducedNoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory returned null for type &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("Op_Invalid_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MemoryStream does not expose its underlying buffer..
        /// </summary>
        internal static string Op_Invalid_MemoryStreamBufferInaccessible {
            get {
                return ResourceManager.GetString("Op_Invalid_MemoryStreamBufferInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required attribute &apos;{0}&apos; on element &apos;{1}&apos;..
        /// </summary>
        internal static string Op_Invalid_MissingRequiredAttribute {
            get {
                return ResourceManager.GetString("Op_Invalid_MissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input data was provided..
        /// </summary>
        internal static string Op_Invalid_NoInputData {
            get {
                return ResourceManager.GetString("Op_Invalid_NoInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance has not been initialized..
        /// </summary>
        internal static string Op_Invalid_NotInitialized {
            get {
                return ResourceManager.GetString("Op_Invalid_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify the collection during a change notification event..
        /// </summary>
        internal static string Op_Invalid_ReentrancyNotAllowed {
            get {
                return ResourceManager.GetString("Op_Invalid_ReentrancyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence contains an invalid item..
        /// </summary>
        internal static string Op_Invalid_SequenceContainsInvalidElement {
            get {
                return ResourceManager.GetString("Op_Invalid_SequenceContainsInvalidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence contains no matching elements..
        /// </summary>
        internal static string Op_Invalid_SequenceNoMatch {
            get {
                return ResourceManager.GetString("Op_Invalid_SequenceNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout cannot be changed after the lock has already been established..
        /// </summary>
        internal static string Op_Invalid_TimeoutAlreadyEstablished {
            get {
                return ResourceManager.GetString("Op_Invalid_TimeoutAlreadyEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown eviction policy &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_UnknownEvictionPolicy {
            get {
                return ResourceManager.GetString("Op_Invalid_UnknownEvictionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a supported numeric type..
        /// </summary>
        internal static string Op_Invalid_UnsupportedNumericType {
            get {
                return ResourceManager.GetString("Op_Invalid_UnsupportedNumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing XML namespace on root element..
        /// </summary>
        internal static string Op_Invalid_XmlMissingNamespace {
            get {
                return ResourceManager.GetString("Op_Invalid_XmlMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SyncRoot property may not be used for the synchronization of concurrent collections..
        /// </summary>
        internal static string Op_NotSupported_ConcurrentSyncRoot {
            get {
                return ResourceManager.GetString("Op_NotSupported_ConcurrentSyncRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutating the dictionary through the Keys collection is not supported..
        /// </summary>
        internal static string Op_NotSupported_DictionaryKeysMutation {
            get {
                return ResourceManager.GetString("Op_NotSupported_DictionaryKeysMutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutating the dictionary through the Values collection is not supported..
        /// </summary>
        internal static string Op_NotSupported_DictionaryValuesMutation {
            get {
                return ResourceManager.GetString("Op_NotSupported_DictionaryValuesMutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fiscal year must be provided. Use {0}..
        /// </summary>
        internal static string Op_NotSupported_FiscalYearRequired {
            get {
                return ResourceManager.GetString("Op_NotSupported_FiscalYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negating the minimum value of a twos complement number is invalid..
        /// </summary>
        internal static string Overflow_Invalid_NegatingTwosComplement {
            get {
                return ResourceManager.GetString("Overflow_Invalid_NegatingTwosComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient or invalid serialized state for {0}..
        /// </summary>
        internal static string Serial_Invalid_State {
            get {
                return ResourceManager.GetString("Serial_Invalid_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEUIOU.
        /// </summary>
        internal static string Text_Character_Vowels {
            get {
                return ResourceManager.GetString("Text_Character_Vowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Text_Number_Bytes {
            get {
                return ResourceManager.GetString("Text_Number_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabytes.
        /// </summary>
        internal static string Text_Number_Exabytes {
            get {
                return ResourceManager.GetString("Text_Number_Exabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes.
        /// </summary>
        internal static string Text_Number_Gigabytes {
            get {
                return ResourceManager.GetString("Text_Number_Gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes.
        /// </summary>
        internal static string Text_Number_Kilobytes {
            get {
                return ResourceManager.GetString("Text_Number_Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        internal static string Text_Number_Megabytes {
            get {
                return ResourceManager.GetString("Text_Number_Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabytes.
        /// </summary>
        internal static string Text_Number_Petabytes {
            get {
                return ResourceManager.GetString("Text_Number_Petabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes.
        /// </summary>
        internal static string Text_Number_Terabytes {
            get {
                return ResourceManager.GetString("Text_Number_Terabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zettabytes.
        /// </summary>
        internal static string Text_Number_Zettabytes {
            get {
                return ResourceManager.GetString("Text_Number_Zettabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighth.
        /// </summary>
        internal static string Text_Ordinal_Eighth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string Text_Ordinal_Fifth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Text_Ordinal_First {
            get {
                return ResourceManager.GetString("Text_Ordinal_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string Text_Ordinal_Fourth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Text_Ordinal_Last {
            get {
                return ResourceManager.GetString("Text_Ordinal_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth.
        /// </summary>
        internal static string Text_Ordinal_Ninth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Text_Ordinal_Second {
            get {
                return ResourceManager.GetString("Text_Ordinal_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh.
        /// </summary>
        internal static string Text_Ordinal_Seventh {
            get {
                return ResourceManager.GetString("Text_Ordinal_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth.
        /// </summary>
        internal static string Text_Ordinal_Sixth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenth.
        /// </summary>
        internal static string Text_Ordinal_Tenth {
            get {
                return ResourceManager.GetString("Text_Ordinal_Tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string Text_Ordinal_Third {
            get {
                return ResourceManager.GetString("Text_Ordinal_Third", resourceCulture);
            }
        }
    }
}
