// ---------------------------------------------------------------------------------------------------------------
// <copyright file="GeneratedCodeFilters.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Internal;

/// <summary>
/// Provides supplementary checks for filtering out generated source files when Roslyn's built-in generated-code
/// detection (configured via <c>ConfigureGeneratedCodeAnalysis</c>) misses a particular file.
/// </summary>
internal static class GeneratedCodeFilters
{
    /// <summary>
    /// Returns whether the supplied syntax tree should be skipped because its filename indicates generated code.
    /// </summary>
    /// <param name="tree">The syntax tree under analysis.</param>
    /// <returns><see langword="true" /> when the filename matches a generated-code pattern; otherwise <see langword="false" />.</returns>
    public static bool IsGeneratedFileName(SyntaxTree tree)
    {
        if (tree is null) throw new ArgumentNullException(nameof(tree));

        var filePath = tree.FilePath;
        if (string.IsNullOrEmpty(filePath)) return false;

        var fileName = Path.GetFileName(filePath!);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith("AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns whether the supplied syntax tree contains the standard <c>&lt;auto-generated /&gt;</c> marker in
    /// its first few lines.
    /// </summary>
    /// <param name="tree">The syntax tree under analysis.</param>
    /// <returns><see langword="true" /> when the marker is found; otherwise <see langword="false" />.</returns>
    public static bool HasAutoGeneratedMarker(SyntaxTree tree)
    {
        if (tree is null) throw new ArgumentNullException(nameof(tree));

        SourceText text = tree.GetText();
        var linesToScan = Math.Min(text.Lines.Count, 4);
        for (var i = 0; i < linesToScan; i++)
        {
            var line = text.Lines[i].ToString();
            if (line.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return true;
            }
        }

        return false;
    }
}
