<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Bodu.Globalization.Calendar.MiddleEast.csproj" />
    <ProjectReference Include="..\..\Bodu.Globalization.Calendar.Data.Test.Common\Bodu.Globalization.Calendar.Data.Test.Common.csproj" />
  </ItemGroup>

</Project>
