// ---------------------------------------------------------------------------------------------------------------
// <copyright file="EaxModeTransformTests.KnownAnswerTests.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bodu.Security.Cryptography
{
    // Known-answer vectors — NIST SP 800-38A, Appendix F.5.1 (CTR mode, AES-128)
    // Source: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf
    //
    // EAX as implemented here is a pure CTR-based streaming cipher. The constructor performs no
    // OMAC or tag computation; the underlying keystream is generated by encrypting the counter
    // with big-endian (most-significant-byte-last) increment — identical to NIST CTR. These
    // vectors therefore apply directly to EaxModeTransform.
    //
    // This is a simplified EAX: a complete EAX implementation (RFC 5116) would add OMAC-based
    // header and ciphertext authentication. If EaxModeTransform is later upgraded to full EAX,
    // these vectors must be replaced with the EAX paper's Appendix G test cases.
    public sealed partial class EaxModeTransformTests
    {
        private static readonly byte[] EaxNistKey128
            = Convert.FromHexString("2b7e151628aed2a6abf7158809cf4f3c");

        // NIST F.5.1 initial counter block (used as the IV for EAX).
        private static readonly byte[] EaxNistIv
            = Convert.FromHexString("f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff");

        private static readonly byte[] EaxNistPlaintext
            = Convert.FromHexString(
                "6bc1bee22e409f96e93d7e117393172a" +
                "ae2d8a571e03ac9c9eb76fac45af8e51" +
                "30c81c46a35ce411e5fbc1191a0a52ef" +
                "f69f2445df4f9b17ad2b417be66c3710");

        private static IEnumerable<object[]> EaxKatVectors()
        {
            yield return new object[]
            {
                "NIST SP 800-38A F.5.1 — CTR-AES128 (EAX big-endian CTR)",
                EaxNistKey128,
                EaxNistIv,
                EaxNistPlaintext,
                Convert.FromHexString(
                    "874d6191b620e3261bef6864990db6ce" +
                    "9806f66b7970fdff8617187bb9fffdff" +
                    "5ae4df3edbd5d35e5b4f09020db03eab" +
                    "1e031dda2fbe03d1792170a0f3009cee"),
            };
        }

        [TestMethod]
        [DynamicData(nameof(EaxKatVectors), DynamicDataSourceType.Method)]
        public void Transform_WithNistVector_ShouldEncryptCorrectly(
            string description, byte[] key, byte[] iv, byte[] plaintext, byte[] expectedCiphertext)
            => AssertKatEncrypt(description, key, iv, plaintext, expectedCiphertext);

        [TestMethod]
        [DynamicData(nameof(EaxKatVectors), DynamicDataSourceType.Method)]
        public void Transform_WithNistVector_ShouldDecryptToOriginalPlaintext(
            string description, byte[] key, byte[] iv, byte[] plaintext, byte[] expectedCiphertext)
            => AssertKatDecrypt(description, key, iv, plaintext, expectedCiphertext);
    }
}