// ---------------------------------------------------------------------------------------------------------------
// <copyright file="MerkleTreeCoreTests.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Security.Cryptography;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Holds the internal <c>MerkleTreeCore</c> primitives to the published RFC 6962 vectors.
/// </summary>
/// <remarks>
/// <para>
/// The public facade validates arguments and reads resources; the core is the stateless arithmetic underneath it. A
/// guard moved into the facade could leave the core accepting something it should not, so the primitives are driven
/// here directly, through the same published values the facade's own suite pins.
/// </para>
/// <para>
/// The inputs are the eight entries of the RFC 6962 reference test suite, so a failure here is a disagreement with
/// the standard rather than with this repository.
/// </para>
/// </remarks>
[TestClass]
public sealed class MerkleTreeCoreTests
{
    /// <summary>The eight reference entries, in order. The first is the empty entry.</summary>
    private static readonly byte[][] ReferenceEntries =
    [
        [],
        [0x00],
        [0x10],
        [0x20, 0x21],
        [0x30, 0x31],
        [0x40, 0x41, 0x42, 0x43],
        [0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57],
        [0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f],
    ];

    /// <summary>
    /// Verifies that the core reproduces the published Merkle Tree Hash for entry counts zero
    /// through eight.
    /// </summary>
    /// <param name="entryCount">The number of reference entries to fold.</param>
    /// <param name="expectedRoot">The published root, lowercase hex.</param>
    [TestMethod]
    [DataRow(0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")]
    [DataRow(1, "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d")]
    [DataRow(2, "fac54203e7cc696cf0dfcb42c92a1d9dbaf70ad9e621f4bd8d98662f00e3c125")]
    [DataRow(3, "aeb6bcfe274b70a14fb067a5e5578264db0fa9b51af5e0ba159158f329e06e77")]
    [DataRow(4, "d37ee418976dd95753c1c73862b9398fa2a2cf9b4ff0fdfe8b30cd95209614b7")]
    [DataRow(5, "4e3bbb1f7b478dcfe71fb631631519a3bca12c9aefca1612bfce4c13a86264d4")]
    [DataRow(6, "76e67dadbcdf1e10e1b74ddc608abd2f98dfb16fbce75277b5232a127f2087ef")]
    [DataRow(7, "ddb89be403809e325750d3d263cd78929c2942b7942a34b77e122c9594a74c8c")]
    [DataRow(8, "5dc9da79a70659a9ad559cb701ded9a2ab9d823aad2f4960cfe370eff4604328")]
    public void Mth_ShouldReproduceRfc6962MerkleTreeHash(
        int entryCount, string expectedRoot)
    {
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;

        string actual = entryCount == 0
            ? Hex(MerkleTreeCore.HashEmpty(hasher, hashLength))
            : Hex(MerkleTreeCore.Mth(LeafHashes(hasher, hashLength, entryCount), hasher, hashLength));

        Assert.AreEqual(expectedRoot, actual);
    }

    /// <summary>
    /// Verifies that the core still applies RFC 6962's domain separation, so a one-entry tree's root
    /// is the entry's leaf hash and never its bare digest.
    /// </summary>
    [TestMethod]
    public void HashWithPrefix_ShouldDomainSeparateLeavesFromNodes()
    {
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;
        byte[] entry = [0x61, 0x62, 0x63];

        byte[] leaf = MerkleTreeCore.HashWithPrefix(hasher, hashLength, MerkleTreeFormat.LeafPrefix, entry);

        Assert.AreEqual("609f6e36d2405585188d5cfd761f407c7cc46a7d3f314c88270469dde315fcd1", Hex(leaf));
        Assert.AreNotEqual(Hex(SHA256.HashData(entry)), Hex(leaf));
        Assert.AreEqual(0x00, MerkleTreeFormat.LeafPrefix);
        Assert.AreEqual(0x01, MerkleTreeFormat.InternalNodePrefix);
        Assert.AreEqual(0x02, MerkleTreeFormat.RootPrefix);
    }

    /// <summary>
    /// Verifies that the core splits three entries 2 + 1 rather than 1 + 2, the point on which
    /// RFC 6962 differs from a naive halving.
    /// </summary>
    [TestMethod]
    public void SplitPoint_ShouldSplitAtTheLargestPowerOfTwoBelowTheCount()
    {
        Assert.AreEqual(2, MerkleTreeCore.SplitPoint(3));
        Assert.AreEqual(4, MerkleTreeCore.SplitPoint(7));
        Assert.AreEqual(4, MerkleTreeCore.SplitPoint(8));
        Assert.AreEqual(8, MerkleTreeCore.SplitPoint(9));
    }

    /// <summary>
    /// Verifies that a path generated by the core walks back to the same root, including the
    /// short path that leaf 6 of a seven-entry tree carries.
    /// </summary>
    [TestMethod]
    public void WalkToHead_ShouldRoundTripEveryLeafOfASevenEntryTree()
    {
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;

        byte[][] leaves = LeafHashes(hasher, hashLength, 7);
        byte[] root = MerkleTreeCore.Mth(leaves, hasher, hashLength);

        for (int leafIndex = 0; leafIndex < 7; leafIndex++)
        {
            List<byte[]> path = [];
            MerkleTreeCore.AppendPath(leaves, leafIndex, path, hasher, hashLength);

            byte[]? head = MerkleTreeCore.WalkToHead(
                7,
                leafIndex,
                leaves[leafIndex],
                path.Select(step => (ReadOnlyMemory<byte>)step).ToArray(),
                hasher,
                hashLength);

            Assert.IsNotNull(head, $"leaf {leafIndex} must walk to a head");
            Assert.AreEqual(Hex(root), Hex(head), $"leaf {leafIndex}");
            Assert.AreEqual(leafIndex == 6 ? 2 : 3, path.Count, $"leaf {leafIndex} path length");
        }
    }

    /// <summary>
    /// Verifies that the core rejects a structurally invalid proof by returning
    /// <see langword="null" /> rather than throwing, which is what keeps the public verifiers total.
    /// </summary>
    [TestMethod]
    public void WalkToHead_WhenProofIsInvalid_ShouldReturnNullRatherThanThrow()
    {
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;
        byte[][] leaves = LeafHashes(hasher, hashLength, 4);

        // Index at the tree size, a zero tree size, and a path longer than ceil(log2 n) all reject.
        Assert.IsNull(MerkleTreeCore.WalkToHead(4, 4, leaves[0], [], hasher, hashLength));
        Assert.IsNull(MerkleTreeCore.WalkToHead(0, 0, leaves[0], [], hasher, hashLength));
        Assert.IsNull(MerkleTreeCore.WalkToHead(
            4, 0, leaves[0], Enumerable.Repeat((ReadOnlyMemory<byte>)new byte[32], 5).ToArray(), hasher, hashLength));
    }

    /// <summary>
    /// Verifies that the block arithmetic agrees with the published behaviour, including the
    /// zero-length input having no blocks at all and the final block being short rather than padded.
    /// </summary>
    [TestMethod]
    public void BlockArithmetic_ShouldMatchPublishedBehaviour()
    {
        Assert.AreEqual(0L, MerkleTreeCore.BlockCount(0, 4), "a zero-length input has no blocks, not one empty one");
        Assert.AreEqual(1L, MerkleTreeCore.BlockCount(1, 4));
        Assert.AreEqual(9L, MerkleTreeCore.BlockCount(33, 4));

        Assert.AreEqual(4, MerkleTreeCore.BlockLength(33, 0, 4));
        Assert.AreEqual(1, MerkleTreeCore.BlockLength(33, 8, 4), "the final block is short, never padded");
        Assert.AreEqual(0, MerkleTreeCore.BlockLength(33, 9, 4));

        // 64-bit arithmetic: a one-mebibyte block size passes int.MaxValue at 2048 blocks.
        Assert.AreEqual(2_147_483_648L, MerkleTreeCore.BlockOffset(2048, 1024 * 1024));
    }

    /// <summary>
    /// Returns the leaf hashes of the first <paramref name="count" /> reference entries.
    /// </summary>
    /// <param name="hasher">The algorithm to hash with.</param>
    /// <param name="hashLength">The algorithm's digest length, in bytes.</param>
    /// <param name="count">The number of entries to hash.</param>
    /// <returns>The leaf hashes, in order.</returns>
    private static byte[][] LeafHashes(HashAlgorithm hasher, int hashLength, int count)
    {
        byte[][] leaves = new byte[count][];
        for (int index = 0; index < count; index++)
            leaves[index] = MerkleTreeCore.HashWithPrefix(
                hasher, hashLength, MerkleTreeFormat.LeafPrefix, ReferenceEntries[index]);

        return leaves;
    }

    /// <summary>Converts a hash to the lowercase hex used throughout the published vectors.</summary>
    /// <param name="value">The bytes to convert.</param>
    /// <returns>The lowercase hex encoding.</returns>
    private static string Hex(ReadOnlySpan<byte> value) => Convert.ToHexString(value).ToLowerInvariant();

    /// <summary>
    /// Verifies that the parallel stream loop hands out exactly the leaf sequence and byte count the sequential loop
    /// produces, at every degree of parallelism and across a batch boundary.
    /// </summary>
    /// <param name="maxDegreeOfParallelism">The degree of parallelism to request.</param>
    [TestMethod]
    [DataRow(1)]
    [DataRow(2)]
    [DataRow(-1)]
    public void ForEachLeafHashParallel_WhenComparedWithTheSequentialLoop_ShouldReportTheSameLeavesInOrder(int maxDegreeOfParallelism)
    {
        byte[] input = SeededInput(300 * 64 + 37);
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;

        List<byte[]> expected = [];
        long expectedLength = MerkleTreeCore.ForEachLeafHash(new MemoryStream(input), 64, hasher, hashLength, expected.Add, CancellationToken.None);

        List<byte[]> actual = [];
        long actualLength = MerkleTreeCore.ForEachLeafHashParallel(
            new MemoryStream(input), 64, SHA256.Create, hashLength, maxDegreeOfParallelism, actual.Add, CancellationToken.None);

        Assert.AreEqual(expectedLength, actualLength);
        Assert.AreEqual(input.Length, actualLength);
        CollectionAssert.AreEqual(expected.Select(h => Hex(h)).ToList(), actual.Select(h => Hex(h)).ToList());
    }

    /// <summary>
    /// Verifies that the asynchronous loops, sequential and parallel, hand out the same leaf sequence and byte count as
    /// the synchronous sequential loop.
    /// </summary>
    /// <param name="maxDegreeOfParallelism">The degree of parallelism to request, or zero for the sequential loop.</param>
    /// <returns>A task representing the asynchronous test.</returns>
    [TestMethod]
    [DataRow(0)]
    [DataRow(1)]
    [DataRow(-1)]
    public async Task ForEachLeafHashAsync_WhenComparedWithTheSequentialLoop_ShouldReportTheSameLeavesInOrder(int maxDegreeOfParallelism)
    {
        byte[] input = SeededInput(300 * 64 + 37);
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;

        List<byte[]> expected = [];
        long expectedLength = MerkleTreeCore.ForEachLeafHash(new MemoryStream(input), 64, hasher, hashLength, expected.Add, CancellationToken.None);

        List<byte[]> actual = [];
        long actualLength = maxDegreeOfParallelism == 0
            ? await MerkleTreeCore.ForEachLeafHashAsync(new MemoryStream(input), 64, hasher, hashLength, actual.Add, CancellationToken.None)
            : await MerkleTreeCore.ForEachLeafHashParallelAsync(
                new MemoryStream(input), 64, SHA256.Create, hashLength, maxDegreeOfParallelism, actual.Add, CancellationToken.None);

        Assert.AreEqual(expectedLength, actualLength);
        CollectionAssert.AreEqual(expected.Select(h => Hex(h)).ToList(), actual.Select(h => Hex(h)).ToList());
    }

    /// <summary>
    /// Verifies that hashing a buffer's blocks in parallel yields the same leaves as the sequential stream loop, and
    /// that an empty buffer yields no leaves.
    /// </summary>
    [TestMethod]
    public void HashLeavesParallel_WhenGivenABuffer_ShouldReportTheSameLeavesAsTheStreamLoop()
    {
        byte[] input = SeededInput(300 * 64 + 37);
        using HashAlgorithm hasher = SHA256.Create();
        int hashLength = hasher.HashSize / 8;

        List<byte[]> expected = [];
        _ = MerkleTreeCore.ForEachLeafHash(new MemoryStream(input), 64, hasher, hashLength, expected.Add, CancellationToken.None);

        byte[][] actual = MerkleTreeCore.HashLeavesParallel(input, 64, SHA256.Create, hashLength, -1, CancellationToken.None);

        CollectionAssert.AreEqual(expected.Select(h => Hex(h)).ToList(), actual.Select(h => Hex(h)).ToList());
        Assert.AreEqual(0, MerkleTreeCore.HashLeavesParallel(ReadOnlyMemory<byte>.Empty, 64, SHA256.Create, hashLength, -1, CancellationToken.None).Length);
    }

    /// <summary>
    /// Verifies that a leaf algorithm faulting inside a parallel worker surfaces its own exception rather than an
    /// <see cref="AggregateException" />.
    /// </summary>
    [TestMethod]
    public void HashLeavesParallel_WhenAWorkerFaults_ShouldSurfaceTheInnerException()
    {
        byte[] input = SeededInput(8 * 64);

        var ex = Assert.ThrowsExactly<InvalidOperationException>(() =>
        {
            _ = MerkleTreeCore.HashLeavesParallel(input, 64, static () => new FaultingAlgorithm(), 32, -1, CancellationToken.None);
        });

        Assert.AreEqual("faulted leaf", ex.Message);
    }

    /// <summary>
    /// Returns a deterministic pseudo-random input of the given length.
    /// </summary>
    /// <param name="length">The number of bytes.</param>
    /// <returns>The bytes.</returns>
    private static byte[] SeededInput(int length)
    {
        byte[] bytes = new byte[length];
        new Random(0x6962).NextBytes(bytes);
        return bytes;
    }

    /// <summary>
    /// A hash algorithm whose every computation faults, standing in for a broken leaf hasher.
    /// </summary>
    private sealed class FaultingAlgorithm : HashAlgorithm
    {
        /// <inheritdoc />
        public override void Initialize()
        {
        }

        /// <inheritdoc />
        protected override void HashCore(byte[] array, int ibStart, int cbSize) =>
            throw new InvalidOperationException("faulted leaf");

        /// <inheritdoc />
        protected override byte[] HashFinal() =>
            throw new InvalidOperationException("faulted leaf");
    }
}
