// ---------------------------------------------------------------------------------------------------------------
// <copyright file="MerkleTreeTests.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Security.Cryptography;
using Bodu.Test.Kat;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Unit tests for <see cref="MerkleTree" />.
/// </summary>
/// <remarks>
/// <para>
/// The entry-mode inputs are the eight entries the RFC 6962 reference test suite uses, so the roots asserted here
/// are expected to match any transparency-log implementation. The block-mode inputs are the first <em>L</em> bytes
/// of the sequence <c>0x00, 0x01, 0x02, …</c> at a block size of 4.
/// </para>
/// <para>
/// Every expected value was computed from RFC 6962 §2.1's definitions by an independent generator, not transcribed
/// from this implementation.
/// </para>
/// </remarks>
[TestClass]
public partial class MerkleTreeTests
{
    /// <summary>The block size used by the block-mode vectors.</summary>
    private const int VectorBlockSize = 4;

    /// <summary>
    /// The eight entries of the RFC 6962 reference test suite, in order. The first is the empty entry.
    /// </summary>
    private static readonly byte[][] ReferenceEntries =
    [
        [],
        [0x00],
        [0x10],
        [0x20, 0x21],
        [0x30, 0x31],
        [0x40, 0x41, 0x42, 0x43],
        [0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57],
        [0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f],
    ];

    /// <summary>Creates a SHA-256 tree, the configuration under which every published vector was computed.</summary>
    /// <returns>A new <see cref="MerkleTree" /> over SHA-256.</returns>
    private static MerkleTree CreateTree() => new(SHA256.Create);

    /// <summary>
    /// Returns the first <paramref name="length" /> entries of <see cref="ReferenceEntries" /> as the read-only
    /// memory list the entry-mode surface accepts.
    /// </summary>
    /// <param name="length">The number of entries to take.</param>
    /// <returns>The entry list.</returns>
    private static IReadOnlyList<ReadOnlyMemory<byte>> TakeEntries(int length)
    {
        ReadOnlyMemory<byte>[] entries = new ReadOnlyMemory<byte>[length];
        for (int index = 0; index < length; index++)
            entries[index] = ReferenceEntries[index];

        return entries;
    }

    /// <summary>
    /// Returns the first <paramref name="length" /> bytes of the sequence <c>0x00, 0x01, 0x02, …</c>, wrapping at
    /// 256.
    /// </summary>
    /// <param name="length">The number of bytes to generate.</param>
    /// <returns>The generated byte sequence.</returns>
    private static byte[] BlockModeInput(int length)
    {
        byte[] bytes = new byte[length];
        for (int index = 0; index < length; index++)
            bytes[index] = (byte)(index & 0xFF);

        return bytes;
    }

    /// <summary>
    /// Cuts <see cref="BlockModeInput(int)" /> into <see cref="VectorBlockSize" />-byte blocks using the tree's own
    /// block arithmetic, so the arithmetic under test is the shipped one.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    /// <returns>The blocks, in order.</returns>
    private static IReadOnlyList<ReadOnlyMemory<byte>> BlockModeEntries(int length)
    {
        byte[] input = BlockModeInput(length);
        long count = MerkleTree.BlockCount(length, VectorBlockSize);

        ReadOnlyMemory<byte>[] blocks = new ReadOnlyMemory<byte>[count];
        for (long index = 0; index < count; index++)
        {
            blocks[index] = input.AsMemory(
                (int)MerkleTree.BlockOffset(index, VectorBlockSize),
                MerkleTree.BlockLength(length, index, VectorBlockSize));
        }

        return blocks;
    }

    /// <summary>Converts a hash to the lowercase hex used throughout the published vectors.</summary>
    /// <param name="value">The bytes to convert.</param>
    /// <returns>The lowercase hex encoding.</returns>
    private static string Hex(ReadOnlySpan<byte> value) => Convert.ToHexString(value).ToLowerInvariant();

    /// <summary>
    /// Gets the RFC 6962 entry-mode roots for entry counts 0 through 8 (requirements appendix A).
    /// </summary>
    public static IEnumerable<object[]> EntryModeRoots =>
    [
        [new ValidKat<int, string>("A entries=0", 0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")],
        [new ValidKat<int, string>("A entries=1", 1, "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d")],
        [new ValidKat<int, string>("A entries=2", 2, "fac54203e7cc696cf0dfcb42c92a1d9dbaf70ad9e621f4bd8d98662f00e3c125")],
        [new ValidKat<int, string>("A entries=3", 3, "aeb6bcfe274b70a14fb067a5e5578264db0fa9b51af5e0ba159158f329e06e77")],
        [new ValidKat<int, string>("A entries=4", 4, "d37ee418976dd95753c1c73862b9398fa2a2cf9b4ff0fdfe8b30cd95209614b7")],
        [new ValidKat<int, string>("A entries=5", 5, "4e3bbb1f7b478dcfe71fb631631519a3bca12c9aefca1612bfce4c13a86264d4")],
        [new ValidKat<int, string>("A entries=6", 6, "76e67dadbcdf1e10e1b74ddc608abd2f98dfb16fbce75277b5232a127f2087ef")],
        [new ValidKat<int, string>("A entries=7", 7, "ddb89be403809e325750d3d263cd78929c2942b7942a34b77e122c9594a74c8c")],
        [new ValidKat<int, string>("A entries=8", 8, "5dc9da79a70659a9ad559cb701ded9a2ab9d823aad2f4960cfe370eff4604328")],
    ];

    /// <summary>
    /// Gets the RFC 6962 block-mode roots at a block size of 4 (requirements appendix B).
    /// </summary>
    public static IEnumerable<object[]> BlockModeRoots =>
    [
        [new ValidKat<int, string>("B length=0", 0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")],
        [new ValidKat<int, string>("B length=1", 1, "96a296d224f285c67bee93c30f8a309157f0daa35dc5b87e410b78630a09cfc7")],
        [new ValidKat<int, string>("B length=4", 4, "a498efa8d0759e7b704095853db9bc1ef8cf65af37bed9d006c4b2917e695061")],
        [new ValidKat<int, string>("B length=5", 5, "a568e8449ea491fdb4a261e3e75d2a8562b7c66887ad89cd590df667eae30146")],
        [new ValidKat<int, string>("B length=8", 8, "000134e55e67854e1a3d28a78c6392b02623c2505580b0f9d571e0b4d3e2257f")],
        [new ValidKat<int, string>("B length=9", 9, "7d0d764930953cf7bda9cfaf927efb27e0c74b7601ea8e5ef87a1b03e7ac85c2")],
        [new ValidKat<int, string>("B length=12", 12, "3b469d6b2565374bf3f9d7405627a59e3dba9a3207f3c52b06db08e7190e1f14")],
        [new ValidKat<int, string>("B length=13", 13, "311ae2a2c5f7b96b71ad76148419619697a19c5d61f894a9dcc254c8363341e9")],
        [new ValidKat<int, string>("B length=16", 16, "516c43cb9e4f82fe70437703f0a41649c5fd963ba5f4be8b736dca20bae05bdd")],
        [new ValidKat<int, string>("B length=17", 17, "557a6fa29055fbfb4466b8068539aa5e6c9b2c1500624cab414631484e5bc551")],
        [new ValidKat<int, string>("B length=20", 20, "0a30d6148fc3d1c38bc90624148f2021ee9d4a72d2fdcb53dcba91e46237f6d0")],
        [new ValidKat<int, string>("B length=28", 28, "6a648b436a7ba0966d61d03e31033b8e6a5d69dcbf73777afb508ab1f0260a63")],
        [new ValidKat<int, string>("B length=32", 32, "4caa28905e0e6530cced23948c7f3a575f09c618644c66e36f8bd5bc19b2f11c")],
        [new ValidKat<int, string>("B length=33", 33, "31dce6ff9c5ac1336d203f99ea214a31eaba3429a3316fdc7eb7dfa1e787e9ec")],
    ];

    /// <summary>
    /// Gets the length-bound roots over the block-mode inputs (requirements appendix C).
    /// </summary>
    public static IEnumerable<object[]> BoundRoots =>
    [
        [new ValidKat<int, string>("C length=1", 1, "ee8acb9cb20eaf4b807ef586e552774d803cc3dd837bf26e9f509500cc2604bd")],
        [new ValidKat<int, string>("C length=4", 4, "c39c67e10308a8c59d1ed505e3d5effdfb95919fcf0f27e43b55b943ed8dc583")],
        [new ValidKat<int, string>("C length=5", 5, "ac3f0c480d6809a0c217a999ddb73789d1995e1b655b88027b6b9b20090cb752")],
        [new ValidKat<int, string>("C length=8", 8, "c5f132c32e9477705f6d0fa233deaebb338dc1da33b4edf94a9077e0a90e7941")],
        [new ValidKat<int, string>("C length=9", 9, "0114742dacb57b039e052a558685ad805108cc03fdeb82af5917bb07cd2545e7")],
        [new ValidKat<int, string>("C length=12", 12, "29f46d734672b404873bd2548b2ab1cf66cf22c5c412fb150331b344cd50332a")],
        [new ValidKat<int, string>("C length=13", 13, "571c6e2f33df94b2fb8d993f3b4da89a4d1e1570b44bf50875a362e57517d8bb")],
        [new ValidKat<int, string>("C length=16", 16, "f5ed505e0cb1f0f1cb6909f10211fefe06a7d976b18f9c38e9bdf497802f2b04")],
        [new ValidKat<int, string>("C length=17", 17, "ac4de219663afebd46a0c39de495cc49abec2c321a1db9ca549c3a5bb2a0eee4")],
        [new ValidKat<int, string>("C length=20", 20, "8418fd8ce3f3e1895644537a10c7b12a048bb541789045420bdd6ece2251ee0a")],
        [new ValidKat<int, string>("C length=28", 28, "0847c78802618221fc7da3a3b64bcab9524558efe3115e6a7cb807185b008d1e")],
        [new ValidKat<int, string>("C length=32", 32, "9fe7554b5c4798e70be59bf08e95550caca6e3d1032065e14ec4879d0438771e")],
        [new ValidKat<int, string>("C length=33", 33, "e269c9dcf6ca5202ed027971c97e81db585373aeff5897c629a07b4d16f04951")],
    ];
}
