// ---------------------------------------------------------------------------------------------------------------
// <copyright file="MerkleTreeHashTests.Rfc6962Divergence.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Security.Cryptography;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Pins the relationship between <see cref="MerkleTreeHash" />'s tree shape and RFC 6962's, so the two cannot
/// silently converge or diverge further.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="MerkleTreeHash" /> adopts RFC 6962's <em>domain separation</em> — a leaf is <c>H(0x00 || block)</c>
/// and an internal node <c>H(0x01 || children)</c> — but not its <em>tree</em>. RFC 6962 splits a tree of
/// <em>n</em> leaves at <c>k</c>, the largest power of two strictly below <em>n</em>, and promotes a lone subtree
/// root unchanged. <see cref="MerkleTreeHash" /> reduces level by level and re-hashes a lone leftover child as a
/// one-child node <c>H(0x01 || child)</c>. The two therefore agree exactly when the leaf count is a power of two
/// and differ otherwise.
/// </para>
/// <para>
/// Every expected value below was computed independently from RFC 6962 §2.1's definitions rather than transcribed
/// from this implementation. The inputs are the first <em>L</em> bytes of the sequence <c>0x00, 0x01, 0x02, …</c>
/// at a block size of 4 and a fan-out of 2 — the configuration under which the two shapes are directly comparable.
/// </para>
/// <para>
/// These tests exist to document the divergence, not to condemn it: a level-by-level reduction is a perfectly good
/// commitment, and the roots this type produces today are frozen. A conforming RFC 6962 tree is a separate type.
/// </para>
/// </remarks>
public partial class MerkleTreeHashTests
{
    /// <summary>The block size at which the two tree shapes are compared.</summary>
    private const int DivergenceBlockSize = 4;

    /// <summary>The fan-out at which the two tree shapes are compared.</summary>
    private const int DivergenceFanOut = 2;

    /// <summary>
    /// Returns the first <paramref name="length" /> bytes of the sequence <c>0x00, 0x01, 0x02, …</c>, wrapping at
    /// 256.
    /// </summary>
    /// <param name="length">The number of bytes to generate.</param>
    /// <returns>The generated byte sequence.</returns>
    private static byte[] DivergenceInput(int length)
    {
        byte[] bytes = new byte[length];
        for (int i = 0; i < length; i++)
            bytes[i] = (byte)(i & 0xFF);

        return bytes;
    }

    /// <summary>
    /// Computes the root <see cref="MerkleTreeHash" /> produces over
    /// <see cref="DivergenceInput(int)" /> at the comparison configuration.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    /// <returns>The root hash, lowercase hex-encoded.</returns>
    private static string DivergenceRoot(int length)
    {
        using var hasher = new MerkleTreeHash(SHA256.Create, DivergenceBlockSize, DivergenceFanOut);
        return Convert.ToHexString(hasher.ComputeHash(DivergenceInput(length))).ToLowerInvariant();
    }

    /// <summary>
    /// Verifies that for a power-of-two leaf count the root equals RFC 6962's Merkle Tree Hash, because the
    /// level-by-level reduction and RFC 6962's recursive split describe the same tree when no level has a lone
    /// leftover child.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    /// <param name="expectedLeafCount">The number of leaves those bytes produce.</param>
    /// <param name="expectedRoot">RFC 6962's Merkle Tree Hash over the same leaves, lowercase hex.</param>
    [TestMethod]
    [TestCategory("Regression")]
    [DataRow(1, 1, "96a296d224f285c67bee93c30f8a309157f0daa35dc5b87e410b78630a09cfc7")]
    [DataRow(4, 1, "a498efa8d0759e7b704095853db9bc1ef8cf65af37bed9d006c4b2917e695061")]
    [DataRow(5, 2, "a568e8449ea491fdb4a261e3e75d2a8562b7c66887ad89cd590df667eae30146")]
    [DataRow(8, 2, "000134e55e67854e1a3d28a78c6392b02623c2505580b0f9d571e0b4d3e2257f")]
    [DataRow(13, 4, "311ae2a2c5f7b96b71ad76148419619697a19c5d61f894a9dcc254c8363341e9")]
    [DataRow(16, 4, "516c43cb9e4f82fe70437703f0a41649c5fd963ba5f4be8b736dca20bae05bdd")]
    [DataRow(32, 8, "4caa28905e0e6530cced23948c7f3a575f09c618644c66e36f8bd5bc19b2f11c")]
    public void ComputeHash_WhenLeafCountIsAPowerOfTwo_ShouldMatchRfc6962MerkleTreeHash(
        int length, int expectedLeafCount, string expectedRoot)
    {
        Assert.AreEqual(
            expectedLeafCount,
            (length + DivergenceBlockSize - 1) / DivergenceBlockSize,
            "the row's stated leaf count must match the block arithmetic");

        Assert.AreEqual(expectedRoot, DivergenceRoot(length));
    }

    /// <summary>
    /// Verifies that for a non-power-of-two leaf count the root differs from RFC 6962's Merkle Tree Hash, and
    /// equals the level-by-level value this type has always produced. The difference is the lone leftover child:
    /// RFC 6962 promotes it unchanged where this type re-hashes it as a one-child node.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    /// <param name="expectedLeafCount">The number of leaves those bytes produce.</param>
    /// <param name="rfc6962Root">RFC 6962's Merkle Tree Hash over the same leaves, lowercase hex.</param>
    /// <param name="expectedRoot">The root this type produces, lowercase hex.</param>
    [TestMethod]
    [TestCategory("Regression")]
    [DataRow(9, 3, "7d0d764930953cf7bda9cfaf927efb27e0c74b7601ea8e5ef87a1b03e7ac85c2", "30cc4e02e75df443946d7e314cdba6d945e15dfe80e1df0afa95578e4bb134ba")]
    [DataRow(12, 3, "3b469d6b2565374bf3f9d7405627a59e3dba9a3207f3c52b06db08e7190e1f14", "a8ff2177cdb8f89bb760ae8e20ca64ae92db7a5a84acf125ac8fca371ea2b38f")]
    [DataRow(17, 5, "557a6fa29055fbfb4466b8068539aa5e6c9b2c1500624cab414631484e5bc551", "30b62b0e0ec135a451f000364fd08edd8a38c89772d026f751f707ac3673e0a0")]
    [DataRow(20, 5, "0a30d6148fc3d1c38bc90624148f2021ee9d4a72d2fdcb53dcba91e46237f6d0", "0892a38103267a72d521a4afac95671df51e8901e625cd26664ffb5c24ecc993")]
    [DataRow(28, 7, "6a648b436a7ba0966d61d03e31033b8e6a5d69dcbf73777afb508ab1f0260a63", "f9bea195c90f6ee0e71ffca1af2226c7cae2b55e1cee0e3c580ebf8c6c0b2db3")]
    [DataRow(33, 9, "31dce6ff9c5ac1336d203f99ea214a31eaba3429a3316fdc7eb7dfa1e787e9ec", "7b29c4db9bf5e233839abffdf1b142eeff5a0e4d07bf64f2be83df6d06230e3d")]
    public void ComputeHash_WhenLeafCountIsNotAPowerOfTwo_ShouldDifferFromRfc6962MerkleTreeHash(
        int length, int expectedLeafCount, string rfc6962Root, string expectedRoot)
    {
        Assert.AreEqual(
            expectedLeafCount,
            (length + DivergenceBlockSize - 1) / DivergenceBlockSize,
            "the row's stated leaf count must match the block arithmetic");

        string actual = DivergenceRoot(length);

        Assert.AreEqual(expectedRoot, actual);
        Assert.AreNotEqual(rfc6962Root, actual, "this type is not expected to produce RFC 6962's tree shape");
    }

    /// <summary>
    /// Verifies that a zero-length input throws where RFC 6962 instead defines <c>MTH({}) = H()</c>, the hash of
    /// the empty string. This is the seventh and last row on which the two shapes disagree.
    /// </summary>
    /// <remarks>
    /// The exception is the documented behaviour of this type and is deliberately left in place; a conforming tree
    /// returns the empty-string digest rather than throwing.
    /// </remarks>
    [TestMethod]
    [TestCategory("Regression")]
    public void ComputeHash_WhenInputIsEmpty_ShouldThrowWhereRfc6962DefinesTheEmptyTreeRoot()
    {
        using var hasher = new MerkleTreeHash(SHA256.Create, DivergenceBlockSize, DivergenceFanOut);

        _ = Assert.ThrowsExactly<InvalidOperationException>(() =>
        {
            _ = hasher.ComputeHash([]);
        });

        Assert.AreEqual(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            Convert.ToHexString(SHA256.HashData([])).ToLowerInvariant(),
            "RFC 6962's empty-tree root is the empty string's digest");
    }
}
