// ---------------------------------------------------------------------------------------------------------------
// <copyright file="Rfc6962MerkleTreeTests.ComputeBlocked.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Buffers.Binary;
using System.Security.Cryptography;
using Bodu.Test.Kat;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Tests for <see cref="Rfc6962MerkleTree.ComputeBlocked(Stream, int, CancellationToken)" />,
/// <see cref="Rfc6962MerkleTree.ComputeBlocked(ReadOnlySpan{byte}, int)" /> and
/// <see cref="Rfc6962MerkleTree.ComputeRootOfBlocks(Stream, int, CancellationToken)" />.
/// </summary>
public partial class Rfc6962MerkleTreeTests
{
    /// <summary>One mebibyte — the leaf size the FallbackPlan repository format fixes.</summary>
    internal const int OneMebibyteBlock = 1024 * 1024;

    /// <summary>
    /// Gets the length-bound roots over one-mebibyte leaves of the counter stream, as the FallbackPlan conformance
    /// vectors publish them.
    /// </summary>
    public static IEnumerable<object[]> WholePreimageBoundRoots =>
    [
        [new ValidKat<int, string>("under_one_leaf", 3, "ee5eba24c6868d02bb0cbb3619123faee1107c7cbff42e06946c6eb430dc2a42")],
        [new ValidKat<int, string>("exactly_one_leaf", 1048576, "2aac375a10d9dfb3452a8f04684100201de9f7caa905586172eda3c52846e94e")],
        [new ValidKat<int, string>("one_byte_over_one_leaf", 1048577, "3dc8efd3b9b74e38c9be8f37a83c95dcf50768a89b3592f4244f5679267054c2")],
        [new ValidKat<int, string>("two_leaves_and_a_tail", 2109497, "fd5a338e6306896800ea3edaa0d69e20e6b5364ce6566b86300c60eaf18cf649")],
    ];

    /// <summary>
    /// Returns the first <paramref name="length" /> bytes of the concatenation of
    /// <c>SHA-256(BE64(counter))</c> from counter zero — the stream the FallbackPlan vectors are taken over.
    /// </summary>
    /// <param name="length">The number of bytes to generate.</param>
    /// <returns>The generated byte sequence.</returns>
    internal static byte[] CounterStream(int length)
    {
        byte[] bytes = new byte[length];
        Span<byte> input = stackalloc byte[sizeof(ulong)];
        Span<byte> block = stackalloc byte[SHA256.HashSizeInBytes];

        ulong counter = 0;
        int written = 0;
        while (written < length)
        {
            BinaryPrimitives.WriteUInt64BigEndian(input, counter++);
            SHA256.HashData(input, block);

            int take = Math.Min(block.Length, length - written);
            block[..take].CopyTo(bytes.AsSpan(written));
            written += take;
        }

        return bytes;
    }

    /// <summary>
    /// Verifies that the streamed block-mode root reproduces the published Merkle Tree Hash, including a short final
    /// block and a zero-length stream.
    /// </summary>
    /// <param name="kat">The input length and its expected root.</param>
    [TestMethod]
    [DynamicData(nameof(BlockModeRoots), DynamicDataDisplayName = nameof(KatDisplayName.GetDisplayName), DynamicDataDisplayNameDeclaringType = typeof(KatDisplayName))]
    [TestCategory("Regression")]
    public void ComputeBlocked_WhenReadingAStream_ShouldReproduceRfc6962MerkleTreeHash(ValidKat<int, string> kat)
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream(BlockModeInput(kat.Input));

        MerkleBlockComputation computation = tree.ComputeBlocked(stream, VectorBlockSize);

        Assert.AreEqual(kat.Expected, Hex(computation.Root));
        Assert.AreEqual(kat.Input, computation.InputLength);
        Assert.AreEqual(VectorBlockSize, computation.BlockSize);
        Assert.AreEqual(MerkleBlocks.BlockCount(kat.Input, VectorBlockSize), computation.LeafHashes.Count);
    }

    /// <summary>
    /// Verifies that the logarithmic-memory fold produces the same root as the leaf-retaining pass for every leaf
    /// count from zero to sixty-four, which is where the two constructions could most easily disagree.
    /// </summary>
    /// <remarks>
    /// The fold pushes each leaf as a one-leaf subtree and combines equal-sized neighbours, then folds the remainder
    /// right to left. That reproduces RFC 6962's shape only if every pending entry is a perfect subtree, so a
    /// disagreement at any non-power-of-two count would reveal a broken merge condition.
    /// </remarks>
    [TestMethod]
    [TestCategory("Regression")]
    public void ComputeRootOfBlocks_WhenFoldingIncrementally_ShouldAgreeWithTheLeafRetainingPass()
    {
        Rfc6962MerkleTree tree = CreateTree();

        for (int leafCount = 0; leafCount <= 64; leafCount++)
        {
            // A trailing partial block as well as exact multiples, so both tail shapes are covered.
            foreach (int tail in (int[])[0, 1])
            {
                int length = (leafCount * VectorBlockSize) + tail;
                if (leafCount == 0 && tail == 0)
                    length = 0;

                byte[] input = BlockModeInput(length);

                using var retaining = new MemoryStream(input);
                using var folding = new MemoryStream(input);

                string expected = Hex(tree.ComputeBlocked(retaining, VectorBlockSize).Root);
                string actual = Hex(tree.ComputeRootOfBlocks(folding, VectorBlockSize));

                Assert.AreEqual(expected, actual, $"length {length} ({leafCount} full blocks + {tail})");
            }
        }
    }

    /// <summary>
    /// Verifies that the incremental fold still agrees with the leaf-retaining pass at large leaf counts, either side
    /// of a power of two, where a wrong merge condition would surface as a mismatch.
    /// </summary>
    /// <param name="leafCount">The number of one-byte blocks, and so of leaves.</param>
    /// <remarks>
    /// The fold's peak memory holds one pending subtree per set bit in the leaf count, so counts such as 65 535
    /// (sixteen set bits) and 65 536 (one) exercise opposite extremes of its stack depth.
    /// </remarks>
    [TestMethod]
    [TestCategory("Regression")]
    [DataRow(1023)]
    [DataRow(1024)]
    [DataRow(1025)]
    [DataRow(65535)]
    [DataRow(65536)]
    [DataRow(65537)]
    public void ComputeRootOfBlocks_WhenLeafCountIsLarge_ShouldAgreeWithTheLeafRetainingPass(int leafCount)
    {
        Rfc6962MerkleTree tree = CreateTree();
        byte[] input = BlockModeInput(leafCount);

        using var retaining = new MemoryStream(input);
        using var folding = new MemoryStream(input);

        MerkleBlockComputation computation = tree.ComputeBlocked(retaining, blockSize: 1);

        Assert.AreEqual(leafCount, computation.LeafHashes.Count);
        Assert.AreEqual(Hex(computation.Root), Hex(tree.ComputeRootOfBlocks(folding, blockSize: 1)));
    }

    /// <summary>
    /// Verifies that the logarithmic-memory fold reproduces the published block-mode roots directly, not merely that
    /// it agrees with the other overload.
    /// </summary>
    /// <param name="kat">The input length and its expected root.</param>
    [TestMethod]
    [DynamicData(nameof(BlockModeRoots), DynamicDataDisplayName = nameof(KatDisplayName.GetDisplayName), DynamicDataDisplayNameDeclaringType = typeof(KatDisplayName))]
    [TestCategory("Regression")]
    public void ComputeRootOfBlocks_WhenReadingAStream_ShouldReproduceRfc6962MerkleTreeHash(ValidKat<int, string> kat)
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream(BlockModeInput(kat.Input));

        Assert.AreEqual(kat.Expected, Hex(tree.ComputeRootOfBlocks(stream, VectorBlockSize)));
    }

    /// <summary>
    /// Verifies that a stream delivering its bytes in small, uneven pieces yields the same root as one delivering
    /// them all at once, so a short read is never mistaken for the end of the stream.
    /// </summary>
    /// <param name="maxBytesPerRead">The most bytes the stream will return from a single read.</param>
    [TestMethod]
    [DataRow(1)]
    [DataRow(2)]
    [DataRow(3)]
    [DataRow(5)]
    [DataRow(7)]
    public void ComputeBlocked_WhenStreamReturnsShortReads_ShouldProduceTheSameRoot(int maxBytesPerRead)
    {
        Rfc6962MerkleTree tree = CreateTree();
        byte[] input = BlockModeInput(33);

        using var whole = new MemoryStream(input);
        string expected = Hex(tree.ComputeBlocked(whole, VectorBlockSize).Root);

        using var throttled = new ThrottledStream(input, maxBytesPerRead);
        MerkleBlockComputation computation = tree.ComputeBlocked(throttled, VectorBlockSize);

        Assert.AreEqual("31dce6ff9c5ac1336d203f99ea214a31eaba3429a3316fdc7eb7dfa1e787e9ec", expected);
        Assert.AreEqual(expected, Hex(computation.Root));
        Assert.AreEqual(33, computation.InputLength);
        Assert.AreEqual(9, computation.LeafHashes.Count);
    }

    /// <summary>
    /// Verifies that the folding overload is equally tolerant of short reads.
    /// </summary>
    [TestMethod]
    public void ComputeRootOfBlocks_WhenStreamReturnsShortReads_ShouldProduceTheSameRoot()
    {
        Rfc6962MerkleTree tree = CreateTree();

        using var throttled = new ThrottledStream(BlockModeInput(33), maxBytesPerRead: 3);

        Assert.AreEqual(
            "31dce6ff9c5ac1336d203f99ea214a31eaba3429a3316fdc7eb7dfa1e787e9ec",
            Hex(tree.ComputeRootOfBlocks(throttled, VectorBlockSize)));
    }

    /// <summary>
    /// Verifies that the span overload agrees with the stream overload over the same bytes.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    [TestMethod]
    [DataRow(0)]
    [DataRow(1)]
    [DataRow(9)]
    [DataRow(17)]
    [DataRow(33)]
    public void ComputeBlocked_WhenGivenASpan_ShouldAgreeWithTheStreamOverload(int length)
    {
        Rfc6962MerkleTree tree = CreateTree();
        byte[] input = BlockModeInput(length);

        using var stream = new MemoryStream(input);

        Assert.AreEqual(
            Hex(tree.ComputeBlocked(stream, VectorBlockSize).Root),
            Hex(tree.ComputeBlocked(input.AsSpan(), VectorBlockSize).Root));
    }

    /// <summary>
    /// Verifies that binding the streamed input's length reproduces the published bound roots over one-mebibyte
    /// leaves, exercising the block arithmetic at the leaf size a real consumer uses.
    /// </summary>
    /// <param name="kat">The preimage length and its expected bound root.</param>
    [TestMethod]
    [DynamicData(nameof(WholePreimageBoundRoots), DynamicDataDisplayName = nameof(KatDisplayName.GetDisplayName), DynamicDataDisplayNameDeclaringType = typeof(KatDisplayName))]
    [TestCategory("Regression")]
    public void ComputeBlocked_WhenBlockSizeIsOneMebibyte_ShouldReproducePublishedBoundRoots(ValidKat<int, string> kat)
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream(CounterStream(kat.Input));

        MerkleBlockComputation computation = tree.ComputeBlocked(stream, OneMebibyteBlock);

        Assert.AreEqual(kat.Input, computation.InputLength);
        Assert.AreEqual(kat.Expected, Hex(tree.BindRoot(computation.Root, computation.InputLength)));
    }

    /// <summary>
    /// Verifies that a zero-length stream produces zero leaves and the empty tree's root, rather than one empty leaf.
    /// </summary>
    [TestMethod]
    public void ComputeBlocked_WhenStreamIsEmpty_ShouldProduceNoLeavesAndTheEmptyTreeRoot()
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream([]);

        MerkleBlockComputation computation = tree.ComputeBlocked(stream, VectorBlockSize);

        Assert.AreEqual(0, computation.LeafHashes.Count);
        Assert.AreEqual(0L, computation.InputLength);
        Assert.AreEqual(Hex(SHA256.HashData([])), Hex(computation.Root));
        Assert.AreNotEqual(Hex(tree.HashLeaf([])), Hex(computation.Root));
    }

    /// <summary>
    /// Verifies that the retained leaf hashes are the leaf hashes of the blocks, in block order.
    /// </summary>
    [TestMethod]
    public void ComputeBlocked_WhenInputHasSeveralBlocks_ShouldRetainEachBlocksLeafHashInOrder()
    {
        Rfc6962MerkleTree tree = CreateTree();
        byte[] input = BlockModeInput(9);
        using var stream = new MemoryStream(input);

        MerkleBlockComputation computation = tree.ComputeBlocked(stream, VectorBlockSize);

        Assert.AreEqual(3, computation.LeafHashes.Count);
        Assert.AreEqual(Hex(tree.HashLeaf(input.AsSpan(0, 4))), Hex(computation.LeafHashes[0]));
        Assert.AreEqual(Hex(tree.HashLeaf(input.AsSpan(4, 4))), Hex(computation.LeafHashes[1]));
        Assert.AreEqual(Hex(tree.HashLeaf(input.AsSpan(8, 1))), Hex(computation.LeafHashes[2]));
    }

    /// <summary>
    /// Verifies that the retained leaf hashes fold to the same root through
    /// <see cref="Rfc6962MerkleTree.ComputeRootOfLeafHashes(IReadOnlyList{byte[]})" />, so a caller can reuse them
    /// without recomputing.
    /// </summary>
    /// <param name="length">The number of input bytes.</param>
    [TestMethod]
    [DataRow(1)]
    [DataRow(12)]
    [DataRow(20)]
    [DataRow(28)]
    public void ComputeBlocked_WhenRetainedLeafHashesAreRefolded_ShouldProduceTheSameRoot(int length)
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream(BlockModeInput(length));

        MerkleBlockComputation computation = tree.ComputeBlocked(stream, VectorBlockSize);

        Assert.AreEqual(
            Hex(computation.Root),
            Hex(tree.ComputeRootOfLeafHashes(computation.LeafHashes)));
    }

    /// <summary>
    /// Verifies that a <see langword="null" /> stream is rejected with <see cref="ArgumentNullException" />.
    /// </summary>
    [TestMethod]
    public void ComputeBlocked_WhenStreamIsNull_ShouldThrowArgumentNullException()
    {
        Rfc6962MerkleTree tree = CreateTree();

        _ = Assert.ThrowsExactly<ArgumentNullException>(() =>
        {
            _ = tree.ComputeBlocked((Stream)null!, 4);
        });
    }

    /// <summary>
    /// Verifies that a non-positive block size is rejected with <see cref="ArgumentOutOfRangeException" />.
    /// </summary>
    /// <param name="blockSize">The invalid block size.</param>
    [TestMethod]
    [DataRow(0)]
    [DataRow(-1)]
    public void ComputeBlocked_WhenBlockSizeIsNotPositive_ShouldThrowArgumentOutOfRangeException(int blockSize)
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream([1, 2, 3]);

        var ex = Assert.ThrowsExactly<ArgumentOutOfRangeException>(() =>
        {
            _ = tree.ComputeBlocked(stream, blockSize);
        });

        Assert.AreEqual("blockSize", ex.ParamName);
    }

    /// <summary>
    /// Verifies that a cancelled token stops the read with <see cref="OperationCanceledException" />.
    /// </summary>
    [TestMethod]
    public void ComputeBlocked_WhenCancellationIsRequested_ShouldThrowOperationCanceledException()
    {
        Rfc6962MerkleTree tree = CreateTree();
        using var stream = new MemoryStream(BlockModeInput(64));
        using var cts = new CancellationTokenSource();
        cts.Cancel();

        _ = Assert.ThrowsExactly<OperationCanceledException>(() =>
        {
            _ = tree.ComputeBlocked(stream, VectorBlockSize, cts.Token);
        });
    }

    /// <summary>
    /// A read-only stream that never returns more than a fixed number of bytes per read, so a caller that treats a
    /// short read as the end of the stream is caught.
    /// </summary>
    private sealed class ThrottledStream : Stream
    {
        /// <summary>The bytes to serve.</summary>
        private readonly byte[] _bytes;

        /// <summary>The most bytes any single read returns.</summary>
        private readonly int _maxBytesPerRead;

        /// <summary>The number of bytes already served.</summary>
        private int _position;

        /// <summary>
        /// Initializes a new instance of the <see cref="ThrottledStream" /> class.
        /// </summary>
        /// <param name="bytes">The bytes to serve.</param>
        /// <param name="maxBytesPerRead">The most bytes any single read returns.</param>
        internal ThrottledStream(byte[] bytes, int maxBytesPerRead)
        {
            _bytes = bytes;
            _maxBytesPerRead = maxBytesPerRead;
        }

        /// <inheritdoc />
        public override bool CanRead => true;

        /// <inheritdoc />
        public override bool CanSeek => false;

        /// <inheritdoc />
        public override bool CanWrite => false;

        /// <inheritdoc />
        public override long Length => _bytes.Length;

        /// <inheritdoc />
        public override long Position
        {
            get => _position;
            set => throw new NotSupportedException();
        }

        /// <inheritdoc />
        public override int Read(byte[] buffer, int offset, int count)
        {
            int available = Math.Min(Math.Min(count, _maxBytesPerRead), _bytes.Length - _position);
            if (available <= 0)
                return 0;

            Buffer.BlockCopy(_bytes, _position, buffer, offset, available);
            _position += available;
            return available;
        }

        /// <inheritdoc />
        public override void Flush()
        {
            // Nothing to flush: the stream is read-only.
        }

        /// <inheritdoc />
        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();

        /// <inheritdoc />
        public override void SetLength(long value) => throw new NotSupportedException();

        /// <inheritdoc />
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }

    /// <summary>
    /// Verifies that a supplied <see cref="MerkleTreeDiagnostics" /> receives a trace that validates on its own, holds
    /// one leaf per block, and ends at the root the call returned — for every leaf count up to sixteen, so promoted
    /// leftovers are covered as well as full pairs.
    /// </summary>
    [TestMethod]
    public void ComputeRootOfBlocks_WhenDiagnosticsAreSupplied_ShouldRecordAValidatingTraceEndingAtTheRoot()
    {
        Rfc6962MerkleTree tree = CreateTree();

        for (int leafCount = 0; leafCount <= 16; leafCount++)
        {
            using var source = new MemoryStream(BlockModeInput(leafCount * VectorBlockSize));
            var diagnostics = new MerkleTreeDiagnostics();

            byte[] root = tree.ComputeRootOfBlocks(source, VectorBlockSize, diagnostics);

            Assert.IsTrue(
                diagnostics.Validate(SHA256.Create, out IReadOnlyList<string> errors),
                string.Join("; ", errors));
            Assert.AreEqual(leafCount, diagnostics.GetLevel(0).Count, $"leaf count {leafCount}");

            if (leafCount == 0)
                Assert.IsNull(diagnostics.Root, "an empty tree records no node");
            else
                Assert.AreEqual(Hex(root), Hex(diagnostics.Root!.Hash), $"leaf count {leafCount}");
        }
    }
}
