// ---------------------------------------------------------------------------------------------------------------
// <copyright file="ThreeFishCipherTests.ThreeFishCipherTestVariant.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

namespace Bodu.Security.Cryptography;

/// <summary>
/// Identifies the Threefish key/tweak initialisation patterns exercised by
/// <see cref="ThreeFishCipherTests{TTest, TCipher}" />: an all-zero key/tweak pair and a
/// deterministic non-zero pair generated by the test harness.
/// </summary>
public enum ThreeFishCipherTestVariant
{
    ZeroedKeyAndTweak,
    DefaultKeyAndTweak
}
