// ---------------------------------------------------------------------------------------------------------------
// <copyright file="TweakableBlockCipherVariant.cs" company="Bodu Pty. Ltd.">
//     Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

namespace Bodu.Security.Cryptography;

/// <summary>
/// Identifies the canonical (key, tweak) initialisation patterns exercised by tweakable block-cipher families (Serpent
/// and Threefish) — an all-zero pair, and a deterministic non-zero pair generated by the test harness. Used as the
/// <c>TVariant</c> type parameter of <see cref="BlockCipherTests{TTest, TCipher, TVariant}" /> and as the dispatch key
/// on each family's <c>&lt;Cipher&gt;KnownAnswers.For(variant)</c> accessor.
/// </summary>
/// <remarks>
/// Replaces the family-specific <c>SerpentCipherTestVariant</c> and <c>ThreeFishCipherTestVariant</c> enums that
/// previously declared the same two values verbatim. Non-tweakable cipher engines (for example <c>Serpent128Cipher</c>)
/// ignore the tweak component, so the same enum can drive both tweakable and non-tweakable concrete test classes within
/// the same family.
/// </remarks>
public enum TweakableBlockCipherVariant
{
    /// <summary>
    /// All-zero key and all-zero tweak (non-tweakable engines ignore the tweak).
    /// </summary>
    ZeroedKeyAndTweak,

    /// <summary>
    /// A deterministic non-zero key and tweak generated as incremental byte sequences.
    /// </summary>
    DefaultKeyAndTweak,
}
