// ---------------------------------------------------------------------------------------------------------------
// <copyright file="BencodeTests.RoundTrip.cs" company="Bodu Pty. Ltd.">
//     Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using Bodu.Test;

namespace Bodu.Text.Bencode;

public sealed partial class BencodeTests
{

    /// <summary>
    /// Verifies that for every positive KAT vector, decoding the canonical bytes and re-encoding the result
    /// reproduces the original bytes exactly.
    /// </summary>
    /// <param name="vector">A KAT vector sourced from
    /// <see cref="BencodeKnownAnswerVectors.AllPositiveVectors" />.</param>
    [TestMethod]
    [TestCategory(TestCategories.Regression)]
    [DynamicData(nameof(BencodeKnownAnswerVectors.AllPositiveVectors), typeof(BencodeKnownAnswerVectors), DynamicDataSourceType.Method)]
    public void DecodeThenEncode_ForPositiveVector_ShouldReproduceCanonicalBytes(BencodeKnownAnswerVector vector)
    {
        BencodedValue decoded = Bencode.Decode(vector.EncodedBytes);
        var reencoded = Bencode.Encode(decoded);

        CollectionAssert.AreEqual(vector.EncodedBytes, reencoded);
    }

    /// <summary>
    /// Verifies that randomly generated byte payloads survive encoding via <see cref="BencodedString" /> and
    /// decoding back to identical bytes. Uses a fixed seed so the test is reproducible.
    /// </summary>
    /// <param name="seed">The random-number-generator seed.</param>
    /// <param name="length">The length of the random payload.</param>
    [TestMethod]
    [TestCategory(TestCategories.Regression)]
    [DataRow(1, 0)]
    [DataRow(1, 1)]
    [DataRow(1, 16)]
    [DataRow(1, 256)]
    [DataRow(1, 4096)]
    [DataRow(2, 1024)]
    [DataRow(3, 1024)]
    public void EncodeThenDecode_ForRandomByteString_ShouldRoundTrip(int seed, int length)
    {
        Random rng = new(seed);
        var payload = new byte[length];
        rng.NextBytes(payload);

        BencodedString original = new(payload);
        var encoded = Bencode.Encode(original);
        var decoded = (BencodedString)Bencode.Decode(encoded);

        CollectionAssert.AreEqual(payload, decoded.Bytes.ToArray());
    }

    /// <summary>
    /// Verifies that a randomly generated nested dictionary structure round-trips through encode and decode.
    /// </summary>
    /// <param name="seed">The random-number-generator seed.</param>
    [TestMethod]
    [TestCategory(TestCategories.Regression)]
    [DataRow(1)]
    [DataRow(2)]
    [DataRow(3)]
    public void EncodeThenDecode_ForRandomDictionary_ShouldPreserveContent(int seed)
    {
        Random rng = new(seed);

        List<KeyValuePair<BencodedString, BencodedValue>> pairs = new();
        for (var i = 0; i < 16; i++)
        {
            var key = BencodedString.FromUtf8($"k{i:D3}");
            BencodedValue value = (i % 3) switch
            {
                0 => new BencodedInteger(rng.NextInt64()),
                1 => BencodedString.FromUtf8($"v{rng.Next(10000)}"),
                _ => new BencodedList([new BencodedInteger(rng.Next()), BencodedString.FromUtf8($"x{rng.Next()}")]),
            };
            pairs.Add(new KeyValuePair<BencodedString, BencodedValue>(key, value));
        }

        BencodedDictionary original = new(pairs);
        var encoded = Bencode.Encode(original);
        var decoded = (BencodedDictionary)Bencode.Decode(encoded);

        Assert.AreEqual(original.Count, decoded.Count);
        foreach (KeyValuePair<BencodedString, BencodedValue> pair in original.GetOrderedItems())
        {
            Assert.IsTrue(decoded.TryGetValue(pair.Key, out BencodedValue decodedValue));
            CollectionAssert.AreEqual(Bencode.Encode(pair.Value), Bencode.Encode(decodedValue));
        }
    }

}
