<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS8600;CS8601;CS8602;CS8604;CS8618;CS8625;CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.MSTest" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Bodu.CodeStyle.XmlDocumentation.Analyzers.csproj" />
    <ProjectReference Include="..\..\Bodu.CodeStyle.XmlDocumentation.Core\src\Bodu.CodeStyle.XmlDocumentation.Core.csproj" />
    <ProjectReference Include="..\..\Bodu.CodeStyle.Test.Common\Bodu.CodeStyle.Test.Common.csproj" />
  </ItemGroup>

</Project>
