// ---------------------------------------------------------------------------------------------------------------
// <copyright file="XmlDocFormatAnalyzerTests.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Threading.Tasks;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Diagnostics;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Test;

[TestClass]
public partial class XmlDocFormatAnalyzerTests
{
    private static CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier> CreateTest(string source) =>
        new CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

    /// <summary>
    /// Verifies that a canonical, multi-line doc comment does not trigger BODUXML001.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenDocCommentIsCanonical_ShouldNotReport()
    {
        string source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <summary>\r\n" +
            "    /// Foo.\r\n" +
            "    /// </summary>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync();
    }

    /// <summary>
    /// Verifies that a single-line summary triggers BODUXML001.
    /// </summary>
    [TestMethod]
    [TestCategory(TestCategories.Smoke)]
    public async Task Analyze_WhenDocCommentMisformatted_ShouldReportBODUXML001()
    {
        string source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <summary>Foo.</summary>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier> test = CreateTest(source);
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.XmlDocumentationFormatting)
                .WithSpan(3, 5, 4, 1)
                );

        await test.RunAsync();
    }

    /// <summary>
    /// Verifies that a generated-code file marked with the auto-generated header is skipped entirely.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenAutoGeneratedMarkerPresent_ShouldSkip()
    {
        string source =
            "// <auto-generated />\r\n" +
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <summary>Foo.</summary>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync();
    }
}
