// ---------------------------------------------------------------------------------------------------------------
// <copyright file="XmlDocFormatAnalyzerTests.GeneratedCode.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Threading.Tasks;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Diagnostics;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Test;

public partial class XmlDocFormatAnalyzerTests
{
    /// <summary>
    /// Verifies that a file containing the <c>&lt;auto-generated /&gt;</c> marker produces no diagnostics even
    /// when its doc comments are misformatted.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenAutoGeneratedHeaderPresent_ShouldSkip()
    {
        string source =
            "// <auto-generated />\r\n" +
            "public sealed class Generated\r\n" +
            "{\r\n" +
            "    /// <summary>Bar.</summary>\r\n" +
            "    public int X;\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier> test = CreateTest(source);

        await test.RunAsync();
    }

    /// <summary>
    /// Verifies that a file containing only the <c>&lt;auto-generated/&gt;</c> marker (no slash space) also
    /// triggers the skip path.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenAutoGeneratedHeaderHasNoSlashSpace_ShouldSkip()
    {
        string source =
            "// <auto-generated/>\r\n" +
            "public sealed class Generated\r\n" +
            "{\r\n" +
            "    /// <summary>Bar.</summary>\r\n" +
            "    public int X;\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier> test = CreateTest(source);

        await test.RunAsync();
    }

    /// <summary>
    /// Verifies that even when the <c>&lt;auto-generated&gt;</c> marker appears further down the file, Roslyn's
    /// built-in generated-code detection skips analysis. The analyzer's <see cref="GeneratedCodeAnalysisFlags" />
    /// configuration tells Roslyn to skip generated files entirely before our actions run.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenAutoGeneratedAppearsLateInFile_ShouldStillSkip()
    {
        string source =
            "// Line 1\r\n" +
            "// Line 2\r\n" +
            "// Line 3\r\n" +
            "// Line 4\r\n" +
            "// Line 5\r\n" +
            "// <auto-generated />\r\n" +
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <summary>Bar.</summary>\r\n" +
            "    public int X;\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocFormatAnalyzer, MSTestVerifier> test = CreateTest(source);

        await test.RunAsync();
    }
}
