// ---------------------------------------------------------------------------------------------------------------
// <copyright file="XmlDocCodeRequiresCDataAnalyzerTests.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Threading.Tasks;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Diagnostics;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Test;

[TestClass]
public sealed class XmlDocCodeRequiresCDataAnalyzerTests
{
    private static CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier> CreateTest(string source) =>
        new CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

    /// <summary>
    /// Verifies that a single-line <c>&lt;code&gt;</c> element whose only child is a CDATA section does not trigger BODU1405.
    /// </summary>
    [TestMethod]
    [TestCategory(TestCategories.Smoke)]
    public async Task Analyze_WhenCodeBeginsWithCData_ShouldNotReport()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code><![CDATA[var x = 5;]]></code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that a multi-line <c>&lt;code&gt;</c> element whose first non-whitespace child is a CDATA
    /// section (with intervening doc-comment prefix whitespace and newlines) does not trigger BODU1405.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenCodeWrapsCDataAcrossLines_ShouldNotReport()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code>\r\n" +
            "    /// <![CDATA[\r\n" +
            "    /// var x = 5;\r\n" +
            "    /// ]]>\r\n" +
            "    /// </code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that an inline <c>&lt;c&gt;</c> element (which is not a <c>&lt;code&gt;</c> block) does not trigger BODU1405.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenInlineCElementUsedInsteadOfCode_ShouldNotReport()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <summary>See <c>X</c> for details.</summary>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that a file marked with the standard <c>&lt;auto-generated /&gt;</c> header is skipped entirely.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenAutoGeneratedMarkerPresent_ShouldSkip()
    {
        var source =
            "// <auto-generated />\r\n" +
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code>var x = 5;</code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        await CreateTest(source).RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that a <c>&lt;code&gt;</c> element containing only text content (no CDATA) triggers BODU1405.
    /// </summary>
    [TestMethod]
    [TestCategory(TestCategories.Smoke)]
    public async Task Analyze_WhenCodeContainsOnlyText_ShouldReportBODU1405()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code>var x = 5;</code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier> test = CreateTest(source);
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.XmlDocCodeRequiresCData)
                .WithSpan(3, 9, 3, 15));

        await test.RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that a <c>&lt;code&gt;</c> element whose first child is text (before a later CDATA) triggers BODU1405.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenCodeContainsTextBeforeCData_ShouldReportBODU1405()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code>prefix<![CDATA[var x = 5;]]></code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier> test = CreateTest(source);
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.XmlDocCodeRequiresCData)
                .WithSpan(3, 9, 3, 15));

        await test.RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that an empty <c>&lt;code&gt;&lt;/code&gt;</c> element triggers BODU1405 because it has no CDATA child.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenCodeIsEmpty_ShouldReportBODU1405()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code></code>\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier> test = CreateTest(source);
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.XmlDocCodeRequiresCData)
                .WithSpan(3, 9, 3, 15));

        await test.RunAsync(TestContext.CancellationTokenSource.Token);
    }

    /// <summary>
    /// Verifies that a self-closing <c>&lt;code /&gt;</c> element triggers BODU1405 because it has no children.
    /// </summary>
    [TestMethod]
    public async Task Analyze_WhenCodeIsSelfClosing_ShouldReportBODU1405()
    {
        var source =
            "public sealed class Sample\r\n" +
            "{\r\n" +
            "    /// <code />\r\n" +
            "    public int X { get; set; }\r\n" +
            "}\r\n";

        CSharpAnalyzerTest<XmlDocCodeRequiresCDataAnalyzer, MSTestVerifier> test = CreateTest(source);
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.XmlDocCodeRequiresCData)
                .WithSpan(3, 9, 3, 17));

        await test.RunAsync(TestContext.CancellationTokenSource.Token);
    }

    public TestContext TestContext { get; set; } = null!;
}
