#!/usr/bin/env bash
# ---------------------------------------------------------------------------------------------------------------
# check-policy.sh
#
# Deterministic (Tier-1) coding-policy gate for the Bodu solution. Enforces the mechanically
# checkable rules from CLAUDE.md that the Roslyn analyzers do not already cover, and reports
# violations as GitHub Actions error annotations (::error file=...::) plus a human summary.
#
# DIFF-SCOPED BY DESIGN. A mature tree carries a few grandfathered stragglers (e.g. the
# TestHelpers files without a banner, or the Bodu.Text.Yaml literal exception messages). To
# introduce a BLOCKING gate without a big-bang cleanup, this script only judges what a change
# actually adds: added FILES for whole-file rules, added LINES for line rules. Pre-existing
# violations are grandfathered until the offending line is touched; new code must comply.
#
# Checks:
#   1. Banner       — every ADDED .cs file starts with the copyright banner (CLAUDE.md > File Header).
#   2. FileScopedNs — every ADDED .cs file uses a file-scoped `namespace X;` (CLAUDE.md > Namespace Style).
#   3. ResxMessage  — no string-literal exception message on ADDED src lines; messages come from the
#                     *ResourceStrings resx via ThrowHelper (CLAUDE.md > Static Text and Exception Messages).
#
# Generated files (*.Designer.cs, *.g.cs, or any file whose head carries an <auto-generated> banner)
# are exempt from 1 and 2. Test code (paths containing /test/) is exempt from 3 (the resx rule is a
# production-code policy).
#
# Usage:  bld/check-policy.sh [BASE_REF] [HEAD_REF]
#   BASE_REF  merge-base side of the diff. Default: $POLICY_BASE_REF, else `git merge-base origin/master HEAD`.
#   HEAD_REF  tip side of the diff.        Default: $POLICY_HEAD_REF, else HEAD.
#
# Exit code: 0 when the change is clean, 1 when one or more violations are found.
# ---------------------------------------------------------------------------------------------------------------
set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

base_ref="${1:-${POLICY_BASE_REF:-}}"
head_ref="${2:-${POLICY_HEAD_REF:-HEAD}}"

if [ -z "$base_ref" ]; then
  base_ref="$(git merge-base origin/master "$head_ref" 2>/dev/null || git merge-base master "$head_ref" 2>/dev/null || echo "")"
fi
if [ -z "$base_ref" ]; then
  echo "::error::check-policy.sh could not resolve a base ref for diffing. Pass BASE_REF or set POLICY_BASE_REF." >&2
  exit 2
fi

violations=0

emit() {
  # emit <file> <line> <message>
  local file="$1" line="$2" msg="$3"
  echo "::error file=${file},line=${line}::${msg}"
  echo "  ✗ ${file}:${line} — ${msg}" >&2
  violations=$((violations + 1))
}

is_generated() {
  # is_generated <file>
  local f="$1"
  case "$f" in
    *.Designer.cs|*.g.cs|*.generated.cs) return 0 ;;
  esac
  [ -f "$f" ] && head -3 "$f" | grep -q '<auto-generated' && return 0
  return 1
}

# ── Whole-file rules over ADDED .cs files ──────────────────────────────────────────────────────
while IFS= read -r f; do
  [ -z "$f" ] && continue
  case "$f" in *.cs) ;; *) continue ;; esac
  [ -f "$f" ] || continue
  is_generated "$f" && continue

  # 1. Banner in the first few lines.
  if ! head -5 "$f" | grep -q '<copyright file='; then
    emit "$f" 1 "New file is missing the Bodu copyright banner (CLAUDE.md > Source File Conventions > File Header)."
  fi

  # 2. File-scoped namespace. A compliant file declares `namespace X;`. Flag the block form
  #    `namespace X { ... }`. Files with no namespace at all (rare: global-scope helpers) are skipped.
  if grep -qE '^[[:space:]]*namespace[[:space:]]+[A-Za-z0-9_.]+[[:space:]]*;' "$f"; then
    : # file-scoped — compliant
  elif grep -qE '^[[:space:]]*namespace[[:space:]]+[A-Za-z0-9_.]+' "$f"; then
    ns_line="$(grep -nE '^[[:space:]]*namespace[[:space:]]+[A-Za-z0-9_.]+' "$f" | head -1 | cut -d: -f1)"
    emit "$f" "${ns_line:-1}" "New file uses a block-scoped namespace; use a file-scoped 'namespace X;' (CLAUDE.md > Namespace Style)."
  fi
done < <(git diff --diff-filter=A --name-only "$base_ref" "$head_ref" -- '*.cs')

# ── Line rules over ADDED lines in production src ───────────────────────────────────────────────
# Collect changed src .cs files (exclude tests), then read only the added lines with their new
# line numbers from a zero-context diff.
mapfile -t src_files < <(
  git diff --diff-filter=ACMR --name-only "$base_ref" "$head_ref" -- '*.cs' \
    | grep -E '/src/' \
    | grep -vE '/test/' || true
)

if [ "${#src_files[@]}" -gt 0 ]; then
  current=""
  newline=0
  while IFS= read -r line; do
    case "$line" in
      '+++ b/'*)
        current="${line#+++ b/}"
        ;;
      '@@ '*)
        # @@ -a,b +c,d @@  → next added line starts at c
        hunk="${line#@@ -}"
        hunk="${hunk#*+}"
        newline="${hunk%%,*}"; newline="${newline%% *}"
        ;;
      '+'*)
        [ "${line:0:3}" = "+++" ] && continue
        content="${line:1}"
        trimmed="${content#"${content%%[![:space:]]*}"}"
        # skip comment lines — doc examples and commented code are not live throws
        case "$trimmed" in
          //*|/\**|\**) newline=$((newline + 1)); continue ;;
        esac
        # 3. Literal exception message: `throw new <T>Exception("...`. A nameof-only argument
        #    (e.g. ArgumentNullException(nameof(x))) carries no literal and is not flagged.
        if printf '%s' "$trimmed" | grep -qE 'throw new [A-Za-z_][A-Za-z0-9_]*Exception\([[:space:]]*(\$?@?")'; then
          emit "$current" "$newline" "Exception message is a string literal; source it from the *ResourceStrings resx via ThrowHelper (CLAUDE.md > Static Text and Exception Messages)."
        fi
        newline=$((newline + 1))
        ;;
      ' '*)
        newline=$((newline + 1))
        ;;
    esac
  done < <(git diff --unified=0 "$base_ref" "$head_ref" -- "${src_files[@]}")
fi

echo >&2
if [ "$violations" -eq 0 ]; then
  echo "Policy gate: OK — no Tier-1 violations in the change." >&2
  exit 0
fi
echo "Policy gate: ${violations} violation(s) found." >&2
exit 1
