#!/usr/bin/env python3
"""Selects, stages, and checks the assemblies the API reference is generated from.

Two subcommands, run by bld/docs/build-api-docs.sh either side of the MSBuild build:

  projects  Decides which projects are documented and writes them for bld/docs/Bodu.Docs.Api.proj:
            every package bld/release-manifest.txt records (published or withheld), less the
            exclusions in bld/docs/api-exclusions.txt.

  stage     Reads what the build produced (docs/obj/api/inputs.tsv, written by BoduGetDocsInputs)
            and, for each framework in $(BoduNetTargets):
              * checks every documented project produced its .dll, .xml, and .pdb;
              * copies them, with the exact reference assemblies the compiler used and their .xml
                documentation, into one flat folder (docs/obj/api/input/<tfm>). DocFX resolves an
                assembly's references from its own folder before the shared runtime, and reads a
                reference's documentation only from a sibling .xml, so staging the reference pack
                there is what lets <inheritdoc /> resolve framework documentation;
              * resolves each assembly's package identity and version, as MSBuild evaluated them;
            and then writes packages.json, frameworks.json, build.json, and the per-framework
            docfx metadata configuration generated from docs/docfx.metadata.json.

A defect in any input fails the command with a GitHub error annotation naming it.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from xml.sax.saxutils import quoteattr

import docs_common as dc


# ------------------------------------------------------------------------------------------ projects


@dataclass(frozen=True)
class DocumentedProject:
    """A project whose public API the reference documents."""

    package_id: str
    project_path: str
    published: bool


def read_exclusions() -> dict[str, str]:
    """Reads bld/docs/api-exclusions.txt as package id → reason."""
    exclusions: dict[str, str] = {}
    with open(os.path.join(dc.BLD_DOCS, "api-exclusions.txt"), encoding="utf-8") as stream:
        for line in stream:
            body, _, reason = line.partition("#")
            package_id = body.strip()
            if package_id:
                exclusions[package_id] = reason.strip()
    return exclusions


def documented_projects() -> list[DocumentedProject]:
    """Returns the documented projects, sorted by package id."""
    check_docs = dc.check_docs()
    published, withheld = check_docs.release_manifest()
    projects = check_docs.packable_package_ids()
    exclusions = read_exclusions()

    problems: list[str] = []
    recorded = set(published) | set(withheld)
    for package_id in sorted(set(exclusions) - recorded):
        problems.append(f"bld/docs/api-exclusions.txt excludes {package_id}, which bld/release-manifest.txt does not record; remove the line")

    selected: list[DocumentedProject] = []
    for package_id in sorted(recorded - set(exclusions)):
        path = projects.get(package_id)
        if path is None:
            problems.append(f"bld/release-manifest.txt records {package_id}, but no packable src/{package_id}.csproj exists")
            continue
        selected.append(DocumentedProject(package_id, os.path.abspath(path), package_id in published))

    if problems:
        raise dc.PipelineError("\n".join(problems))
    return selected


def cmd_projects() -> int:
    """Writes projects.json and the projects.props that bld/docs/Bodu.Docs.Api.proj imports."""
    selected = documented_projects()

    dc.write_json(dc.PROJECTS_JSON, [{"packageId": p.package_id, "project": p.project_path, "published": p.published} for p in selected])

    lines = ["<Project>", "  <!-- Generated by bld/docs/prepare_api_inputs.py projects. Do not edit. -->", "  <ItemGroup>"]
    lines += [f"    <DocsProject Include={quoteattr(p.project_path)} PackageId={quoteattr(p.package_id)} />" for p in selected]
    lines += ["  </ItemGroup>", "</Project>", ""]
    os.makedirs(dc.OBJ, exist_ok=True)
    with open(dc.PROJECTS_PROPS, "w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))

    withheld = [p.package_id for p in selected if not p.published]
    print(f"Documenting {len(selected)} projects ({len(withheld)} withheld from nuget.org: {', '.join(withheld) or 'none'}).")
    return 0


# --------------------------------------------------------------------------------------------- stage

INPUT_COLUMNS = (
    "kind",
    "tfm",
    "project",
    "path",
    "assembly",
    "package_id",
    "package_version",
    "version_override",
    "is_packable",
    "generate_documentation_file",
    "xml",
    "pdb",
    "fusion_name",
    "project_path",
)


def read_inputs(path: str) -> list[dict[str, str]]:
    """Parses inputs.tsv into one dictionary per line, keyed by INPUT_COLUMNS."""
    if not os.path.exists(path):
        raise dc.PipelineError(f"{os.path.relpath(path, dc.ROOT)} does not exist; run the `assemblies` stage of bld/docs/build-api-docs.sh first")
    rows: list[dict[str, str]] = []
    with open(path, encoding="utf-8") as stream:
        for number, line in enumerate(stream, 1):
            fields = line.rstrip("\r\n").split("\t")
            if len(fields) != len(INPUT_COLUMNS):
                raise dc.PipelineError(f"{os.path.relpath(path, dc.ROOT)}:{number} has {len(fields)} fields; expected {len(INPUT_COLUMNS)}")
            rows.append(dict(zip(INPUT_COLUMNS, fields)))
    return rows


_VERSION = re.compile(r"Version=(\d+(?:\.\d+){0,3})")


def fusion_version(fusion_name: str) -> tuple[int, ...]:
    """Returns the assembly version in a fusion name, or () when it names none."""
    match = _VERSION.search(fusion_name)
    return tuple(int(part) for part in match.group(1).split(".")) if match else ()


def validate_packages(assemblies: dict[str, dict[str, dict[str, str]]], selected: list[DocumentedProject], tfms: list[str]) -> tuple[dict[str, dict[str, object]], list[str]]:
    """Resolves each documented assembly to one package id and version, and checks them.

    ``assemblies`` maps project name → framework → the Assembly row that build produced.
    Returns the packages.json content (assembly name → package) and the problems found.
    """
    problems: list[str] = []
    packages: dict[str, dict[str, object]] = {}
    for project in selected:
        name = os.path.splitext(os.path.basename(project.project_path))[0]
        builds = assemblies.get(name, {})
        missing = [tfm for tfm in tfms if tfm not in builds]
        if missing:
            problems.append(f"{project.package_id}: the build produced no assembly for {', '.join(missing)}")
            continue

        ids = {row["package_id"] for row in builds.values()}
        versions = {row["package_version"] for row in builds.values()}
        names = {row["assembly"] for row in builds.values()}
        if ids != {project.package_id}:
            problems.append(f"{project.package_id}: MSBuild resolved package id(s) {sorted(ids)}, which is not exactly the id bld/release-manifest.txt records")
        if len(names) != 1:
            problems.append(f"{project.package_id}: the assembly name differs between frameworks: {sorted(names)}")
        if len(versions) != 1:
            detail = ", ".join(f"{tfm} {builds[tfm]['package_version']}" for tfm in tfms)
            problems.append(f"{project.package_id}: the package version differs between frameworks ({detail}); the build inputs are inconsistent")
        version = next(iter(versions))
        if not version:
            problems.append(f"{project.package_id}: MSBuild resolved an empty PackageVersion")
        for tfm in tfms:
            override = builds[tfm]["version_override"]
            if override and not (version == override or version.startswith(override + "-")):
                problems.append(f"{project.package_id}: sets BoduPackageVersionOverride {override}, but its {tfm} PackageVersion resolved to {version}")

        assembly = next(iter(names))
        if assembly in packages:
            problems.append(f"{project.package_id}: assembly {assembly} is also produced by {packages[assembly]['id']}")
        packages[assembly] = {"id": project.package_id, "version": version, "published": project.published}

    return dict(sorted(packages.items())), problems


def stage_framework(tfm: str, assembly_rows: list[dict[str, str]], reference_rows: list[dict[str, str]]) -> list[str]:
    """Copies one framework's documented assemblies and their references into input_dir(tfm)."""
    problems: list[str] = []
    target = dc.input_dir(tfm)
    shutil.rmtree(target, ignore_errors=True)
    os.makedirs(target)

    documented = {row["assembly"] for row in assembly_rows}
    for row in assembly_rows:
        for kind, path in (("assembly", row["path"]), ("XML documentation", row["xml"]), ("portable PDB", row["pdb"])):
            if not os.path.isfile(path):
                problems.append(f"{row['package_id']} ({tfm}): the {kind} {path} does not exist")
                continue
            shutil.copy2(path, target)

    # One file per reference name. Projects share references, and two can resolve different versions
    # of one assembly (a framework assembly and a newer package of the same name); the runtime would
    # unify on the highest, so that is the one staged.
    chosen: dict[str, dict[str, str]] = {}
    for row in reference_rows:
        name = os.path.splitext(os.path.basename(row["path"]))[0]
        if name in documented:
            continue
        current = chosen.get(name)
        if current is None or fusion_version(row["fusion_name"]) > fusion_version(current["fusion_name"]):
            chosen[name] = row
    for name in sorted(chosen):
        path = chosen[name]["path"]
        if not os.path.isfile(path):
            problems.append(f"reference {path} ({tfm}) does not exist")
            continue
        shutil.copy2(path, target)
        xml = os.path.splitext(path)[0] + ".xml"
        if os.path.isfile(xml):
            shutil.copy2(xml, target)

    print(f"{tfm}: staged {len(assembly_rows)} documented assemblies and {len(chosen)} references in {os.path.relpath(target, dc.ROOT)}")
    return problems


def write_metadata_config(frameworks: list[dc.Framework], assemblies: list[str]) -> None:
    """Expands docs/docfx.metadata.json into one metadata entry per framework."""
    template = dc.read_json(dc.METADATA_TEMPLATE)
    entries = template.get("metadata")
    if not isinstance(entries, list) or len(entries) != 1 or not isinstance(entries[0], dict):
        raise dc.PipelineError("docs/docfx.metadata.json must hold exactly one metadata entry (the settings shared by every framework)")
    settings = entries[0]
    for key in ("src", "dest", "output", "properties"):
        if key in settings:
            raise dc.PipelineError(f"docs/docfx.metadata.json sets '{key}'; the pipeline sets the input and output of each framework itself")

    files = [f"{name}.dll" for name in sorted(assemblies)]
    config = {
        "metadata": [
            {"src": [{"src": f"input/{fw.tfm}", "files": files}], "dest": f"metadata/{fw.tfm}", **settings}
            for fw in frameworks
        ]
    }
    dc.write_json(dc.METADATA_CONFIG, config)


def git_commit() -> str:
    """Returns the commit being documented, which the Source Link URLs must name."""
    return subprocess.run(["git", "-C", dc.ROOT, "rev-parse", "HEAD"], check=True, capture_output=True, text=True).stdout.strip()


def cmd_stage() -> int:
    """Stages every framework's inputs and writes the pipeline's resolved metadata."""
    tfms = dc.bodu_net_targets()
    frameworks = dc.frameworks_newest_first(tfms)
    selected = [dc_project(p) for p in dc.read_json(dc.PROJECTS_JSON)]
    rows = read_inputs(dc.INPUTS_TSV)

    problems: list[str] = []
    built = sorted({row["tfm"] for row in rows})
    if built != sorted(tfms):
        problems.append(f"the build produced frameworks {built}, but $(BoduNetTargets) is {tfms}; rebuild with bld/docs/build-api-docs.sh assemblies")

    assemblies: dict[str, dict[str, dict[str, str]]] = defaultdict(dict)
    for row in rows:
        if row["kind"] == "Assembly":
            if row["tfm"] in assemblies[row["project"]]:
                problems.append(f"{row['project']} ({row['tfm']}) was reported twice")
            assemblies[row["project"]][row["tfm"]] = row

    packages, package_problems = validate_packages(assemblies, selected, tfms)
    problems += package_problems
    if problems:
        return dc.fail(problems, "Documentation inputs")

    for tfm in tfms:
        assembly_rows = [row for row in rows if row["kind"] == "Assembly" and row["tfm"] == tfm]
        reference_rows = [row for row in rows if row["kind"] == "Reference" and row["tfm"] == tfm]
        problems += stage_framework(tfm, assembly_rows, reference_rows)
    if problems:
        return dc.fail(problems, "Staging documentation inputs")

    dc.write_json(dc.PACKAGES_JSON, packages)
    dc.write_json(dc.FRAMEWORKS_JSON, {"_boduFrameworks": [fw.to_json() for fw in frameworks]})
    dc.write_json(dc.BUILD_JSON, {"commit": git_commit(), "frameworks": [fw.tfm for fw in frameworks]})
    write_metadata_config(frameworks, list(packages))

    distinct = sorted({(p["id"], p["version"]) for p in packages.values()}, key=lambda pair: pair[0])
    by_version: dict[str, int] = defaultdict(int)
    for _, version in distinct:
        by_version[str(version)] += 1
    summary = ", ".join(f"{count} at {version}" for version, count in sorted(by_version.items()))
    print(f"Resolved {len(packages)} packages ({summary}) for {', '.join(fw.label for fw in frameworks)}.")
    return 0


def dc_project(record: dict[str, object]) -> DocumentedProject:
    """Rebuilds a DocumentedProject from its projects.json record."""
    return DocumentedProject(str(record["packageId"]), str(record["project"]), bool(record["published"]))


def main(argv: list[str]) -> int:
    commands = {"projects": cmd_projects, "stage": cmd_stage}
    if len(argv) != 2 or argv[1] not in commands:
        print(__doc__, file=sys.stderr)
        return 2
    try:
        return commands[argv[1]]()
    except dc.PipelineError as error:
        return dc.fail(str(error).splitlines(), f"prepare_api_inputs {argv[1]}")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
