<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Bodu.Globalization.Calendar.Americas.csproj" />
    <ProjectReference Include="..\..\Bodu.Globalization.Calendar.Data.Test.Common\Bodu.Globalization.Calendar.Data.Test.Common.csproj" />
    <ProjectReference Include="..\..\..\Bodu.Test\test\Bodu.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Globalization.Calendar\Fixtures\Vectors\*.csv">
      <LogicalName>Bodu.Globalization.Calendar.Americas.Fixtures.Vectors.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
