<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(BoduNetTargets)</TargetFrameworks>
    <RootNamespace>Bodu.Globalization.Calendar.Tool</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Test\test\Bodu.Test.csproj" />
    <ProjectReference Include="..\src\Bodu.Globalization.Calendar.Tool.csproj" />
  </ItemGroup>

</Project>
