//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu.Globalization.Calendar.Tool {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.Globalization.Calendar.Tool.ToolResourceStrings", typeof(ToolResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to bodu-calendar — compile and lint Bodu notable-date rule packs.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown command &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnknownCommand {
            get {
                return ResourceManager.GetString("Error_UnknownCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing required argument for &apos;{0}&apos;..
        /// </summary>
        internal static string Error_MissingArgument {
            get {
                return ResourceManager.GetString("Error_MissingArgument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown option &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnknownOption {
            get {
                return ResourceManager.GetString("Error_UnknownOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported document extension &apos;{0}&apos;: expected .xml or .json..
        /// </summary>
        internal static string Error_UnsupportedExtension {
            get {
                return ResourceManager.GetString("Error_UnsupportedExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: OK — resource &apos;{1}&apos; is valid ({2} diagnostic(s))..
        /// </summary>
        internal static string Lint_Clean {
            get {
                return ResourceManager.GetString("Lint_Clean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: FAILED — {1} error(s), {2} total diagnostic(s)..
        /// </summary>
        internal static string Lint_Failed {
            get {
                return ResourceManager.GetString("Lint_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compiled &apos;{0}&apos; -&gt; {1} ({2} bytes, sha256 {3})..
        /// </summary>
        internal static string Compile_Succeeded {
            get {
                return ResourceManager.GetString("Compile_Succeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: format v{1}, resource &apos;{2}&apos; (schema {3}), {4} notable date(s), {5} adjustment policy(ies), payload sha256 {6}..
        /// </summary>
        internal static string Info_Summary {
            get {
                return ResourceManager.GetString("Info_Summary", resourceCulture);
            }
        }
    }
}
