// ---------------------------------------------------------------------------------------------------------------
// <copyright file="Program.cs" company="Bodu Pty. Ltd.">
//     Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Bodu.Tools.CurrencyCatalogueGenerator;

/// <summary>
/// Reads currencies.json and emits one C# tag file per ISO 4217 entry under the Bodu.Numerics Currencies folder.
/// </summary>
internal static class Program
{
    private const string FileHeader = """
        // ---------------------------------------------------------------------------------------------------------------
        // <auto-generated>
        //     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
        //     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
        // </auto-generated>
        // ---------------------------------------------------------------------------------------------------------------

        """;

    private static int Main(string[] args)
    {
        string repoRoot = LocateRepoRoot();
        string inputPath = Path.Combine(repoRoot, "Bodu.Numerics", "src", "Numerics", "Currencies", "currencies.json");
        string outputDir = Path.Combine(repoRoot, "Bodu.Numerics", "src", "Numerics", "Currencies");

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"Input file not found: {inputPath}");
            return 1;
        }

        Console.WriteLine($"Reading {inputPath}");
        Catalogue catalogue = ReadCatalogue(inputPath);
        Console.WriteLine($"Loaded {catalogue.Currencies.Length} currency entries.");

        var existing = new HashSet<string>(
            Directory.EnumerateFiles(outputDir, "*.cs", SearchOption.TopDirectoryOnly).Select(Path.GetFileName)!,
            StringComparer.Ordinal);

        int written = 0;
        int unchanged = 0;
        foreach (CurrencyEntry currency in catalogue.Currencies)
        {
            ValidateEntry(currency);

            string fileName = currency.Iso + ".cs";
            string outputPath = Path.Combine(outputDir, fileName);
            string source = BuildSource(currency);

            if (File.Exists(outputPath) && File.ReadAllText(outputPath) == source)
            {
                unchanged++;
            }
            else
            {
                File.WriteAllText(outputPath, source);
                written++;
            }

            existing.Remove(fileName);
        }

        foreach (string stale in existing)
        {
            if (string.Equals(stale, "currencies.json", StringComparison.Ordinal))
                continue;
            if (string.Equals(stale, "README.md", StringComparison.Ordinal))
                continue;

            string stalePath = Path.Combine(outputDir, stale);
            Console.WriteLine($"Removing stale file: {stale}");
            File.Delete(stalePath);
        }

        Console.WriteLine($"Done. Wrote {written}, left {unchanged} unchanged, removed {existing.Count}.");
        return 0;
    }

    private static Catalogue ReadCatalogue(string path)
    {
        string json = File.ReadAllText(path);
        var options = new JsonSerializerOptions
        {
            ReadCommentHandling = JsonCommentHandling.Skip,
            AllowTrailingCommas = true,
            PropertyNameCaseInsensitive = true,
        };

        Catalogue? catalogue = JsonSerializer.Deserialize<Catalogue>(json, options);
        if (catalogue is null || catalogue.Currencies is null)
            throw new InvalidDataException("currencies.json could not be deserialized.");

        return catalogue;
    }

    private static void ValidateEntry(CurrencyEntry currency)
    {
        if (currency.Iso is null || currency.Iso.Length != 3)
            throw new InvalidDataException($"Invalid ISO code: '{currency.Iso}'.");

        for (int i = 0; i < 3; i++)
        {
            char c = currency.Iso[i];
            if (c < 'A' || c > 'Z')
                throw new InvalidDataException($"ISO code '{currency.Iso}' must be three uppercase ASCII letters.");
        }

        if (currency.Numeric < 0 || currency.Numeric > 999)
            throw new InvalidDataException($"ISO numeric code {currency.Numeric} for {currency.Iso} is out of range.");

        if (currency.MinorUnits < 0 || currency.MinorUnits > 4)
            throw new InvalidDataException($"MinorUnits {currency.MinorUnits} for {currency.Iso} is out of supported range [0, 4].");
    }

    private static string BuildSource(CurrencyEntry currency)
    {
        StringBuilder builder = new();
        builder.Append(FileHeader);
        builder.AppendLine("namespace Bodu.Numerics.Currencies;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.Append("/// Identifies ").Append(currency.Iso).Append(" (").Append(currency.Name).AppendLine(") at the type-system level.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("/// <remarks>");
        builder.Append("/// ISO 4217 numeric code <c>").Append(currency.Numeric.ToString(CultureInfo.InvariantCulture)).Append("</c>; minor-unit precision <c>").Append(currency.MinorUnits.ToString(CultureInfo.InvariantCulture)).AppendLine("</c>.");
        builder.AppendLine("/// </remarks>");
        builder.Append("public sealed class ").Append(currency.Iso).AppendLine(" : ICurrency");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets the ISO 4217 alphabetic code for the currency.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <returns>The three-letter ISO 4217 code.</returns>");
        builder.Append("    public static string IsoCode => \"").Append(currency.Iso).AppendLine("\";");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Gets the number of fractional digits in the currency's minor unit.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <returns>The currency's minor-unit precision.</returns>");
        builder.Append("    public static int MinorUnits => ").Append(currency.MinorUnits.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.Append("    /// Prevents instantiation of the <see cref=\"").Append(currency.Iso).AppendLine("\" /> tag type.");
        builder.AppendLine("    /// </summary>");
        builder.Append("    private ").Append(currency.Iso).AppendLine("()");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string LocateRepoRoot()
    {
        DirectoryInfo? dir = new(Directory.GetCurrentDirectory());
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "bodu.slnx")))
                return dir.FullName;
            dir = dir.Parent;
        }

        throw new InvalidOperationException("Unable to locate repository root (bodu.slnx not found in any ancestor).");
    }

    private sealed record Catalogue
    {
        public CurrencyEntry[] Currencies { get; init; } = [];
    }

    private sealed record CurrencyEntry
    {
        public string Iso { get; init; } = string.Empty;
        public int Numeric { get; init; }
        public int MinorUnits { get; init; }
        public string Name { get; init; } = string.Empty;
    }
}
