// ---------------------------------------------------------------------------------------------------------------
// <copyright file="GeneratedCodeFiltersTests.cs" company="Bodu Pty. Ltd.">
//     Copyright (c) Bodu Pty. Ltd.. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Test.Internal;

[TestClass]
public sealed class GeneratedCodeFiltersTests
{
    /// <summary>
    /// Verifies that <see cref="GeneratedCodeFilters.IsGeneratedFileName" /> throws when the tree is
    /// <see langword="null" />.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenTreeIsNull_ShouldThrowArgumentNullException()
    {
        ArgumentNullException ex = Assert.ThrowsException<ArgumentNullException>(() =>
        {
            _ = GeneratedCodeFilters.IsGeneratedFileName(null!);
        });

        Assert.AreEqual("tree", ex.ParamName);
    }

    /// <summary>
    /// Verifies that <see cref="GeneratedCodeFilters.HasAutoGeneratedMarker" /> throws when the tree is
    /// <see langword="null" />.
    /// </summary>
    [TestMethod]
    public void HasAutoGeneratedMarker_WhenTreeIsNull_ShouldThrowArgumentNullException()
    {
        ArgumentNullException ex = Assert.ThrowsException<ArgumentNullException>(() =>
        {
            _ = GeneratedCodeFilters.HasAutoGeneratedMarker(null!);
        });

        Assert.AreEqual("tree", ex.ParamName);
    }

    /// <summary>
    /// Verifies that <c>*.g.cs</c> filenames are recognised as generated.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenFileNameEndsWithDotGCs_ShouldReturnTrue()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.g.cs", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsTrue(GeneratedCodeFilters.IsGeneratedFileName(tree));
    }

    /// <summary>
    /// Verifies that <c>*.designer.cs</c> filenames are recognised as generated.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenFileNameEndsWithDesignerCs_ShouldReturnTrue()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.designer.cs", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsTrue(GeneratedCodeFilters.IsGeneratedFileName(tree));
    }

    /// <summary>
    /// Verifies that <c>*.generated.cs</c> filenames are recognised as generated.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenFileNameEndsWithGeneratedCs_ShouldReturnTrue()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.generated.cs", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsTrue(GeneratedCodeFilters.IsGeneratedFileName(tree));
    }

    /// <summary>
    /// Verifies that ordinary <c>.cs</c> filenames are not recognised as generated.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenFileNameIsOrdinary_ShouldReturnFalse()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.cs", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsFalse(GeneratedCodeFilters.IsGeneratedFileName(tree));
    }

    /// <summary>
    /// Verifies that a tree with no <c>FilePath</c> is treated as non-generated.
    /// </summary>
    [TestMethod]
    public void IsGeneratedFileName_WhenFilePathIsEmpty_ShouldReturnFalse()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsFalse(GeneratedCodeFilters.IsGeneratedFileName(tree));
    }

    /// <summary>
    /// Verifies that an <c>&lt;auto-generated /&gt;</c> marker on the first line is detected.
    /// </summary>
    [TestMethod]
    public void HasAutoGeneratedMarker_WhenMarkerOnFirstLine_ShouldReturnTrue()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("// <auto-generated />\r\nclass X { }", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsTrue(GeneratedCodeFilters.HasAutoGeneratedMarker(tree));
    }

    /// <summary>
    /// Verifies that an <c>&lt;auto-generated&gt;</c> marker beyond the scanned window is not detected by the
    /// internal helper. (Roslyn's broader detection still catches such files at a higher layer.)
    /// </summary>
    [TestMethod]
    public void HasAutoGeneratedMarker_WhenMarkerIsBeyondScannedWindow_ShouldReturnFalse()
    {
        var source =
            "// Line 1\r\n" +
            "// Line 2\r\n" +
            "// Line 3\r\n" +
            "// Line 4\r\n" +
            "// Line 5\r\n" +
            "// <auto-generated />\r\n" +
            "class X { }";

        SyntaxTree tree = CSharpSyntaxTree.ParseText(source, cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsFalse(GeneratedCodeFilters.HasAutoGeneratedMarker(tree));
    }

    /// <summary>
    /// Verifies that a file with no marker returns <see langword="false" />.
    /// </summary>
    [TestMethod]
    public void HasAutoGeneratedMarker_WhenNoMarkerPresent_ShouldReturnFalse()
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText("class X { }", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsFalse(GeneratedCodeFilters.HasAutoGeneratedMarker(tree));
    }

    /// <summary>
    /// Verifies that <see cref="GeneratedCodeFilters.IsGenerated" /> combines the filename and marker checks and
    /// returns a stable result across repeated calls (the cached path).
    /// </summary>
    [TestMethod]
    public void IsGenerated_ShouldCombineChecksAndReturnStableResult()
    {
        SyntaxTree generatedByName = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.g.cs", cancellationToken: TestContext.CancellationTokenSource.Token);
        SyntaxTree generatedByMarker = CSharpSyntaxTree.ParseText("// <auto-generated />\r\nclass X { }", cancellationToken: TestContext.CancellationTokenSource.Token);
        SyntaxTree ordinary = CSharpSyntaxTree.ParseText("class X { }", path: "/tmp/Foo.cs", cancellationToken: TestContext.CancellationTokenSource.Token);

        Assert.IsTrue(GeneratedCodeFilters.IsGenerated(generatedByName));
        Assert.IsTrue(GeneratedCodeFilters.IsGenerated(generatedByMarker));
        Assert.IsFalse(GeneratedCodeFilters.IsGenerated(ordinary));

        // Second calls exercise the per-tree cache and must agree with the first.
        Assert.IsTrue(GeneratedCodeFilters.IsGenerated(generatedByName));
        Assert.IsFalse(GeneratedCodeFilters.IsGenerated(ordinary));
    }

    /// <summary>
    /// Verifies that <see cref="GeneratedCodeFilters.IsGenerated" /> throws when the tree is
    /// <see langword="null" />.
    /// </summary>
    [TestMethod]
    public void IsGenerated_WhenTreeIsNull_ShouldThrowArgumentNullException()
    {
        ArgumentNullException ex = Assert.ThrowsException<ArgumentNullException>(() =>
        {
            _ = GeneratedCodeFilters.IsGenerated(null!);
        });

        Assert.AreEqual("tree", ex.ParamName);
    }

    public TestContext TestContext { get; set; }
}
