// ---------------------------------------------------------------------------------------------------------------
// <copyright file="IntervalTreeGenericTests.DifferentialSweep.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

namespace Bodu.Collections.Generic;

public partial class IntervalTreeGenericTests
{
    /// <summary>The exclusive upper bound of the endpoint universe exercised by the differential sweep.</summary>
    private const int SweepUniverse = 120;

    /// <summary>The maximum interval span generated by the differential sweep.</summary>
    private const int SweepMaxSpan = 25;

    /// <summary>The number of mixed operations applied by the differential sweep.</summary>
    private const int SweepOperations = 4_000;

    /// <summary>The number of operations between full-oracle checkpoints.</summary>
    private const int SweepCheckpointInterval = 400;

    /// <summary>
    /// Verifies that 4,000 seeded weighted add/remove operations mirrored against a brute-force entry-list oracle
    /// leave the <see cref="IntervalTree{TKey, TValue}" /> in exactly the mirrored state at every checkpoint —
    /// count, full ascending enumeration with per-interval insertion order, and stabbing/window probe batteries.
    /// Both remove overloads are exercised, mirroring first-stored and value-specific semantics on the oracle.
    /// </summary>
    [TestMethod]
    [TestCategory("Regression")]
    public void IntervalTree_WhenRandomOperationSweepApplied_ShouldMatchBruteForceOracle()
    {
        var random = new Random(20260705);
        var sut = new IntervalTree<int, int>();
        var oracle = new List<(int Low, int High, int Value)>();
        int nextValue = 0;

        for (int op = 1; op <= SweepOperations; op++)
        {
            int low = random.Next(SweepUniverse);
            int high = low + random.Next(SweepMaxSpan + 1);

            switch (random.Next(5))
            {
                case 0:
                case 1:
                case 2:
                    // Bias toward adds; reuse a small value universe so value-specific removal hits duplicates.
                    int value = nextValue++ % 7;
                    sut.Add(low, high, value);
                    oracle.Add((low, high, value));
                    break;

                case 3:
                    // Remove(low, high): drops the first stored entry of the exact interval. Aim at a random
                    // existing entry half the time (frequent hit) and a random probe otherwise (frequent miss).
                    (int Low, int High) target = (low, high);
                    if (oracle.Count > 0 && random.Next(2) == 0)
                    {
                        (int Low, int High, int Value) existing = oracle[random.Next(oracle.Count)];
                        target = (existing.Low, existing.High);
                    }

                    int firstIndex = oracle.FindIndex(entry => entry.Low == target.Low && entry.High == target.High);
                    bool expected = firstIndex >= 0;
                    if (expected)
                        oracle.RemoveAt(firstIndex);

                    Assert.AreEqual(
                        expected,
                        sut.Remove(target.Low, target.High),
                        $"Remove({target.Low}, {target.High}) disagrees at op {op}.");
                    break;

                default:
                    // Remove(low, high, value): drops the first matching entry of the exact interval.
                    (int Low, int High, int Value) victim = oracle.Count > 0 && random.Next(2) == 0
                        ? oracle[random.Next(oracle.Count)]
                        : (low, high, random.Next(7));

                    int matchIndex = oracle.FindIndex(entry => entry == victim);
                    bool expectedValueRemove = matchIndex >= 0;
                    if (expectedValueRemove)
                        oracle.RemoveAt(matchIndex);

                    Assert.AreEqual(
                        expectedValueRemove,
                        sut.Remove(victim.Low, victim.High, victim.Value),
                        $"Remove({victim.Low}, {victim.High}, {victim.Value}) disagrees at op {op}.");
                    break;
            }

            if (op % SweepCheckpointInterval == 0)
                AssertMatchesOracle(sut, oracle, random, op);
        }

        // Drain the survivors through the value-specific overload to sweep the deletion paths once more.
        foreach ((int low, int high, int value) in oracle.ToArray())
        {
            Assert.IsTrue(sut.Remove(low, high, value));
        }

        Assert.AreEqual(0, sut.Count);
    }

    /// <summary>
    /// Asserts that the tree agrees with the brute-force oracle on count, full ascending enumeration (with values
    /// in per-interval insertion order), and stabbing/window probe batteries answered by linear scans.
    /// </summary>
    /// <param name="sut">The tree under test.</param>
    /// <param name="oracle">The mirrored brute-force entry list, in insertion order.</param>
    /// <param name="random">The seeded probe source.</param>
    /// <param name="op">The operation ordinal, for failure labelling.</param>
    private static void AssertMatchesOracle(
        IntervalTree<int, int> sut, List<(int Low, int High, int Value)> oracle, Random random, int op)
    {
        Assert.AreEqual(oracle.Count, sut.Count, $"Count disagrees at op {op}.");

        // A stable sort on (Low, High) preserves per-interval insertion order, matching the value-list contract.
        List<(int Low, int High, int Value)> expectedOrder = oracle
            .OrderBy(entry => entry.Low)
            .ThenBy(entry => entry.High)
            .ToList();
        CollectionAssert.AreEqual(expectedOrder, sut.ToList(), $"Enumeration disagrees at op {op}.");

        for (int probe = 0; probe < 15; probe++)
        {
            int point = random.Next(-5, SweepUniverse + SweepMaxSpan + 5);

            List<(int Low, int High, int Value)> expected = expectedOrder
                .Where(entry => entry.Low <= point && point <= entry.High)
                .ToList();

            CollectionAssert.AreEqual(
                expected, sut.QueryPoint(point).ToList(), $"QueryPoint({point}) disagrees at op {op}.");
            Assert.AreEqual(
                expected.Count > 0, sut.IntersectsPoint(point), $"IntersectsPoint({point}) disagrees at op {op}.");
        }

        for (int probe = 0; probe < 15; probe++)
        {
            int windowLow = random.Next(-5, SweepUniverse + SweepMaxSpan + 5);
            int windowHigh = windowLow + random.Next(SweepMaxSpan + 1);

            List<(int Low, int High, int Value)> expected = expectedOrder
                .Where(entry => entry.Low <= windowHigh && windowLow <= entry.High)
                .ToList();

            CollectionAssert.AreEqual(
                expected,
                sut.QueryOverlaps(windowLow, windowHigh).ToList(),
                $"QueryOverlaps({windowLow}, {windowHigh}) disagrees at op {op}.");
            Assert.AreEqual(
                expected.Count > 0,
                sut.Intersects(windowLow, windowHigh),
                $"Intersects({windowLow}, {windowHigh}) disagrees at op {op}.");
        }
    }
}
