// ---------------------------------------------------------------------------------------------------------------
// <copyright file="IntervalTreeTests.DifferentialSweep.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

namespace Bodu.Collections.Generic;

public partial class IntervalTreeTests
{
    /// <summary>The exclusive upper bound of the endpoint universe exercised by the differential sweep.</summary>
    private const int SweepUniverse = 200;

    /// <summary>The maximum interval span generated by the differential sweep.</summary>
    private const int SweepMaxSpan = 40;

    /// <summary>The number of mixed operations applied by the differential sweep.</summary>
    private const int SweepOperations = 10_000;

    /// <summary>The number of operations between full-oracle checkpoints.</summary>
    private const int SweepCheckpointInterval = 500;

    /// <summary>The number of stabbing probes evaluated at each checkpoint.</summary>
    private const int SweepPointProbes = 20;

    /// <summary>The number of overlap windows evaluated at each checkpoint.</summary>
    private const int SweepWindowProbes = 20;

    /// <summary>
    /// Verifies that 10,000 seeded weighted add/remove operations mirrored against a brute-force list oracle leave
    /// the <see cref="IntervalTree{T}" /> in exactly the mirrored state at every checkpoint — count, full ascending
    /// enumeration, and batteries of stabbing, overlap-window, and intersection probes answered by linear scans.
    /// This sweep is the correctness gate for the max-endpoint augmentation across every rotation and fixup path.
    /// </summary>
    [TestMethod]
    [TestCategory("Regression")]
    public void IntervalTree_WhenRandomOperationSweepApplied_ShouldMatchBruteForceOracle()
    {
        var random = new Random(20260705);
        var sut = new IntervalTree<int>();
        var oracle = new List<(int Low, int High)>();

        for (int op = 1; op <= SweepOperations; op++)
        {
            int low = random.Next(SweepUniverse);
            int high = low + random.Next(SweepMaxSpan + 1);

            if (random.Next(5) < 3)
            {
                // Bias toward adds so the tree grows through every insertion fixup path.
                sut.Add(low, high);
                oracle.Add((low, high));
            }
            else
            {
                // Remove either a random existing interval (frequent hit) or a random probe (frequent miss);
                // List.Remove drops one occurrence, mirroring the tree's single-occurrence semantics.
                (int Low, int High) victim = oracle.Count > 0 && random.Next(2) == 0
                    ? oracle[random.Next(oracle.Count)]
                    : (low, high);

                Assert.AreEqual(
                    oracle.Remove(victim),
                    sut.Remove(victim.Low, victim.High),
                    $"Remove({victim.Low}, {victim.High}) disagrees at op {op}.");
            }

            if (op % SweepCheckpointInterval == 0)
                AssertMatchesOracle(sut, oracle, random, op);
        }

        // Drain the survivors through Remove to sweep the deletion fixup paths once more.
        foreach ((int low, int high) in oracle.ToArray())
        {
            Assert.IsTrue(sut.Remove(low, high));
        }

        Assert.AreEqual(0, sut.Count);
    }

    /// <summary>
    /// Asserts that the tree agrees with the brute-force oracle on count, full ascending enumeration, and a battery
    /// of stabbing, overlap-window, containment, and intersection probes.
    /// </summary>
    /// <param name="sut">The tree under test.</param>
    /// <param name="oracle">The mirrored brute-force interval list.</param>
    /// <param name="random">The seeded probe source.</param>
    /// <param name="op">The operation ordinal, for failure labelling.</param>
    private static void AssertMatchesOracle(
        IntervalTree<int> sut, List<(int Low, int High)> oracle, Random random, int op)
    {
        Assert.AreEqual(oracle.Count, sut.Count, $"Count disagrees at op {op}.");

        List<(int Low, int High)> expectedOrder = oracle
            .OrderBy(interval => interval.Low)
            .ThenBy(interval => interval.High)
            .ToList();
        CollectionAssert.AreEqual(expectedOrder, sut.ToList(), $"Enumeration disagrees at op {op}.");

        for (int probe = 0; probe < SweepPointProbes; probe++)
        {
            int point = random.Next(-5, SweepUniverse + SweepMaxSpan + 5);

            List<(int Low, int High)> expected = expectedOrder
                .Where(interval => interval.Low <= point && point <= interval.High)
                .ToList();

            CollectionAssert.AreEqual(
                expected, sut.QueryPoint(point).ToList(), $"QueryPoint({point}) disagrees at op {op}.");
            Assert.AreEqual(
                expected.Count > 0, sut.IntersectsPoint(point), $"IntersectsPoint({point}) disagrees at op {op}.");
        }

        for (int probe = 0; probe < SweepWindowProbes; probe++)
        {
            int windowLow = random.Next(-5, SweepUniverse + SweepMaxSpan + 5);
            int windowHigh = windowLow + random.Next(SweepMaxSpan + 1);

            List<(int Low, int High)> expected = expectedOrder
                .Where(interval => interval.Low <= windowHigh && windowLow <= interval.High)
                .ToList();

            CollectionAssert.AreEqual(
                expected,
                sut.QueryOverlaps(windowLow, windowHigh).ToList(),
                $"QueryOverlaps({windowLow}, {windowHigh}) disagrees at op {op}.");
            Assert.AreEqual(
                expected.Count > 0,
                sut.Intersects(windowLow, windowHigh),
                $"Intersects({windowLow}, {windowHigh}) disagrees at op {op}.");
        }
    }
}
