<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bodu.CodeStyle.Ordering.CodeFixes</RootNamespace>
    <AssemblyName>Bodu.CodeStyle.Ordering.CodeFixes</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>false</IsPackable>
    <DevelopmentDependency>true</DevelopmentDependency>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.CodeStyle.Ordering.Core\src\Bodu.CodeStyle.Ordering.Core.csproj" />
    <ProjectReference Include="..\..\Bodu.CodeStyle.Ordering.Analyzers\src\Bodu.CodeStyle.Ordering.Analyzers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bodu.CodeStyle.Ordering.CodeFixes.Test" />
  </ItemGroup>

</Project>
