<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Test\test\Bodu.Test.csproj" />
    <ProjectReference Include="..\..\Bodu.Financial\src\Bodu.Financial.csproj" />
    <ProjectReference Include="..\src\Bodu.Financial.ExchangeRates.Yahoo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fixtures\*.json">
      <LogicalName>Bodu.Financial.ExchangeRates.Yahoo.Fixtures.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
