<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Core\src\Bodu.Core.csproj" />
    <ProjectReference Include="..\..\Bodu.Test\test\Bodu.Test.csproj" />
    <ProjectReference Include="..\src\Bodu.Globalization.Calendar.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Globalization.Calendar\Fixtures\*.xml">
      <LogicalName>Bodu.Globalization.Calendar.Fixtures.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
