<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu.Globalization.Calendar.Plugins.TestPlugin.NotPlugin</RootNamespace>
    <IsPackable>false</IsPackable>
    <BoduEnablePackageValidation>false</BoduEnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Bodu.Globalization.Calendar.Plugins.csproj" />
  </ItemGroup>

</Project>
