//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu.Financial.ExchangeRates {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XeResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XeResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.Financial.ExchangeRates.XeResourceStrings", typeof(XeResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The XE response for {0}/{1} did not contain any charting-rate data..
        /// </summary>
        internal static string Format_Invalid_XeNoData {
            get {
                return ResourceManager.GetString("Format_Invalid_XeNoData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The XE response for {0}/{1} was not valid JSON..
        /// </summary>
        internal static string Format_Invalid_XeResponse {
            get {
                return ResourceManager.GetString("Format_Invalid_XeResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No XE exchange rate is available for {0}/{1} on {2}..
        /// </summary>
        internal static string IO_KeyNotFound_XeRate {
            get {
                return ResourceManager.GetString("IO_KeyNotFound_XeRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire an XE authorization token from the XE website..
        /// </summary>
        internal static string Op_Invalid_XeAuthTokenUnavailable {
            get {
                return ResourceManager.GetString("Op_Invalid_XeAuthTokenUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The XE options charting-rates path must be specified..
        /// </summary>
        internal static string Arg_Invalid_XeOptionsChartingRatesPath {
            get {
                return ResourceManager.GetString("Arg_Invalid_XeOptionsChartingRatesPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The XE options authorization bootstrap URL must be specified..
        /// </summary>
        internal static string Arg_Invalid_XeOptionsAuthBootstrapUrl {
            get {
                return ResourceManager.GetString("Arg_Invalid_XeOptionsAuthBootstrapUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The XE options authorization chunk base URL must be specified..
        /// </summary>
        internal static string Arg_Invalid_XeOptionsAuthChunkBaseUrl {
            get {
                return ResourceManager.GetString("Arg_Invalid_XeOptionsAuthChunkBaseUrl", resourceCulture);
            }
        }
    }
}
