//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu.Numerics {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumericsResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumericsResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.Numerics.NumericsResourceStrings", typeof(NumericsResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The denominator limit must be at least one..
        /// </summary>
        internal static string Arg_OutOfRange_ContinuedFractionLimit {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_ContinuedFractionLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coefficients after the first must be strictly positive..
        /// </summary>
        internal static string Arg_OutOfRange_ContinuedFractionTerm {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_ContinuedFractionTerm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON string &apos;{0}&apos; is not a valid compact Fraction&lt;{1}&gt; form..
        /// </summary>
        internal static string Json_Invalid_CompactFractionForm {
            get {
                return ResourceManager.GetString("Json_Invalid_CompactFractionForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON string &apos;{0}&apos; is not a valid compact Interval&lt;{1}&gt; form..
        /// </summary>
        internal static string Json_Invalid_CompactIntervalForm {
            get {
                return ResourceManager.GetString("Json_Invalid_CompactIntervalForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;denominator&apos; property must be a number or a numeric string..
        /// </summary>
        internal static string Json_Invalid_DenominatorMustBeNumber {
            get {
                return ResourceManager.GetString("Json_Invalid_DenominatorMustBeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;denominator&apos; property must not be zero..
        /// </summary>
        internal static string Json_Invalid_DenominatorZero {
            get {
                return ResourceManager.GetString("Json_Invalid_DenominatorZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;denominator&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateDenominator {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateDenominator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;empty&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateEmpty {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;lower&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateLower {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;lowerInclusive&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateLowerInclusive {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateLowerInclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;numerator&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateNumerator {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateNumerator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;upper&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateUpper {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object contains a duplicate &apos;upperInclusive&apos; property..
        /// </summary>
        internal static string Json_Invalid_DuplicateUpperInclusive {
            get {
                return ResourceManager.GetString("Json_Invalid_DuplicateUpperInclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An empty interval must not carry endpoint properties alongside &apos;empty&apos;..
        /// </summary>
        internal static string Json_Invalid_EmptyIntervalExtraProperties {
            get {
                return ResourceManager.GetString("Json_Invalid_EmptyIntervalExtraProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON string in compact Fraction&lt;{0}&gt; form (e.g. &quot;3/4&quot;)..
        /// </summary>
        internal static string Json_Invalid_ExpectedCompactString_Fraction {
            get {
                return ResourceManager.GetString("Json_Invalid_ExpectedCompactString_Fraction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON string in compact Interval&lt;{0}&gt; form (e.g. &quot;[1, 5)&quot; or &quot;∅&quot;)..
        /// </summary>
        internal static string Json_Invalid_ExpectedCompactString_Interval {
            get {
                return ResourceManager.GetString("Json_Invalid_ExpectedCompactString_Interval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON object containing a Fraction..
        /// </summary>
        internal static string Json_Invalid_ExpectedObject_Fraction {
            get {
                return ResourceManager.GetString("Json_Invalid_ExpectedObject_Fraction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON object containing an Interval..
        /// </summary>
        internal static string Json_Invalid_ExpectedObject_Interval {
            get {
                return ResourceManager.GetString("Json_Invalid_ExpectedObject_Interval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON property name..
        /// </summary>
        internal static string Json_Invalid_ExpectedPropertyName {
            get {
                return ResourceManager.GetString("Json_Invalid_ExpectedPropertyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;lower&apos; property must be a number or a numeric string..
        /// </summary>
        internal static string Json_Invalid_LowerMustBeNumber {
            get {
                return ResourceManager.GetString("Json_Invalid_LowerMustBeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;denominator&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingDenominator {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingDenominator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;lower&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingLower {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;lowerInclusive&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingLowerInclusive {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingLowerInclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;numerator&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingNumerator {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingNumerator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;upper&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingUpper {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON object is missing the required &apos;upperInclusive&apos; property..
        /// </summary>
        internal static string Json_Invalid_MissingUpperInclusive {
            get {
                return ResourceManager.GetString("Json_Invalid_MissingUpperInclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;numerator&apos; property must be a number or a numeric string..
        /// </summary>
        internal static string Json_Invalid_NumeratorMustBeNumber {
            get {
                return ResourceManager.GetString("Json_Invalid_NumeratorMustBeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must be a boolean..
        /// </summary>
        internal static string Json_Invalid_PropertyMustBeBoolean {
            get {
                return ResourceManager.GetString("Json_Invalid_PropertyMustBeBoolean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The JSON ended unexpectedly while reading the value..
        /// </summary>
        internal static string Json_Invalid_UnexpectedEnd {
            get {
                return ResourceManager.GetString("Json_Invalid_UnexpectedEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;upper&apos; property must be a number or a numeric string..
        /// </summary>
        internal static string Json_Invalid_UpperMustBeNumber {
            get {
                return ResourceManager.GetString("Json_Invalid_UpperMustBeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create a JSON converter for &apos;{0}&apos;..
        /// </summary>
        internal static string Op_Invalid_UnableToCreateConverter {
            get {
                return ResourceManager.GetString("Op_Invalid_UnableToCreateConverter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The denominator of a fraction must not be zero..
        /// </summary>
        internal static string DivideByZero_DenominatorZero {
            get {
                return ResourceManager.GetString("DivideByZero_DenominatorZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot divide a fraction by zero..
        /// </summary>
        internal static string DivideByZero_Division {
            get {
                return ResourceManager.GetString("DivideByZero_Division", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot take the remainder of a fraction divided by zero..
        /// </summary>
        internal static string DivideByZero_Remainder {
            get {
                return ResourceManager.GetString("DivideByZero_Remainder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot compute the reciprocal of zero..
        /// </summary>
        internal static string DivideByZero_Reciprocal {
            get {
                return ResourceManager.GetString("DivideByZero_Reciprocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot raise zero to a negative power..
        /// </summary>
        internal static string DivideByZero_ZeroToNegativePower {
            get {
                return ResourceManager.GetString("DivideByZero_ZeroToNegativePower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The magnitude of the exponent is too large to evaluate..
        /// </summary>
        internal static string Overflow_ExponentMagnitude {
            get {
                return ResourceManager.GetString("Overflow_ExponentMagnitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The backing type &apos;{0}&apos; is unbounded and has no minimum value..
        /// </summary>
        internal static string Op_NotSupported_UnboundedMinValue {
            get {
                return ResourceManager.GetString("Op_NotSupported_UnboundedMinValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The backing type &apos;{0}&apos; is unbounded and has no maximum value..
        /// </summary>
        internal static string Op_NotSupported_UnboundedMaxValue {
            get {
                return ResourceManager.GetString("Op_NotSupported_UnboundedMaxValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}..
        /// </summary>
        internal static string Arg_Invalid_ComparandType {
            get {
                return ResourceManager.GetString("Arg_Invalid_ComparandType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The minimum bound must not exceed the maximum bound..
        /// </summary>
        internal static string Arg_Invalid_ClampBounds {
            get {
                return ResourceManager.GetString("Arg_Invalid_ClampBounds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only finite values can be converted to a fraction..
        /// </summary>
        internal static string Arg_Invalid_NonFiniteToFraction {
            get {
                return ResourceManager.GetString("Arg_Invalid_NonFiniteToFraction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one coefficient is required..
        /// </summary>
        internal static string Arg_Invalid_ContinuedFractionEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_ContinuedFractionEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The format string &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Format_Invalid_FractionFormat {
            get {
                return ResourceManager.GetString("Format_Invalid_FractionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid Interval&lt;{1}&gt; representation..
        /// </summary>
        internal static string Format_Invalid_IntervalText {
            get {
                return ResourceManager.GetString("Format_Invalid_IntervalText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The input string &apos;{0}&apos; was not in a correct fraction format..
        /// </summary>
        internal static string Format_Invalid_FractionText {
            get {
                return ResourceManager.GetString("Format_Invalid_FractionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The length of an unbounded interval is infinite and cannot be represented..
        /// </summary>
        internal static string Op_Invalid_IntervalUnboundedLength {
            get {
                return ResourceManager.GetString("Op_Invalid_IntervalUnboundedLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The count of an unbounded discrete interval is infinite and cannot be represented..
        /// </summary>
        internal static string Op_Invalid_DiscreteIntervalUnboundedCount {
            get {
                return ResourceManager.GetString("Op_Invalid_DiscreteIntervalUnboundedCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The union of two disjoint, non-adjacent intervals is not a single contiguous interval; use Difference or accumulate the pieces instead..
        /// </summary>
        internal static string Op_Invalid_IntervalNonContiguousUnion {
            get {
                return ResourceManager.GetString("Op_Invalid_IntervalNonContiguousUnion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An interval endpoint must be a number; NaN is not a valid endpoint..
        /// </summary>
        internal static string Arg_Invalid_IntervalNaNEndpoint {
            get {
                return ResourceManager.GetString("Arg_Invalid_IntervalNaNEndpoint", resourceCulture);
            }
        }
    }
}
