<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bodu</RootNamespace>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <OutputType>Library</OutputType>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Bodu.Globalization.Calendar.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Core\src\Bodu.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Globalization.Calendar\NotableDates.v2.xsd">
      <LogicalName>Bodu.Globalization.Calendar.NotableDates.v2.xsd</LogicalName>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar\NotableDates.v2.schema.json">
      <LogicalName>Bodu.Globalization.Calendar.NotableDates.v2.schema.json</LogicalName>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar\Resources\*.xml">
      <LogicalName>Bodu.Globalization.Calendar.Resources.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CalendarResourceStrings.resx">
      <LastGenOutput>CalendarResourceStrings.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <Compile Update="CalendarResourceStrings.Designer.cs">
      <DependentUpon>CalendarResourceStrings.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

</Project>
