<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\bld\Bodu.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bodu</RootNamespace>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <OutputType>Library</OutputType>
    <OutputType>Library</OutputType>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <DefineConstants>$(DefineConstants);NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <DefineConstants>$(DefineConstants);NET6_0_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <DefineConstants>$(DefineConstants);NET7_0_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NET8_0_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Globalization.Calendar\CalendarDayProviderBase.cs" />
    <Compile Remove="Globalization.Calendar\CalendarDayProviderExtensions.cs" />
    <Compile Remove="Globalization.Calendar\CalendarDayProviderRegistry.cs" />
    <Compile Remove="Globalization.Calendar\CalendarProviderConfig.cs" />
    <Compile Remove="Globalization.Calendar\DefaultCalendarDayProvider.cs" />
    <Compile Remove="Globalization.Calendar\ICalendarDayProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Globalization.Calendar.Resources\christian-gregorian.xml" />
    <None Remove="Globalization.Calendar.Resources\global-all.xml" />
    <None Remove="Globalization.Calendar.Resources\global-core.xml" />
    <None Remove="Globalization.Calendar.Resources\global-cultural.xml" />
    <None Remove="Globalization.Calendar.Resources\global-education.xml" />
    <None Remove="Globalization.Calendar.Resources\global-environment.xml" />
    <None Remove="Globalization.Calendar.Resources\global-health.xml" />
    <None Remove="Globalization.Calendar.Resources\global-remembrance.xml" />
    <None Remove="Globalization.Calendar.Resources\global-social.xml" />
    <None Remove="Globalization.Calendar.Resources\global-un.xml" />
    <None Remove="Globalization.Calendar.Resources\global.core.xml" />
    <None Remove="Globalization.Calendar.Resources\global.cultural.xml" />
    <None Remove="Globalization.Calendar.Resources\global.education.xml" />
    <None Remove="Globalization.Calendar.Resources\global.environment.xml" />
    <None Remove="Globalization.Calendar.Resources\global.health.xml" />
    <None Remove="Globalization.Calendar.Resources\global.remembrance.xml" />
    <None Remove="Globalization.Calendar.Resources\global.social.xml" />
    <None Remove="Globalization.Calendar.Resources\global.un.xml" />
    <None Remove="Globalization.Calendar.Resources\global._all.xml" />
    <None Remove="Globalization.Calendar\NotableDates.xml" />
    <None Remove="Globalization.Calendar\NotableDates.xsd" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Bodu.Globalization.Calendar.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Globalization.Calendar.Resources\christian-gregorian.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-all.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-core.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-cultural.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-education.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-environment.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-health.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-remembrance.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-social.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\global-un.xml" />
    <EmbeddedResource Include="Globalization.Calendar\NotableDates.xml" />
    <EmbeddedResource Include="Globalization.Calendar\NotableDates.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar.Resources\Common.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\Christian.xml" />
    <EmbeddedResource Include="Globalization.Calendar.Resources\region-au.xml">
      <LogicalName>Bodu.Globalization.Calendar.Resources.AU.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar.Resources\region-us.xml">
      <LogicalName>Bodu.Globalization.Calendar.Resources.US.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar.Resources\region-gb.xml">
      <LogicalName>Bodu.Globalization.Calendar.Resources.GB.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Globalization.Calendar.Resources\region-fr.xml">
      <LogicalName>Bodu.Globalization.Calendar.Resources.FR.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="ResourceStrings.resx">
      <LastGenOutput>ResourceStrings.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Core\src\Bodu.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ResourceStrings.Designer.cs">
      <DependentUpon>ResourceStrings.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

</Project>