// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
namespace Bodu.Numerics.Currencies;

/// <summary>
/// Identifies LVL (Latvian Lats) at the type-system level.
/// </summary>
/// <remarks>
/// ISO 4217 numeric code <c>428</c>; minor-unit precision <c>2</c>.
/// Historic — demonetized on 2014-01-14, replaced by EUR.
/// </remarks>
public sealed class LVL : ICurrency
{
    /// <summary>
    /// Gets the ISO 4217 alphabetic code for the currency.
    /// </summary>
    /// <returns>The three-letter ISO 4217 code.</returns>
    public static string IsoCode => "LVL";

    /// <summary>
    /// Gets the number of fractional digits in the currency's minor unit.
    /// </summary>
    /// <returns>The currency's minor-unit precision.</returns>
    public static int MinorUnits => 2;

    /// <summary>
    /// Gets a value indicating that the currency has been demonetized.
    /// </summary>
    /// <returns><see langword="true" /> — this is a historic currency.</returns>
    public static bool IsHistoric => true;

    /// <summary>
    /// Gets the date the currency was withdrawn from circulation.
    /// </summary>
    /// <returns>The demonetization date.</returns>
    public static global::System.DateOnly? DemonetizedOn => new global::System.DateOnly(2014, 1, 14);

    /// <summary>
    /// Gets the ISO 4217 alphabetic code of the currency that replaced this one.
    /// </summary>
    /// <returns>The successor currency's ISO code.</returns>
    public static string? SuccessorIsoCode => "EUR";

    /// <summary>
    /// Prevents instantiation of the <see cref="LVL" /> tag type.
    /// </summary>
    private LVL()
    {
    }
}
