// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
namespace Bodu.Numerics.Currencies;

/// <summary>
/// Identifies VND (Dong) at the type-system level.
/// </summary>
/// <remarks>
/// ISO 4217 numeric code <c>704</c>; minor-unit precision <c>0</c>.
/// </remarks>
public sealed class VND : ICurrency
{
    /// <summary>
    /// Gets the ISO 4217 alphabetic code for the currency.
    /// </summary>
    /// <returns>The three-letter ISO 4217 code.</returns>
    public static string IsoCode => "VND";

    /// <summary>
    /// Gets the number of fractional digits in the currency's minor unit.
    /// </summary>
    /// <returns>The currency's minor-unit precision.</returns>
    public static int MinorUnits => 0;

    /// <summary>
    /// Prevents instantiation of the <see cref="VND" /> tag type.
    /// </summary>
    private VND()
    {
    }
}
