<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(BoduNetTargets)</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Bodu.Tools.IslamicObservanceVectorGenerator</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
