//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu.Financial.ExchangeRates.Caching {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CachingResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CachingResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.Financial.ExchangeRates.Caching.CachingResourceStrings", typeof(CachingResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The cache expiry must be greater than zero, but was {0}..
        /// </summary>
        internal static string Arg_Invalid_ExpiryNotPositive {
            get {
                return ResourceManager.GetString("Arg_Invalid_ExpiryNotPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one exchange-rate provider must be supplied..
        /// </summary>
        internal static string Arg_Invalid_ProvidersEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_ProvidersEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Each exchange-rate provider must be supplied with a non-blank name..
        /// </summary>
        internal static string Arg_Invalid_ProviderNameBlank {
            get {
                return ResourceManager.GetString("Arg_Invalid_ProviderNameBlank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exchange-rate provider must not be null..
        /// </summary>
        internal static string Arg_Invalid_ProviderNull {
            get {
                return ResourceManager.GetString("Arg_Invalid_ProviderNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More than one exchange-rate provider was supplied with the name '{0}'..
        /// </summary>
        internal static string Arg_Invalid_DuplicateProviderName {
            get {
                return ResourceManager.GetString("Arg_Invalid_DuplicateProviderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No exchange rate is available for {0}/{1} on {2}..
        /// </summary>
        internal static string IO_KeyNotFound_ExchangeRate {
            get {
                return ResourceManager.GetString("IO_KeyNotFound_ExchangeRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The end date must not be earlier than the start date..
        /// </summary>
        internal static string Arg_Invalid_RangeInverted {
            get {
                return ResourceManager.GetString("Arg_Invalid_RangeInverted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The provider name '{0}' referenced by the aggregation configuration was not supplied as a child..
        /// </summary>
        internal static string Arg_Invalid_UnknownAggregationChild {
            get {
                return ResourceManager.GetString("Arg_Invalid_UnknownAggregationChild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An aggregation route is keyed by an invalid currency pair..
        /// </summary>
        internal static string Arg_Invalid_AggregationRoutePair {
            get {
                return ResourceManager.GetString("Arg_Invalid_AggregationRoutePair", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An aggregation route must reference at least one provider..
        /// </summary>
        internal static string Arg_Invalid_AggregationRouteEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_AggregationRouteEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An aggregation route must not be null..
        /// </summary>
        internal static string Arg_Invalid_AggregationRouteNull {
            get {
                return ResourceManager.GetString("Arg_Invalid_AggregationRouteNull", resourceCulture);
            }
        }
    }
}
