// ---------------------------------------------------------------------------------------------------------------
// <copyright file="Argon2.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Provides the shared base for the Argon2 password-hashing and key-derivation functions defined by RFC 9106. The
/// concrete variants are <see cref="Argon2d" />, <see cref="Argon2i" />, and <see cref="Argon2id" />.
/// </summary>
/// <remarks>
/// <para>
/// Argon2 is a memory-hard function designed to make password cracking expensive on parallel hardware. An instance
/// binds a set of cost <see cref="Argon2Parameters" /> (memory, iterations, parallelism, and tag length) once, then
/// derives keys or password hashes from a password and salt. Cross-variant verification of a PHC encoded string is
/// available through the static <see cref="Verify(string, ReadOnlySpan{byte})" /> method, which dispatches to the
/// variant named in the string.
/// </para>
/// <para>
/// This implementation computes lanes sequentially; results are identical to a multi-threaded implementation for any
/// degree of parallelism. It is not independently audited and offers best-effort, not guaranteed, side-channel
/// resistance.
/// </para>
/// </remarks>
public abstract class Argon2
{
    /// <summary>
    /// The salt length, in bytes, generated by the parameterless-salt <see cref="Hash(ReadOnlySpan{byte})" /> overload.
    /// </summary>
    private const int GeneratedSaltLength = 16;

    /// <summary>
    /// The minimum accepted salt length, in bytes.
    /// </summary>
    private const int MinSaltLength = 8;

    private readonly Argon2Parameters _parameters;

    /// <summary>
    /// Initializes a new instance of the <see cref="Argon2" /> class with the specified cost parameters.
    /// </summary>
    /// <param name="parameters">The cost and auxiliary parameters governing the derivation.</param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="parameters" /> is <see langword="null" />.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter in <paramref name="parameters" /> falls outside the range permitted by RFC 9106.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// The version code in <paramref name="parameters" /> is neither 0x10 nor 0x13.
    /// </exception>
    protected Argon2(Argon2Parameters parameters)
    {
        ThrowHelper.ThrowIfNull(parameters);
        parameters.Validate();

        _parameters = parameters;
    }

    /// <summary>
    /// Gets the cost and auxiliary parameters bound to this instance.
    /// </summary>
    /// <returns>The <see cref="Argon2Parameters" /> supplied at construction.</returns>
    public Argon2Parameters Parameters => _parameters;

    /// <summary>
    /// Gets the variant code that selects the reference-indexing strategy for this instance.
    /// </summary>
    internal abstract Argon2Type Type { get; }

    /// <summary>
    /// Derives a tag of the configured <see cref="Argon2Parameters.TagLength" /> from the supplied password and salt.
    /// </summary>
    /// <param name="password">The password / message to derive from.</param>
    /// <param name="salt">The salt; must be at least 8 bytes.</param>
    /// <returns>The derived tag.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="salt" /> is shorter than 8 bytes.
    /// </exception>
    public byte[] GetBytes(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt)
    {
        ThrowIfSaltTooShort(salt);

        byte[] tag = new byte[_parameters.TagLength];
        Argon2Core.DeriveTag(Type, _parameters, password, salt, tag);
        return tag;
    }

    /// <summary>
    /// Derives a tag into the supplied destination buffer.
    /// </summary>
    /// <param name="password">The password / message to derive from.</param>
    /// <param name="salt">The salt; must be at least 8 bytes.</param>
    /// <param name="destination">The buffer to receive the tag; its length must equal the configured tag length.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="salt" /> is shorter than 8 bytes, or <paramref name="destination" /> does not have the configured
    /// tag length.
    /// </exception>
    public void DeriveKey(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, Span<byte> destination)
    {
        ThrowIfSaltTooShort(salt);
        if (destination.Length != _parameters.TagLength)
            throw new ArgumentException(
                string.Format(CultureInfo.CurrentCulture, CryptoResourceStrings.Arg_Invalid_Argon2DestinationLength, _parameters.TagLength),
                nameof(destination));

        Argon2Core.DeriveTag(Type, _parameters, password, salt, destination);
    }

    /// <summary>
    /// Derives a tag from the password and a freshly generated random 16-byte salt and returns the result as a PHC
    /// encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <returns>The PHC encoded-hash string, including the generated salt.</returns>
    public string Hash(ReadOnlySpan<byte> password)
    {
        Span<byte> salt = stackalloc byte[GeneratedSaltLength];
        RandomNumberGenerator.Fill(salt);
        return Hash(password, salt);
    }

    /// <summary>
    /// Derives a tag from the password and the supplied salt and returns the result as a PHC encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="salt">The salt to embed in the encoded string; must be at least 8 bytes.</param>
    /// <returns>The PHC encoded-hash string.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="salt" /> is shorter than 8 bytes.
    /// </exception>
    public string Hash(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt)
    {
        ThrowIfSaltTooShort(salt);

        byte[] tag = new byte[_parameters.TagLength];
        Argon2Core.DeriveTag(Type, _parameters, password, salt, tag);

        string encoded = Encode(Type, _parameters, salt, tag);
        CryptographyHelper.Clear(tag);
        return encoded;
    }

    /// <summary>
    /// Verifies a password against an Argon2 PHC encoded-hash string, dispatching to the variant named in the string.
    /// </summary>
    /// <param name="encoded">The PHC encoded-hash string produced by an Argon2 variant.</param>
    /// <param name="password">The password to verify.</param>
    /// <returns>
    /// <see langword="true" /> if the password matches the encoded hash; otherwise, <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="encoded" /> is <see langword="null" />.
    /// </exception>
    /// <exception cref="FormatException">
    /// <paramref name="encoded" /> is not a well-formed Argon2 PHC string.
    /// </exception>
    /// <remarks>
    /// This overload supplies no secret key. Hashes produced with an <see cref="Argon2Parameters.Secret" /> must be
    /// verified through <see cref="Verify(string, ReadOnlySpan{byte}, ReadOnlySpan{byte})" />.
    /// </remarks>
    public static bool Verify(string encoded, ReadOnlySpan<byte> password) =>
        Verify(encoded, password, ReadOnlySpan<byte>.Empty);

    /// <summary>
    /// Verifies a password against an Argon2 PHC encoded-hash string using the supplied secret key.
    /// </summary>
    /// <param name="encoded">The PHC encoded-hash string produced by an Argon2 variant.</param>
    /// <param name="password">The password to verify.</param>
    /// <param name="secret">The secret key (pepper) used when the hash was produced; empty when none was used.</param>
    /// <returns>
    /// <see langword="true" /> if the password matches the encoded hash; otherwise, <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="encoded" /> is <see langword="null" />.
    /// </exception>
    /// <exception cref="FormatException">
    /// <paramref name="encoded" /> is not a well-formed Argon2 PHC string.
    /// </exception>
    public static bool Verify(string encoded, ReadOnlySpan<byte> password, ReadOnlySpan<byte> secret)
    {
        ThrowHelper.ThrowIfNull(encoded);

        Argon2EncodedHash parsed = Decode(encoded);

        var parameters = new Argon2Parameters
        {
            MemoryKiB = parsed.Memory,
            Iterations = parsed.Iterations,
            Parallelism = parsed.Parallelism,
            TagLength = parsed.Hash.Length,
            Version = parsed.Version,
            Secret = secret.IsEmpty ? null : secret.ToArray(),
            AssociatedData = parsed.Data.Length == 0 ? null : parsed.Data,
        };
        parameters.Validate();

        byte[] computed = new byte[parsed.Hash.Length];
        Argon2Core.DeriveTag(parsed.Type, parameters, password, parsed.Salt, computed);

        bool match = CryptographicOperations.FixedTimeEquals(computed, parsed.Hash);
        CryptographyHelper.Clear(computed);
        return match;
    }

    /// <summary>
    /// Validates that <paramref name="encoded" /> names the expected variant and verifies the password against it.
    /// </summary>
    /// <param name="encoded">The PHC encoded-hash string.</param>
    /// <param name="password">The password to verify.</param>
    /// <param name="secret">The secret key used when the hash was produced; empty when none was used.</param>
    /// <param name="expected">The variant the caller expects the string to name.</param>
    /// <returns>
    /// <see langword="true" /> if the string names <paramref name="expected" /> and the password matches; otherwise,
    /// <see langword="false" />.
    /// </returns>
    private protected static bool VerifyAs(string encoded, ReadOnlySpan<byte> password, ReadOnlySpan<byte> secret, Argon2Type expected)
    {
        ThrowHelper.ThrowIfNull(encoded);

        if (Decode(encoded).Type != expected)
            return false;

        return Verify(encoded, password, secret);
    }

    /// <summary>
    /// Throws an <see cref="ArgumentException" /> if the salt is shorter than the minimum length.
    /// </summary>
    private static void ThrowIfSaltTooShort(ReadOnlySpan<byte> salt)
    {
        if (salt.Length < MinSaltLength)
            throw new ArgumentException(
                string.Format(CultureInfo.CurrentCulture, CryptoResourceStrings.Arg_Invalid_KdfSaltTooShort, MinSaltLength),
                nameof(salt));
    }

    /// <summary>
    /// Formats an Argon2 PHC encoded-hash string.
    /// </summary>
    private static string Encode(Argon2Type type, Argon2Parameters p, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> hash)
    {
        var sb = new StringBuilder();
        sb.Append('$').Append(TypeName(type));
        sb.Append("$v=").Append(p.Version.ToString(CultureInfo.InvariantCulture));
        sb.Append("$m=").Append(p.MemoryKiB.ToString(CultureInfo.InvariantCulture))
          .Append(",t=").Append(p.Iterations.ToString(CultureInfo.InvariantCulture))
          .Append(",p=").Append(p.Parallelism.ToString(CultureInfo.InvariantCulture));

        if (p.AssociatedData is { Length: > 0 })
            sb.Append(",data=").Append(PhcString.EncodeBase64(p.AssociatedData));

        sb.Append('$').Append(PhcString.EncodeBase64(salt));
        sb.Append('$').Append(PhcString.EncodeBase64(hash));
        return sb.ToString();
    }

    /// <summary>
    /// Parses an Argon2 PHC encoded-hash string into its constituent fields.
    /// </summary>
    private static Argon2EncodedHash Decode(string encoded)
    {
        string[] fields = PhcString.SplitFields(encoded);

        // Expect: "", name, [v=..], m..t..p.., salt, hash
        if (fields.Length is < 5 or > 6)
            throw PhcString.Invalid();

        int index = 1;
        Argon2Type type = ParseTypeName(fields[index++]);

        int version = Argon2Parameters.Version10;
        if (fields[index].StartsWith("v=", StringComparison.Ordinal))
        {
            version = ParseInt(fields[index][2..]);
            index++;
        }

        if (index + 3 != fields.Length)
            throw PhcString.Invalid();

        (int memory, int iterations, int parallelism, byte[] data) = ParseCostFields(fields[index++]);
        byte[] salt = PhcString.DecodeBase64(fields[index++]);
        byte[] hash = PhcString.DecodeBase64(fields[index]);

        return new Argon2EncodedHash(type, version, memory, iterations, parallelism, salt, hash, data);
    }

    /// <summary>
    /// Parses the comma-separated cost-parameter field (<c>m=..,t=..,p=..[,data=..]</c>).
    /// </summary>
    private static (int Memory, int Iterations, int Parallelism, byte[] Data) ParseCostFields(string field)
    {
        int? memory = null, iterations = null, parallelism = null;
        byte[] data = [];

        foreach (string part in field.Split(','))
        {
            int eq = part.IndexOf('=', StringComparison.Ordinal);
            if (eq <= 0)
                throw PhcString.Invalid();

            string key = part[..eq];
            string value = part[(eq + 1)..];

            switch (key)
            {
                case "m": memory = ParseInt(value); break;
                case "t": iterations = ParseInt(value); break;
                case "p": parallelism = ParseInt(value); break;
                case "data": data = PhcString.DecodeBase64(value); break;
                default: throw PhcString.Invalid();
            }
        }

        if (memory is null || iterations is null || parallelism is null)
            throw PhcString.Invalid();

        return (memory.Value, iterations.Value, parallelism.Value, data);
    }

    /// <summary>
    /// Parses a non-negative decimal integer, throwing a <see cref="FormatException" /> on failure.
    /// </summary>
    private static int ParseInt(string value) =>
        int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out int result)
            ? result
            : throw PhcString.Invalid();

    /// <summary>
    /// Returns the PHC type name for a variant.
    /// </summary>
    private static string TypeName(Argon2Type type) => type switch
    {
        Argon2Type.Argon2d => "argon2d",
        Argon2Type.Argon2i => "argon2i",
        _ => "argon2id",
    };

    /// <summary>
    /// Parses a PHC type name into a variant, throwing a <see cref="FormatException" /> on an unknown name.
    /// </summary>
    private static Argon2Type ParseTypeName(string name) => name switch
    {
        "argon2d" => Argon2Type.Argon2d,
        "argon2i" => Argon2Type.Argon2i,
        "argon2id" => Argon2Type.Argon2id,
        _ => throw PhcString.Invalid(),
    };
}
