// ---------------------------------------------------------------------------------------------------------------
// <copyright file="EaxModeTransform.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Security.Cryptography;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Applies EAX mode to an underlying <see cref="IBlockCipher" />, providing two-pass authenticated encryption with
/// associated data (AEAD) per Bellare, Rogaway and Wagner (FSE 2004).
/// </summary>
/// <remarks>
/// <para>
/// <img src="../images/diagrams/aead-mode.svg" alt="Generic AEAD data flow — EAX instantiates the top pipeline as CTR mode and the bottom pipeline as three OMAC invocations over the nonce, associated data, and ciphertext whose outputs are XOR-combined to form the tag."/>
/// </para>
/// <para>
/// EAX is the <b>CTR + OMAC(N ‖ A ‖ C)</b> instantiation of the generic AEAD shape above. Three independent OMAC
/// invocations are performed with a single-byte tweak <c>t ∈ {0, 1, 2}</c> selecting the input kind:
/// <list type="bullet">
/// <item>
/// <description><c>N' = OMAC_K^0(nonce)</c> — authenticates the nonce and seeds the CTR counter.</description>
/// </item>
/// <item>
/// <description><c>H' = OMAC_K^1(associatedData)</c> — authenticates the AAD.</description>
/// </item>
/// <item>
/// <description><c>C' = OMAC_K^2(ciphertext)</c> — authenticates the ciphertext.</description>
/// </item>
/// </list>
/// The authentication tag is <c>T = N' ⊕ H' ⊕ C'</c>, and the keystream is generated by encrypting successive
/// big-endian increments of <c>N'</c> with the underlying block cipher.
/// </para>
/// <para>
/// <c>OMAC_K^t(M)</c> is defined as <c>CMAC_K([t]_n ‖ M)</c>, where <c>[t]_n</c> is the integer <c>t</c> encoded as a
/// full <c>BlockSize</c>-byte big-endian block. All three invocations therefore share the same CMAC subkeys K₁ =
/// dbl(E(0ⁿ)) and K₂ = dbl(K₁), derived from the cipher once per instance.
/// </para>
/// <para>
/// The tag size is fixed at 16 bytes (the full OMAC output). The IV is the raw nonce: the class computes <c>N'</c>
/// internally. Ciphertext is output as <c>C ‖ T</c> (ciphertext then tag), consistent with the
/// <see cref="IAeadBlockCipherModeTransform" /> convention.
/// </para>
/// <para>
/// <strong>When to use EAX.</strong> Pick EAX when an unencumbered, two-pass AEAD with a flexible nonce length (the
/// OMAC-derived <c>N'</c> means EAX accepts nonces up to the cipher block size) is wanted — some embedded protocols and
/// historical industry standards require it. EAX is roughly half the throughput of <see cref="GcmModeTransform" /> on
/// commodity hardware but does not depend on Galois-field arithmetic and has no patent concerns. For new
/// general-purpose AEAD prefer GCM; for nonce-misuse resistance prefer <see cref="GcmSivModeTransform" /> or
/// <see cref="SivModeTransform" />; for single-pass AEAD without GCM's catastrophic-on-reuse profile prefer
/// <see cref="OcbModeTransform" />.
/// </para>
/// <para>
/// <strong>Nonce uniqueness is required.</strong> EAX is not nonce-misuse resistant. Two messages encrypted under the
/// same <c>(key, nonce)</c> share the same <c>N'</c> seed, so they share the same CTR keystream and an attacker can
/// recover <c>P1 XOR P2</c>; the per-message OMAC tag inputs also overlap, weakening authentication. Callers must
/// guarantee that every <c>(key, nonce)</c> pair is used at most once — either via a deterministic per-message counter
/// or a fresh random nonce drawn from a CSPRNG. If nonce uniqueness cannot be guaranteed, prefer
/// <see cref="GcmSivModeTransform" /> or <see cref="SivModeTransform" />.
/// </para>
/// </remarks>
/// <example>
/// <code language="csharp">
///<![CDATA[
/// using System.Security.Cryptography;
/// using Bodu.Security.Cryptography;
/// using Bodu.Security.Cryptography.Extensions;
///
/// using IBlockCipher cipher = new AesBlockCipher(key);
/// byte[] nonce = RandomNumberGenerator.GetBytes(cipher.BlockSize / 8); // unique per message
/// using IAeadBlockCipherModeTransform eax = new EaxModeTransform(cipher, nonce);
/// byte[] sealed_ = eax.Encrypt(plaintext, associatedData: header);
/// using IAeadBlockCipherModeTransform dec = new EaxModeTransform(cipher, nonce);
/// byte[] recovered = dec.Decrypt(sealed_, associatedData: header);
///]]>
/// </code>
/// </example>
/// <seealso href="../guides/cryptography/aead-modes.html#eax--two-pass-fse-2004">EAX walk-through in the AEAD-modes
/// guide</seealso> <seealso cref="AesBlockCipher"/>
/// <seealso cref="Bodu.Security.Cryptography.Extensions.AeadBlockCipherModeTransformExtensions"/>
public sealed class EaxModeTransform
    : IAeadBlockCipherModeTransform, IDisposable
{
    /// <summary>The default EAX authentication-tag size, in bits.</summary>
    private const int DefaultTagSizeBits = 128;

    /// <summary>The default EAX authentication-tag size, in bytes.</summary>
    private const int DefaultTagSize = DefaultTagSizeBits / 8;

    /// <summary>The underlying block cipher used for both OMAC and the CTR keystream.</summary>
    private readonly IBlockCipher _cipher;

    /// <summary>The raw user-supplied nonce, held as a defensive clone.</summary>
    private readonly byte[] _nonce;

    /// <summary>The buffered associated authenticated data, or <see langword="null" /> until processed.</summary>
    private byte[]? _aad;

    /// <summary>Indicates whether the associated data has been processed.</summary>
    private bool _aadProcessed;

    /// <summary>Indicates whether this transform has already completed an encrypt or decrypt operation.</summary>
    private bool _completed;

    /// <summary>Indicates whether this instance has been disposed.</summary>
    private bool _disposed;

    /// <summary>
    /// Initializes a new instance of the <see cref="EaxModeTransform" /> class.
    /// </summary>
    /// <param name="cipher">The block cipher used for both OMAC and the CTR keystream.</param>
    /// <param name="iv">
    /// The nonce <c>N</c>. Must equal the cipher block size. A defensive copy is taken; the caller's array is not
    /// modified.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="cipher" /> or <paramref name="iv" /> is <see langword="null" />.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="iv" /> length does not equal the cipher block size.
    /// </exception>
    public EaxModeTransform(IBlockCipher cipher, byte[] iv)
    {
        ThrowHelper.ThrowIfNull(cipher);
        CryptographyThrowHelper.ThrowIfIvLengthInvalid(iv, cipher.BlockSize);

        _cipher = cipher;

        _nonce = (byte[])iv.Clone();
    }

    /// <inheritdoc />
    /// <value>Length of the EAX authentication tag is 128 bits (16 bytes).</value>
    public int TagSize => DefaultTagSizeBits;

    /// <inheritdoc />
    public void ProcessAssociatedData(ReadOnlySpan<byte> associatedData)
    {
        ThrowIfDisposed();

        CryptographyThrowHelper.ThrowIfAssociatedDataAlreadyProcessed(_aadProcessed);

        _aad = associatedData.ToArray();
        _aadProcessed = true;
    }

    /// <inheritdoc />
    public int Encrypt(ReadOnlySpan<byte> plaintext, Span<byte> output)
    {
        ThrowIfDisposed();
        ThrowIfCompleted();

        int required = plaintext.Length + DefaultTagSize;
        ThrowHelper.ThrowIfSpanLengthIsInsufficient(output, required);

        EnsureAadProcessed();

        byte[]? nPrime = null;
        byte[]? hPrime = null;
        byte[]? cPrime = null;

        try
        {
            nPrime = Omac(0, _nonce);
            hPrime = Omac(1, _aad!);

            // CTR-encrypt plaintext into output[..plaintext.Length] using N' as the initial counter.
            Span<byte> ciphertext = output[..plaintext.Length];
            CtrEncrypt(plaintext, ciphertext, nPrime);

            cPrime = Omac(2, ciphertext);

            // Tag = N' XOR H' XOR C'.
            Span<byte> tag = output.Slice(plaintext.Length, DefaultTagSize);
            for (int i = 0; i < DefaultTagSize; i++)
                tag[i] = (byte)(nPrime[i] ^ hPrime[i] ^ cPrime[i]);

            return required;
        }
        finally
        {
            CryptographyHelper.Clear(nPrime);
            CryptographyHelper.Clear(hPrime);
            CryptographyHelper.Clear(cPrime);
            _completed = true;
        }
    }

    /// <inheritdoc />
    /// <remarks>
    /// <strong>Authentication pattern: verify-before-release.</strong> The OMAC-derived tag is recomputed and compared
    /// in constant time before the CTR decryption stream is applied to <paramref name="output" />; no plaintext byte is
    /// ever written when authentication fails. See <see cref="IAeadBlockCipherModeTransform.Decrypt" /> for the
    /// library-wide failure contract.
    /// </remarks>
    public int Decrypt(ReadOnlySpan<byte> ciphertextWithTag, Span<byte> output)
    {
        ThrowIfDisposed();
        ThrowIfCompleted();

        CryptographyThrowHelper.ThrowIfCiphertextTooShort(ciphertextWithTag, DefaultTagSize);

        int plaintextLength = ciphertextWithTag.Length - DefaultTagSize;
        ThrowHelper.ThrowIfSpanLengthIsInsufficient(output, plaintextLength);

        EnsureAadProcessed();

        ReadOnlySpan<byte> ciphertext = ciphertextWithTag[..plaintextLength];
        ReadOnlySpan<byte> receivedTag = ciphertextWithTag[plaintextLength..];

        byte[]? nPrime = null;
        byte[]? hPrime = null;
        byte[]? cPrime = null;
        byte[]? expectedTag = null;

        try
        {
            nPrime = Omac(0, _nonce);
            hPrime = Omac(1, _aad!);
            cPrime = Omac(2, ciphertext);

            expectedTag = new byte[DefaultTagSize];
            for (int i = 0; i < DefaultTagSize; i++)
                expectedTag[i] = (byte)(nPrime[i] ^ hPrime[i] ^ cPrime[i]);

            // Constant-time tag comparison; throw before emitting any plaintext. On failure, also
            // zero any data the caller may have pre-seeded into the output buffer — defense-in-depth
            // aligned with AsconAead128.Decrypt.
            if (!CryptographicOperations.FixedTimeEquals(expectedTag, receivedTag))
            {
                CryptographyHelper.Clear(output[..plaintextLength]);
                throw new CryptographicException(CryptoResourceStrings.Crypt_Invalid_AuthenticationTagMismatch);
            }

            CtrEncrypt(ciphertext, output[..plaintextLength], nPrime);

            return plaintextLength;
        }
        finally
        {
            CryptographyHelper.Clear(expectedTag);
            CryptographyHelper.Clear(cPrime);
            CryptographyHelper.Clear(hPrime);
            CryptographyHelper.Clear(nPrime);
            _completed = true;
        }
    }

    /// <summary>
    /// Throws <see cref="InvalidOperationException" /> if this transform has already encrypted or decrypted a message.
    /// EAX transforms are single-use; create a fresh instance per message.
    /// </summary>
    private void ThrowIfCompleted() =>
        CryptographyThrowHelper.ThrowIfAlreadyCompleted(_completed);

    /// <summary>
    /// Releases the resources used by this instance and clears retained nonce and associated-data state from memory.
    /// </summary>
    /// <remarks>
    /// The supplied <see cref="IBlockCipher" /> is not disposed by this type. Ownership remains with the caller.
    /// </remarks>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Releases the resources used by this instance.
    /// </summary>
    /// <param name="disposing">
    /// <see langword="true" /> to release managed resources; <see langword="false" /> to release unmanaged resources
    /// only.
    /// </param>
    private void Dispose(bool disposing)
    {
        if (_disposed)
            return;

        if (disposing)
        {
            CryptographyHelper.Clear(_nonce);
            CryptographyHelper.ClearAndNullify(ref _aad);

            _aadProcessed = false;
        }

        _disposed = true;
    }

    // ── Private helpers ────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Ensures the associated-data contribution has been initialized before payload processing.
    /// </summary>
    private void EnsureAadProcessed()
    {
        if (!_aadProcessed)
        {
            _aad = [];
            _aadProcessed = true;
        }
    }

    /// <summary>
    /// Computes <c>OMAC_K^t(m) = CMAC_K([t]_n ‖ m)</c>, where <c>[t]_n</c> is the integer <paramref name="t" /> encoded
    /// as a full-block big-endian prefix.
    /// </summary>
    /// <param name="t">
    /// The single-byte tweak that selects the OMAC domain, encoded as a full-block big-endian prefix.
    /// </param>
    /// <param name="m">The message bytes to authenticate.</param>
    /// <returns>The OMAC tag for <paramref name="m" /> under tweak <paramref name="t" />.</returns>
    private byte[] Omac(byte t, ReadOnlySpan<byte> m)
    {
        int blockSize = _cipher.BlockSize / 8;
        byte[] prefixed = new byte[blockSize + m.Length];

        try
        {
            prefixed[blockSize - 1] = t; // [t]_n = (blockSize − 1) zero bytes, then t
            m.CopyTo(prefixed.AsSpan(blockSize));

            return ComputeCmac(prefixed);
        }
        finally
        {
            CryptographyHelper.Clear(prefixed);
        }
    }

    /// <summary>
    /// Computes AES-CMAC of <paramref name="message" /> under the mode's cipher, per RFC 4493.
    /// </summary>
    /// <param name="message">The message to authenticate.</param>
    /// <returns>The CMAC tag, one cipher block in length.</returns>
    private byte[] ComputeCmac(ReadOnlySpan<byte> message)
    {
        int blockSize = _cipher.BlockSize / 8;

        byte[] zeroBlock = new byte[blockSize];
        byte[] l = new byte[blockSize];
        byte[] k1 = new byte[blockSize];
        byte[] k2 = new byte[blockSize];
        byte[] mac = new byte[blockSize];
        byte[] lastBlock = new byte[blockSize];

        try
        {
            // Subkey generation: K1 = dbl(E(0^n)), K2 = dbl(K1).
            _cipher.Encrypt(zeroBlock, l);

            l.CopyTo(k1, 0);
            Dbl(k1);

            k1.CopyTo(k2, 0);
            Dbl(k2);

            int totalBlocks = (message.Length + blockSize - 1) / blockSize;
            bool lastIsFull = message.Length > 0 && message.Length % blockSize == 0;

            if (message.Length == 0)
            {
                totalBlocks = 1;
                lastIsFull = false;
            }

            for (int blockIdx = 0; blockIdx < totalBlocks - 1; blockIdx++)
            {
                byte[] block = new byte[blockSize];

                try
                {
                    message.Slice(blockIdx * blockSize, blockSize).CopyTo(block);
                    Xor(mac, block, mac);
                    _cipher.Encrypt(mac, mac);
                }
                finally
                {
                    CryptographyHelper.Clear(block);
                }
            }

            // Last block: pad with 0x80 || 0…0 if partial, then XOR K1 (full) or K2 (partial).
            if (message.Length > 0)
            {
                int lastOffset = (totalBlocks - 1) * blockSize;
                int lastLen = message.Length - lastOffset;

                message.Slice(lastOffset, lastLen).CopyTo(lastBlock);

                if (!lastIsFull)
                    lastBlock[lastLen] = 0x80;
            }
            else
            {
                lastBlock[0] = 0x80; // empty message: pad = 0x80 || 0...0
            }

            byte[] subkey = lastIsFull ? k1 : k2;
            Xor(lastBlock, subkey, lastBlock);
            Xor(mac, lastBlock, mac);
            _cipher.Encrypt(mac, mac);

            return mac;
        }
        catch
        {
            // On a mid-MAC cipher fault, zero the partially computed accumulator before it escapes;
            // mirrors SivModeTransform.ComputeCmac so both CMAC paths clear secret state on failure.
            CryptographyHelper.Clear(mac);
            throw;
        }
        finally
        {
            CryptographyHelper.Clear(lastBlock);
            CryptographyHelper.Clear(k2);
            CryptographyHelper.Clear(k1);
            CryptographyHelper.Clear(l);
            CryptographyHelper.Clear(zeroBlock);
        }
    }

    /// <summary>
    /// Applies CTR mode: generates a keystream by encrypting successive big-endian increments of
    /// <paramref name="counter" /> (copied defensively) and XORs it with <paramref name="input" />. The final block may
    /// be partial; remaining keystream bytes are discarded.
    /// </summary>
    /// <param name="input">The bytes to encrypt or decrypt.</param>
    /// <param name="output">The span that receives the transformed bytes.</param>
    /// <param name="counter">The initial counter block; copied defensively and left unmodified.</param>
    private void CtrEncrypt(ReadOnlySpan<byte> input, Span<byte> output, byte[] counter)
    {
        int blockSize = _cipher.BlockSize / 8;
        byte[] ctr = (byte[])counter.Clone();
        Span<byte> ks = stackalloc byte[blockSize];

        try
        {
            for (int offset = 0; offset < input.Length; offset += blockSize)
            {
                _cipher.Encrypt(ctr, ks);

                for (int i = ctr.Length - 1; i >= 0; i--)
                    if (++ctr[i] != 0) break;

                int len = Math.Min(blockSize, input.Length - offset);
                for (int i = 0; i < len; i++)
                    output[offset + i] = (byte)(input[offset + i] ^ ks[i]);
            }
        }
        finally
        {
            CryptographyHelper.Clear(ks);
            CryptographyHelper.Clear(ctr);
        }
    }

    /// <summary>
    /// Doubles <paramref name="x" /> in-place in GF(2^128) with big-endian bit order and polynomial x^128 + x^7 + x^2 +
    /// x + 1.
    /// </summary>
    /// <param name="x">The block doubled in place.</param>
    private static void Dbl(byte[] x)
    {
        bool msb = (x[0] & 0x80) != 0;

        for (int i = 0; i < x.Length - 1; i++)
            x[i] = (byte)((x[i] << 1) | (x[i + 1] >> 7));

        x[^1] <<= 1;

        if (msb)
            x[^1] ^= 0x87;
    }

    /// <summary>
    /// XORs two equally-sized input spans into <paramref name="result" />.
    /// </summary>
    /// <param name="a">The first input span.</param>
    /// <param name="b">The second input span.</param>
    /// <param name="result">The span that receives the XOR of <paramref name="a" /> and <paramref name="b" />.</param>
    private static void Xor(ReadOnlySpan<byte> a, ReadOnlySpan<byte> b, Span<byte> result)
    {
        for (int i = 0; i < result.Length; i++)
            result[i] = (byte)(a[i] ^ b[i]);
    }

    /// <summary>
    /// Throws an <see cref="ObjectDisposedException" /> if the algorithm instance has been disposed.
    /// </summary>
    /// <exception cref="ObjectDisposedException">
    /// Thrown when any public method or property is accessed after the instance has been disposed.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ThrowIfDisposed() =>
        ObjectDisposedException.ThrowIf(_disposed, this);
}
