// ---------------------------------------------------------------------------------------------------------------
// <copyright file="EaxModeTransform.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Security.Cryptography;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Applies EAX mode to an underlying <see cref="IBlockCipher" />, providing two-pass authenticated encryption with
/// associated data (AEAD) per Bellare, Rogaway and Wagner (FSE 2004).
/// </summary>
/// <remarks>
/// <para>
/// <img src="../images/diagrams/aead-mode.svg" alt="Generic AEAD data flow - EAX instantiates the top pipeline as CTR mode and the bottom pipeline as three OMAC invocations over the nonce, associated data, and ciphertext whose outputs are XOR-combined to form the tag."/>
/// </para>
/// <para>
/// EAX is the <b>CTR + OMAC(N ‖ A ‖ C)</b> instantiation of the generic AEAD shape above. Three independent OMAC
/// invocations are performed with a single-byte tweak <c>t ∈ {0, 1, 2}</c> selecting the input kind:
/// <list type="bullet">
/// <item>
/// <description><c>N' = OMAC_K^0(nonce)</c> - authenticates the nonce and seeds the CTR counter.</description>
/// </item>
/// <item>
/// <description><c>H' = OMAC_K^1(associatedData)</c> - authenticates the AAD.</description>
/// </item>
/// <item>
/// <description><c>C' = OMAC_K^2(ciphertext)</c> - authenticates the ciphertext.</description>
/// </item>
/// </list>
/// The authentication tag is <c>T = N' ⊕ H' ⊕ C'</c>, and the keystream is generated by encrypting successive
/// big-endian increments of <c>N'</c> with the underlying block cipher.
/// </para>
/// <para>
/// <c>OMAC_K^t(M)</c> is defined as <c>CMAC_K([t]_n ‖ M)</c>, where <c>[t]_n</c> is the integer <c>t</c> encoded as a
/// full <c>BlockSize</c>-byte big-endian block. All three invocations therefore share the same CMAC subkeys K₁ =
/// dbl(E(0ⁿ)) and K₂ = dbl(K₁), derived from the cipher once per instance.
/// </para>
/// <para>
/// The tag size is fixed at 16 bytes (the full OMAC output). The IV is the raw nonce: the class computes <c>N'</c>
/// internally. Ciphertext is output as <c>C ‖ T</c> (ciphertext then tag), consistent with the
/// <see cref="IAeadBlockCipherModeTransform" /> convention.
/// </para>
/// <para>
/// <strong>When to use EAX.</strong> Pick EAX when an unencumbered, two-pass AEAD with a flexible nonce length (the
/// OMAC-derived <c>N'</c> means EAX accepts nonces up to the cipher block size) is wanted - some embedded protocols and
/// historical industry standards require it. EAX is roughly half the throughput of <see cref="GcmModeTransform" /> on
/// commodity hardware but does not depend on Galois-field arithmetic and has no patent concerns. For new
/// general-purpose AEAD prefer GCM; for nonce-misuse resistance prefer <see cref="GcmSivModeTransform" /> or
/// <see cref="SivModeTransform" />; for single-pass AEAD without GCM's catastrophic-on-reuse profile prefer
/// <see cref="OcbModeTransform" />.
/// </para>
/// <para>
/// <strong>Nonce uniqueness is required.</strong> EAX is not nonce-misuse resistant. Two messages encrypted under the
/// same <c>(key, nonce)</c> share the same <c>N'</c> seed, so they share the same CTR keystream and an attacker can
/// recover <c>P1 XOR P2</c>; the per-message OMAC tag inputs also overlap, weakening authentication. Callers must
/// guarantee that every <c>(key, nonce)</c> pair is used at most once - either via a deterministic per-message counter
/// or a fresh random nonce drawn from a CSPRNG. If nonce uniqueness cannot be guaranteed, prefer
/// <see cref="GcmSivModeTransform" /> or <see cref="SivModeTransform" />.
/// </para>
/// </remarks>
/// <example>
/// <code language="csharp">
///<![CDATA[
/// using System.Security.Cryptography;
/// using Bodu.Security.Cryptography;
/// using Bodu.Security.Cryptography.Extensions;
///
/// using IBlockCipher cipher = new AesBlockCipher(key);
/// byte[] nonce = RandomNumberGenerator.GetBytes(cipher.BlockSize / 8); // unique per message
/// using IAeadBlockCipherModeTransform eax = new EaxModeTransform(cipher, nonce);
/// byte[] sealed_ = eax.Encrypt(plaintext, associatedData: header);
/// using IAeadBlockCipherModeTransform dec = new EaxModeTransform(cipher, nonce);
/// byte[] recovered = dec.Decrypt(sealed_, associatedData: header);
///]]>
/// </code>
/// </example>
/// <seealso href="../guides/cryptography/aead-modes.html#eax---two-pass-fse-2004">EAX walk-through in the AEAD-modes
/// guide</seealso> <seealso cref="AesBlockCipher"/>
/// <seealso cref="Bodu.Security.Cryptography.Extensions.AeadBlockCipherModeTransformExtensions"/>
public sealed class EaxModeTransform
    : IAeadBlockCipherModeTransform, IDisposable
{
    /// <summary>The default EAX authentication-tag size, in bits.</summary>
    private const int DefaultTagSizeBits = 128;

    /// <summary>The default EAX authentication-tag size, in bytes.</summary>
    private const int DefaultTagSize = DefaultTagSizeBits / 8;

    /// <summary>The block size, in bytes, of the cipher, of OMAC, and of a counter block.</summary>
    private const int BlockBytes = 16;

    /// <summary>The underlying block cipher used for both OMAC and the CTR keystream.</summary>
    private readonly IBlockCipher _cipher;

    /// <summary>The raw user-supplied nonce, held as a defensive clone.</summary>
    private readonly byte[] _nonce;

    /// <summary>The buffered associated authenticated data, or <see langword="null" /> until processed.</summary>
    private byte[]? _aad;

    /// <summary>Indicates whether the associated data has been processed.</summary>
    private bool _aadProcessed;

    /// <summary>Indicates whether this transform has already completed an encrypt or decrypt operation.</summary>
    private bool _completed;

    /// <summary>Indicates whether this instance has been disposed.</summary>
    private bool _disposed;

    /// <summary>
    /// Initializes a new instance of the <see cref="EaxModeTransform" /> class.
    /// </summary>
    /// <param name="cipher">The block cipher used for both OMAC and the CTR keystream.</param>
    /// <param name="iv">
    /// The nonce <c>N</c>. Must equal the cipher block size. A defensive copy is taken; the caller's array is not
    /// modified.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="cipher" /> or <paramref name="iv" /> is <see langword="null" />.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="iv" /> length does not equal the cipher block size.
    /// </exception>
    public EaxModeTransform(IBlockCipher cipher, byte[] iv)
    {
        ThrowHelper.ThrowIfNull(cipher);
        CryptographyThrowHelper.ThrowIfIvLengthInvalid(iv, cipher.BlockSize);

        _cipher = cipher;

        _nonce = (byte[])iv.Clone();
    }

    /// <inheritdoc />
    /// <value>Length of the EAX authentication tag is 128 bits (16 bytes).</value>
    public int TagSize => DefaultTagSizeBits;

    /// <inheritdoc />
    public void ProcessAssociatedData(ReadOnlySpan<byte> associatedData)
    {
        ThrowIfDisposed();

        CryptographyThrowHelper.ThrowIfAssociatedDataAlreadyProcessed(_aadProcessed);

        _aad = associatedData.ToArray();
        _aadProcessed = true;
    }

    /// <inheritdoc />
    public int Encrypt(ReadOnlySpan<byte> plaintext, Span<byte> output)
    {
        ThrowIfDisposed();
        ThrowIfCompleted();

        int required = plaintext.Length + DefaultTagSize;
        ThrowHelper.ThrowIfSpanLengthIsInsufficient(output, required);

        EnsureAadProcessed();

        // Scratch: the CMAC subkeys K1 and K2, the CMAC state and held-back block, then N', H', and C'.
        Span<byte> scratch = stackalloc byte[7 * BlockBytes];

        try
        {
            Span<byte> nPrime = scratch.Slice(4 * BlockBytes, BlockBytes);
            Span<byte> hPrime = scratch.Slice(5 * BlockBytes, BlockBytes);
            Span<byte> cPrime = scratch.Slice(6 * BlockBytes, BlockBytes);
            Cmac.DeriveSubkeys(_cipher, scratch[..BlockBytes], scratch.Slice(BlockBytes, BlockBytes));

            Omac(0, _nonce, scratch, nPrime);
            Omac(1, _aad!, scratch, hPrime);

            // CTR-encrypt the plaintext from N', then authenticate the ciphertext.
            Span<byte> ciphertext = output[..plaintext.Length];
            CounterKeystream.TransformBigEndian128(_cipher, nPrime, plaintext, ciphertext);
            Omac(2, ciphertext, scratch, cPrime);

            // Tag = N' XOR H' XOR C'.
            Span<byte> tag = output.Slice(plaintext.Length, DefaultTagSize);
            CryptographyHelper.Xor(nPrime, hPrime, tag);
            CryptographyHelper.Xor(tag, cPrime, tag);

            return required;
        }
        finally
        {
            CryptographyHelper.Clear(scratch);
            _completed = true;
        }
    }

    /// <inheritdoc />
    /// <remarks>
    /// <strong>Authentication pattern: verify-before-release.</strong> The OMAC-derived tag is recomputed and compared
    /// in constant time before the CTR decryption stream is applied to <paramref name="output" />; no plaintext byte is
    /// ever written when authentication fails. If the underlying cipher throws mid-transform, the plaintext region of
    /// <paramref name="output" /> is zeroed before the exception propagates. See
    /// <see cref="IAeadBlockCipherModeTransform.Decrypt" /> for the library-wide failure contract.
    /// </remarks>
    public int Decrypt(ReadOnlySpan<byte> ciphertextWithTag, Span<byte> output)
    {
        ThrowIfDisposed();
        ThrowIfCompleted();

        CryptographyThrowHelper.ThrowIfCiphertextTooShort(ciphertextWithTag, DefaultTagSize);

        int plaintextLength = ciphertextWithTag.Length - DefaultTagSize;
        ThrowHelper.ThrowIfSpanLengthIsInsufficient(output, plaintextLength);

        EnsureAadProcessed();

        ReadOnlySpan<byte> ciphertext = ciphertextWithTag[..plaintextLength];
        ReadOnlySpan<byte> receivedTag = ciphertextWithTag[plaintextLength..];

        // Scratch: the CMAC subkeys K1 and K2, the CMAC state and held-back block, then N', H', C', and the expected tag.
        Span<byte> scratch = stackalloc byte[8 * BlockBytes];

        try
        {
            Span<byte> nPrime = scratch.Slice(4 * BlockBytes, BlockBytes);
            Span<byte> hPrime = scratch.Slice(5 * BlockBytes, BlockBytes);
            Span<byte> cPrime = scratch.Slice(6 * BlockBytes, BlockBytes);
            Span<byte> expectedTag = scratch.Slice(7 * BlockBytes, BlockBytes);
            Cmac.DeriveSubkeys(_cipher, scratch[..BlockBytes], scratch.Slice(BlockBytes, BlockBytes));

            Omac(0, _nonce, scratch, nPrime);
            Omac(1, _aad!, scratch, hPrime);
            Omac(2, ciphertext, scratch, cPrime);

            CryptographyHelper.Xor(nPrime, hPrime, expectedTag);
            CryptographyHelper.Xor(expectedTag, cPrime, expectedTag);

            // Constant-time tag comparison; throw before emitting any plaintext. On failure, also
            // zero any data the caller may have pre-seeded into the output buffer - defense-in-depth
            // aligned with AsconAead128.Decrypt.
            if (!CryptographicOperations.FixedTimeEquals(expectedTag, receivedTag))
            {
                CryptographyHelper.Clear(output[..plaintextLength]);
                throw new CryptographicException(CryptoResourceStrings.Crypt_Invalid_AuthenticationTagMismatch);
            }

            CounterKeystream.TransformBigEndian128(_cipher, nPrime, ciphertext, output[..plaintextLength]);

            return plaintextLength;
        }
        catch
        {
            // Zero the plaintext region on any failure - a tag mismatch or a fault from the underlying
            // cipher mid-transform - so partially written plaintext or keystream bytes never leak.
            CryptographyHelper.Clear(output[..plaintextLength]);
            throw;
        }
        finally
        {
            CryptographyHelper.Clear(scratch);
            _completed = true;
        }
    }

    /// <summary>
    /// Throws <see cref="InvalidOperationException" /> if this transform has already encrypted or decrypted a message.
    /// EAX transforms are single-use; create a fresh instance per message.
    /// </summary>
    private void ThrowIfCompleted() =>
        CryptographyThrowHelper.ThrowIfAlreadyCompleted(_completed);

    /// <summary>
    /// Releases the resources used by this instance and clears retained nonce and associated-data state from memory.
    /// </summary>
    /// <remarks>
    /// The supplied <see cref="IBlockCipher" /> is not disposed by this type. Ownership remains with the caller.
    /// </remarks>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Releases the resources used by this instance.
    /// </summary>
    /// <param name="disposing">
    /// <see langword="true" /> to release managed resources; <see langword="false" /> to release unmanaged resources
    /// only.
    /// </param>
    private void Dispose(bool disposing)
    {
        if (_disposed)
            return;

        if (disposing)
        {
            CryptographyHelper.Clear(_nonce);
            CryptographyHelper.ClearAndNullify(ref _aad);

            _aadProcessed = false;
        }

        _disposed = true;
    }

    // ── Private helpers ────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Ensures the associated-data contribution has been initialized before payload processing.
    /// </summary>
    private void EnsureAadProcessed()
    {
        if (!_aadProcessed)
        {
            _aad = [];
            _aadProcessed = true;
        }
    }

    /// <summary>
    /// Computes <c>OMAC_K^t(m) = CMAC_K([t]_n ‖ m)</c>, where <c>[t]_n</c> is the integer <paramref name="t" /> encoded
    /// as a full-block big-endian prefix, without copying <paramref name="m" />.
    /// </summary>
    /// <param name="t">The single-byte tweak that selects the OMAC domain.</param>
    /// <param name="m">The message bytes to authenticate.</param>
    /// <param name="scratch">
    /// Scratch whose first two blocks hold the subkeys <c>K1</c> and <c>K2</c> and whose next two receive the CMAC
    /// state and held-back block.
    /// </param>
    /// <param name="mac">Receives the OMAC tag.</param>
    private void Omac(byte t, ReadOnlySpan<byte> m, Span<byte> scratch, Span<byte> mac)
    {
        Span<byte> prefix = stackalloc byte[BlockBytes];
        prefix.Clear();
        prefix[^1] = t;

        var cmac = new Cmac(
            _cipher,
            scratch[..BlockBytes],
            scratch.Slice(BlockBytes, BlockBytes),
            scratch.Slice(2 * BlockBytes, BlockBytes),
            scratch.Slice(3 * BlockBytes, BlockBytes));
        cmac.Append(prefix);
        cmac.Append(m);
        cmac.Finish(mac);
    }

    /// <summary>
    /// Throws an <see cref="ObjectDisposedException" /> if the algorithm instance has been disposed.
    /// </summary>
    /// <exception cref="ObjectDisposedException">
    /// Thrown when any public method or property is accessed after the instance has been disposed.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ThrowIfDisposed() =>
        ObjectDisposedException.ThrowIf(_disposed, this);
}
