// ---------------------------------------------------------------------------------------------------------------
// <copyright file="Scrypt.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Computes the scrypt sequential memory-hard password-hashing and key-derivation function defined by RFC 7914. This
/// class cannot be inherited.
/// </summary>
/// <remarks>
/// <para>
/// scrypt derives a key from a password and salt while deliberately requiring a large amount of memory, raising the
/// cost of large-scale custom-hardware attacks. An instance binds a set of cost <see cref="ScryptParameters" /> once,
/// then derives keys or PHC password hashes. The static one-shot methods are provided for convenience.
/// </para>
/// <para>
/// By default a derivation runs its <see cref="ScryptParameters.Parallelization" /> units one after another on the
/// calling thread. <see cref="MaxDegreeOfParallelism" /> lets them run at once instead, each with a <c>V</c> of its
/// own, so the time falls and the memory rises with the threads; the derived key never depends on them.
/// </para>
/// <para>
/// The working memory - <c>V</c>, <c>128 · N · r</c> bytes - is held in native memory and reused across derivations, in
/// the same reserve as Argon2's matrix, so a derivation neither allocates it on the collected heap nor waits for it to
/// be zeroed. Up to one buffer per processor stays reserved - cleared - for up to thirty seconds after the last
/// derivation; the <c>Bodu.Security.Cryptography.Argon2.DisableMatrixReuse</c> <see cref="AppContext" /> switch
/// releases each buffer as soon as its derivation ends instead. Every buffer holding a password-derived value is
/// cleared before it is released; values the JIT keeps in registers or its own stack slots are beyond the library's
/// reach.
/// </para>
/// <para>
/// This implementation is not independently audited and offers best-effort, not guaranteed, side-channel resistance.
/// </para>
/// </remarks>
public sealed class Scrypt
{
    /// <summary>The salt length, in bytes, generated by the parameterless-salt <see cref="Hash(ReadOnlySpan{byte}, int)" /> overload.</summary>
    private const int GeneratedSaltLength = 16;

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters.
    /// </summary>
    /// <param name="parameters">The cost parameters governing the derivation.</param>
    /// <exception cref="ArgumentNullException"><paramref name="parameters" /> is <see langword="null" />.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter in <paramref name="parameters" /> falls outside the range permitted by RFC 7914.
    /// </exception>
    /// <remarks>
    /// Every derivation runs on the calling thread; see <see cref="MaxDegreeOfParallelism" />.
    /// </remarks>
    public Scrypt(ScryptParameters parameters)
        : this(parameters, maxDegreeOfParallelism: 1)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters and bound on
    /// the threads each derivation may use.
    /// </summary>
    /// <param name="parameters">The cost parameters governing the derivation.</param>
    /// <param name="maxDegreeOfParallelism">
    /// The greatest number of threads one derivation may use, the calling thread included; <c>-1</c> for up to one per
    /// processor.
    /// </param>
    /// <exception cref="ArgumentNullException"><paramref name="parameters" /> is <see langword="null" />.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter in <paramref name="parameters" /> falls outside the range permitted by RFC 7914, or
    /// <paramref name="maxDegreeOfParallelism" /> is zero or less than <c>-1</c>.
    /// </exception>
    /// <remarks>
    /// Each unit that runs at once holds its own <c>V</c> of <c>128 · N · r</c> bytes, so a derivation on several
    /// threads needs that much memory for each of them; see <see cref="MaxDegreeOfParallelism" />.
    /// </remarks>
    public Scrypt(ScryptParameters parameters, int maxDegreeOfParallelism)
    {
        ThrowHelper.ThrowIfNull(parameters);
        CryptographyThrowHelper.ThrowIfDegreeOfParallelismInvalid(maxDegreeOfParallelism);
        parameters.Validate();

        Parameters = parameters;
        MaxDegreeOfParallelism = maxDegreeOfParallelism;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters.
    /// </summary>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c> - a power of two greater than one.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter falls outside the range permitted by RFC 7914.
    /// </exception>
    /// <remarks>
    /// Every derivation runs on the calling thread; see <see cref="MaxDegreeOfParallelism" />.
    /// </remarks>
    public Scrypt(int costN, int blockSizeR, int parallelization)
        : this(costN, blockSizeR, parallelization, maxDegreeOfParallelism: 1)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters and bound on
    /// the threads each derivation may use.
    /// </summary>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c> - a power of two greater than one.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="maxDegreeOfParallelism">
    /// The greatest number of threads one derivation may use, the calling thread included; <c>-1</c> for up to one per
    /// processor.
    /// </param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter falls outside the range permitted by RFC 7914, or <paramref name="maxDegreeOfParallelism" /> is
    /// zero or less than <c>-1</c>.
    /// </exception>
    /// <remarks>
    /// Each unit that runs at once holds its own <c>V</c> of <c>128 · N · r</c> bytes, so a derivation on several
    /// threads needs that much memory for each of them; see <see cref="MaxDegreeOfParallelism" />.
    /// </remarks>
    public Scrypt(int costN, int blockSizeR, int parallelization, int maxDegreeOfParallelism)
        : this(new ScryptParameters { CostN = costN, BlockSizeR = blockSizeR, Parallelization = parallelization }, maxDegreeOfParallelism)
    {
    }

    /// <summary>
    /// Gets the cost parameters bound to this instance.
    /// </summary>
    /// <value>The <see cref="ScryptParameters" /> supplied at construction.</value>
    public ScryptParameters Parameters { get; }

    /// <summary>
    /// Gets the greatest number of threads one derivation by this instance may use, the calling thread included.
    /// </summary>
    /// <value>
    /// <c>1</c>, the default, runs a derivation's <see cref="ScryptParameters.Parallelization" /> units one after
    /// another on the calling thread. A larger value, or <c>-1</c> for up to one thread per processor, lets them run at
    /// once, on no more threads than there are units. The derived key never depends on this value.
    /// </value>
    /// <remarks>
    /// <para>
    /// Unlike Argon2's lanes, which share one memory matrix, each scrypt unit that runs at once holds its own <c>V</c>
    /// of <c>128 · N · r</c> bytes, so a derivation on <c>t</c> threads needs <c>t</c> times the memory of one on the
    /// calling thread. That is why the default is <c>1</c>: a service that verifies many passwords at once already
    /// keeps every core busy, and would only multiply its memory.
    /// </para>
    /// <para>
    /// A derivation keeps its working memory within the 2 GiB ceiling on a single <c>V</c> however high the bound,
    /// running on fewer threads when its units are large, so an encoded hash from an untrusted source cannot multiply
    /// the memory a verification takes. It stays on the calling thread when its units are small - under 1 MiB of
    /// <c>V</c> each - where handing them to other threads costs more than it saves.
    /// </para>
    /// </remarks>
    public int MaxDegreeOfParallelism { get; }

    /// <summary>
    /// Derives a key of the requested length from the supplied password and salt.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="length">The derived-key length, in bytes.</param>
    /// <returns>The derived key.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    public byte[] GetBytes(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int length)
    {
        ThrowIfInvalidLength(length);

        byte[] output = new byte[length];
        ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, output, MaxDegreeOfParallelism);
        return output;
    }

    /// <summary>
    /// Derives a key into the supplied destination buffer.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="destination">The buffer to receive the derived key; its length is the derived-key length.</param>
    /// <exception cref="ArgumentException"><paramref name="destination" /> is empty.</exception>
    public void DeriveKey(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, Span<byte> destination)
    {
        ThrowIfInvalidLength(destination.Length);

        ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, destination, MaxDegreeOfParallelism);
    }

    /// <summary>
    /// Derives a hash from the password and a freshly generated random 16-byte salt and returns it as a PHC
    /// encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string, including the generated salt.</returns>
    public string Hash(ReadOnlySpan<byte> password, int length)
    {
        Span<byte> salt = stackalloc byte[GeneratedSaltLength];
        RandomNumberGenerator.Fill(salt);
        return Hash(password, salt, length);
    }

    /// <summary>
    /// Derives a hash from the password and the supplied salt and returns it as a PHC encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="salt">The salt to embed in the encoded string.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    public string Hash(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int length)
    {
        ThrowIfInvalidLength(length);

        byte[] hash = new byte[length];

        try
        {
            ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, hash, MaxDegreeOfParallelism);

            return Encode(Parameters, salt, hash);
        }
        finally
        {
            CryptographyHelper.Clear(hash);
        }
    }

    /// <summary>
    /// Derives a key from a password and salt using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="length">The derived-key length, in bytes.</param>
    /// <returns>The derived key.</returns>
    public static byte[] DeriveKey(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, int length) =>
        new Scrypt(costN, blockSizeR, parallelization).GetBytes(password, salt, length);

    /// <summary>
    /// Derives a key into the supplied destination buffer using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="destination">The buffer to receive the derived key.</param>
    public static void DeriveKey(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, Span<byte> destination) =>
        new Scrypt(costN, blockSizeR, parallelization).DeriveKey(password, salt, destination);

    /// <summary>
    /// Derives a key in a single call from a pinned, disposable password holder and a typed salt.
    /// </summary>
    /// <param name="password">The password material to derive from. Must not be <see langword="null" />.</param>
    /// <param name="salt">The salt, typically produced by <see cref="Salt.Random(int)" />.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="length">The derived-key length, in bytes.</param>
    /// <returns>The derived key.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="password" /> is <see langword="null" />.</exception>
    /// <exception cref="ObjectDisposedException"><paramref name="password" /> has been disposed.</exception>
    /// <remarks>
    /// Convenience overload over the span form for callers using the <see cref="SecretBytes" /> and <see cref="Salt" />
    /// value types, which keep password material pinned and zeroed on disposal and keep salts distinct from keys and
    /// nonces in calling code.
    /// </remarks>
    public static byte[] DeriveKey(
        SecretBytes password, Salt salt, int costN, int blockSizeR, int parallelization, int length)
    {
        ThrowHelper.ThrowIfNull(password);

        return DeriveKey(password.AsSpan(), salt.AsSpan(), costN, blockSizeR, parallelization, length);
    }

    /// <summary>
    /// Derives a hash and returns it as a PHC encoded-hash string using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="salt">The salt to embed in the encoded string.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string.</returns>
    public static string Hash(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, int length) =>
        new Scrypt(costN, blockSizeR, parallelization).Hash(password, salt, length);

    /// <summary>
    /// Verifies a password against a scrypt PHC encoded-hash string.
    /// </summary>
    /// <param name="encoded">
    /// The PHC encoded-hash string produced by <see cref="Hash(ReadOnlySpan{byte}, ReadOnlySpan{byte}, int)" />.
    /// </param>
    /// <param name="password">The password to verify.</param>
    /// <returns>
    /// <see langword="true" /> if the password matches the encoded hash; otherwise, <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="encoded" /> is <see langword="null" />.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// The cost parameters in <paramref name="encoded" /> fall outside the range permitted by RFC 7914 or the memory
    /// ceiling.
    /// </exception>
    /// <exception cref="FormatException">
    /// <paramref name="encoded" /> is not a well-formed scrypt PHC string.
    /// </exception>
    /// <remarks>
    /// The derivation runs on the calling thread.
    /// </remarks>
    public static bool Verify(string encoded, ReadOnlySpan<byte> password) =>
        Verify(encoded, password, maxDegreeOfParallelism: 1);

    /// <summary>
    /// Verifies a password against a scrypt PHC encoded-hash string, with a bound on the threads the derivation may
    /// use.
    /// </summary>
    /// <param name="encoded">
    /// The PHC encoded-hash string produced by <see cref="Hash(ReadOnlySpan{byte}, ReadOnlySpan{byte}, int)" />.
    /// </param>
    /// <param name="password">The password to verify.</param>
    /// <param name="maxDegreeOfParallelism">
    /// The greatest number of threads the derivation may use, the calling thread included; <c>-1</c> for up to one per
    /// processor.
    /// </param>
    /// <returns>
    /// <see langword="true" /> if the password matches the encoded hash; otherwise, <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="encoded" /> is <see langword="null" />.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <paramref name="maxDegreeOfParallelism" /> is zero or less than <c>-1</c>, or the cost parameters in
    /// <paramref name="encoded" /> fall outside the range permitted by RFC 7914 or the memory ceiling.
    /// </exception>
    /// <exception cref="FormatException">
    /// <paramref name="encoded" /> is not a well-formed scrypt PHC string.
    /// </exception>
    /// <remarks>
    /// The bound lets a hash with several units (<c>p</c> greater than 1) verify faster at the cost of memory; the
    /// result never depends on it. The working memory stays within the 2 GiB ceiling on a single <c>V</c> whatever the
    /// encoded hash asks for; see <see cref="MaxDegreeOfParallelism" />.
    /// </remarks>
    public static bool Verify(string encoded, ReadOnlySpan<byte> password, int maxDegreeOfParallelism)
    {
        ThrowHelper.ThrowIfNull(encoded);
        CryptographyThrowHelper.ThrowIfDegreeOfParallelismInvalid(maxDegreeOfParallelism);

        (int costN, int blockSizeR, int parallelization, byte[]? salt, byte[]? hash) = Decode(encoded);

        byte[]? computed = null;

        try
        {
            // Validate the decoded cost parameters before deriving, so an untrusted encoded hash cannot drive an
            // unbounded (multi-gigabyte) allocation through the memory-hard core.
            new ScryptParameters { CostN = costN, BlockSizeR = blockSizeR, Parallelization = parallelization }.Validate();

            computed = new byte[hash.Length];
            ScryptCore.DeriveKey(password, salt, costN, blockSizeR, parallelization, computed, maxDegreeOfParallelism);

            return CryptographicOperations.FixedTimeEquals(computed, hash);
        }
        finally
        {
            CryptographyHelper.Clear(computed);
            CryptographyHelper.Clear(hash);
            CryptographyHelper.Clear(salt);
        }
    }

    /// <summary>
    /// Throws an <see cref="ArgumentOutOfRangeException" /> if the requested output length is less than 1.
    /// </summary>
    /// <param name="length">The requested output length, in bytes.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    private static void ThrowIfInvalidLength(int length)
    {
        // The RFC 7914 upper bound of (2^32 - 1) * 32 always exceeds Array.MaxLength, so only the lower bound is
        // meaningful for a managed array.
        if (length < 1)
        {
            throw new ArgumentOutOfRangeException(
                nameof(length),
                length,
                string.Format(CultureInfo.CurrentCulture, CryptoResourceStrings.Arg_OutOfRange_ScryptOutputLength, (long)uint.MaxValue * 32));
        }
    }

    /// <summary>
    /// Formats a scrypt PHC encoded-hash string.
    /// </summary>
    /// <param name="p">The scrypt parameters to encode.</param>
    /// <param name="salt">The salt bytes.</param>
    /// <param name="hash">The derived hash bytes.</param>
    /// <returns>The scrypt PHC encoded-hash string.</returns>
    private static string Encode(ScryptParameters p, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> hash)
    {
        int logN = BitOperations.Log2((uint)p.CostN);

        var sb = new StringBuilder();
        sb.Append("$scrypt$ln=").Append(logN.ToString(CultureInfo.InvariantCulture))
          .Append(",r=").Append(p.BlockSizeR.ToString(CultureInfo.InvariantCulture))
          .Append(",p=").Append(p.Parallelization.ToString(CultureInfo.InvariantCulture));
        sb.Append('$').Append(PhcString.EncodeBase64(salt));
        sb.Append('$').Append(PhcString.EncodeBase64(hash));
        return sb.ToString();
    }

    /// <summary>
    /// Parses a scrypt PHC encoded-hash string into its constituent fields.
    /// </summary>
    /// <param name="encoded">The scrypt PHC encoded-hash string to parse.</param>
    /// <returns>The cost parameters, salt, and hash parsed from <paramref name="encoded" />.</returns>
    /// <exception cref="FormatException"><paramref name="encoded" /> is not a valid scrypt PHC string.</exception>
    private static (int CostN, int BlockSizeR, int Parallelization, byte[] Salt, byte[] Hash) Decode(string encoded)
    {
        string[] fields = PhcString.SplitFields(encoded);

        // Expect: "", scrypt, ln=..,r=..,p=.., salt, hash
        if (fields.Length != 5 || fields[1] != "scrypt")
            throw PhcString.Invalid();

        int? logN = null, blockSizeR = null, parallelization = null;
        foreach (string part in fields[2].Split(','))
        {
            int eq = part.IndexOf('=', StringComparison.Ordinal);
            if (eq <= 0)
                throw PhcString.Invalid();

            string key = part[..eq];
            string value = part[(eq + 1)..];

            switch (key)
            {
                case "ln": logN = ParseInt(value); break;
                case "r": blockSizeR = ParseInt(value); break;
                case "p": parallelization = ParseInt(value); break;
                default: throw PhcString.Invalid();
            }
        }

        if (logN is null or < 1 or > 30 || blockSizeR is null || parallelization is null)
            throw PhcString.Invalid();

        byte[] salt = PhcString.DecodeBase64(fields[3]);
        byte[] hash = PhcString.DecodeBase64(fields[4]);

        return (1 << logN.Value, blockSizeR.Value, parallelization.Value, salt, hash);
    }

    /// <summary>
    /// Parses a non-negative decimal integer, throwing a <see cref="FormatException" /> on failure.
    /// </summary>
    /// <param name="value">The text to parse.</param>
    /// <returns>The parsed non-negative integer.</returns>
    private static int ParseInt(string value) =>
        int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out int result)
            ? result
            : throw PhcString.Invalid();
}
