// ---------------------------------------------------------------------------------------------------------------
// <copyright file="Scrypt.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;

namespace Bodu.Security.Cryptography;

/// <summary>
/// Computes the scrypt sequential memory-hard password-hashing and key-derivation function defined by RFC 7914. This
/// class cannot be inherited.
/// </summary>
/// <remarks>
/// <para>
/// scrypt derives a key from a password and salt while deliberately requiring a large amount of memory, raising the
/// cost of large-scale custom-hardware attacks. An instance binds a set of cost <see cref="ScryptParameters" /> once,
/// then derives keys or PHC password hashes. The static one-shot methods are provided for convenience.
/// </para>
/// <para>
/// This implementation is not independently audited and offers best-effort, not guaranteed, side-channel resistance.
/// </para>
/// </remarks>
public sealed class Scrypt
{
    /// <summary>
    /// The salt length, in bytes, generated by the parameterless-salt <see cref="Hash(ReadOnlySpan{byte}, int)" />
    /// overload.
    /// </summary>
    private const int GeneratedSaltLength = 16;

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters.
    /// </summary>
    /// <param name="parameters">The cost parameters governing the derivation.</param>
    /// <exception cref="ArgumentNullException"><paramref name="parameters" /> is <see langword="null" />.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter in <paramref name="parameters" /> falls outside the range permitted by RFC 7914.
    /// </exception>
    public Scrypt(ScryptParameters parameters)
    {
        ThrowHelper.ThrowIfNull(parameters);
        parameters.Validate();

        Parameters = parameters;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Scrypt" /> class with the specified cost parameters.
    /// </summary>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c> — a power of two greater than one.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// A cost parameter falls outside the range permitted by RFC 7914.
    /// </exception>
    public Scrypt(int costN, int blockSizeR, int parallelization)
        : this(new ScryptParameters { CostN = costN, BlockSizeR = blockSizeR, Parallelization = parallelization })
    { }

    /// <summary>
    /// Gets the cost parameters bound to this instance.
    /// </summary>
    /// <returns>The <see cref="ScryptParameters" /> supplied at construction.</returns>
    public ScryptParameters Parameters { get; }

    /// <summary>
    /// Derives a key of the requested length from the supplied password and salt.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="length">The derived-key length, in bytes.</param>
    /// <returns>The derived key.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    public byte[] GetBytes(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int length)
    {
        ThrowIfInvalidLength(length);

        byte[] output = new byte[length];
        ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, output);
        return output;
    }

    /// <summary>
    /// Derives a key into the supplied destination buffer.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="destination">The buffer to receive the derived key; its length is the derived-key length.</param>
    /// <exception cref="ArgumentException"><paramref name="destination" /> is empty.</exception>
    public void DeriveKey(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, Span<byte> destination)
    {
        ThrowIfInvalidLength(destination.Length);

        ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, destination);
    }

    /// <summary>
    /// Derives a hash from the password and a freshly generated random 16-byte salt and returns it as a PHC
    /// encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string, including the generated salt.</returns>
    public string Hash(ReadOnlySpan<byte> password, int length)
    {
        Span<byte> salt = stackalloc byte[GeneratedSaltLength];
        RandomNumberGenerator.Fill(salt);
        return Hash(password, salt, length);
    }

    /// <summary>
    /// Derives a hash from the password and the supplied salt and returns it as a PHC encoded-hash string.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="salt">The salt to embed in the encoded string.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    public string Hash(ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int length)
    {
        ThrowIfInvalidLength(length);

        byte[] hash = new byte[length];
        ScryptCore.DeriveKey(password, salt, Parameters.CostN, Parameters.BlockSizeR, Parameters.Parallelization, hash);

        string encoded = Encode(Parameters, salt, hash);
        CryptographyHelper.Clear(hash);
        return encoded;
    }

    /// <summary>
    /// Derives a key from a password and salt using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="length">The derived-key length, in bytes.</param>
    /// <returns>The derived key.</returns>
    public static byte[] DeriveKey(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, int length) =>
        new Scrypt(costN, blockSizeR, parallelization).GetBytes(password, salt, length);

    /// <summary>
    /// Derives a key into the supplied destination buffer using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to derive from.</param>
    /// <param name="salt">The salt.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="destination">The buffer to receive the derived key.</param>
    public static void DeriveKey(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, Span<byte> destination) =>
        new Scrypt(costN, blockSizeR, parallelization).DeriveKey(password, salt, destination);

    /// <summary>
    /// Derives a hash and returns it as a PHC encoded-hash string using the supplied parameters in a single call.
    /// </summary>
    /// <param name="password">The password to hash.</param>
    /// <param name="salt">The salt to embed in the encoded string.</param>
    /// <param name="costN">The CPU/memory cost parameter <c>N</c>.</param>
    /// <param name="blockSizeR">The block-size parameter <c>r</c>.</param>
    /// <param name="parallelization">The parallelization parameter <c>p</c>.</param>
    /// <param name="length">The hash length, in bytes.</param>
    /// <returns>The PHC encoded-hash string.</returns>
    public static string Hash(
        ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt, int costN, int blockSizeR, int parallelization, int length) =>
        new Scrypt(costN, blockSizeR, parallelization).Hash(password, salt, length);

    /// <summary>
    /// Verifies a password against a scrypt PHC encoded-hash string.
    /// </summary>
    /// <param name="encoded">
    /// The PHC encoded-hash string produced by <see cref="Hash(ReadOnlySpan{byte}, ReadOnlySpan{byte}, int)" />.
    /// </param>
    /// <param name="password">The password to verify.</param>
    /// <returns>
    /// <see langword="true" /> if the password matches the encoded hash; otherwise, <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="encoded" /> is <see langword="null" />.</exception>
    /// <exception cref="FormatException">
    /// <paramref name="encoded" /> is not a well-formed scrypt PHC string.
    /// </exception>
    public static bool Verify(string encoded, ReadOnlySpan<byte> password)
    {
        ThrowHelper.ThrowIfNull(encoded);

        (int costN, int blockSizeR, int parallelization, byte[]? salt, byte[]? hash) = Decode(encoded);

        byte[] computed = new byte[hash.Length];
        ScryptCore.DeriveKey(password, salt, costN, blockSizeR, parallelization, computed);

        bool match = CryptographicOperations.FixedTimeEquals(computed, hash);
        CryptographyHelper.Clear(computed);
        return match;
    }

    /// <summary>
    /// Throws an <see cref="ArgumentOutOfRangeException" /> if the requested output length is less than 1.
    /// </summary>
    /// <param name="length">The requested output length, in bytes.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="length" /> is less than 1.</exception>
    private static void ThrowIfInvalidLength(int length)
    {
        // The RFC 7914 upper bound of (2^32 - 1) * 32 always exceeds Array.MaxLength, so only the lower bound is
        // meaningful for a managed array.
        if (length < 1)
            throw new ArgumentOutOfRangeException(
                nameof(length),
                length,
                string.Format(CultureInfo.CurrentCulture, CryptoResourceStrings.Arg_OutOfRange_ScryptOutputLength, (long)uint.MaxValue * 32));
    }

    /// <summary>
    /// Formats a scrypt PHC encoded-hash string.
    /// </summary>
    /// <param name="p">The scrypt parameters to encode.</param>
    /// <param name="salt">The salt bytes.</param>
    /// <param name="hash">The derived hash bytes.</param>
    /// <returns>The scrypt PHC encoded-hash string.</returns>
    private static string Encode(ScryptParameters p, ReadOnlySpan<byte> salt, ReadOnlySpan<byte> hash)
    {
        int logN = BitOperations.Log2((uint)p.CostN);

        var sb = new StringBuilder();
        sb.Append("$scrypt$ln=").Append(logN.ToString(CultureInfo.InvariantCulture))
          .Append(",r=").Append(p.BlockSizeR.ToString(CultureInfo.InvariantCulture))
          .Append(",p=").Append(p.Parallelization.ToString(CultureInfo.InvariantCulture));
        sb.Append('$').Append(PhcString.EncodeBase64(salt));
        sb.Append('$').Append(PhcString.EncodeBase64(hash));
        return sb.ToString();
    }

    /// <summary>
    /// Parses a scrypt PHC encoded-hash string into its constituent fields.
    /// </summary>
    /// <param name="encoded">The scrypt PHC encoded-hash string to parse.</param>
    /// <returns>The cost parameters, salt, and hash parsed from <paramref name="encoded" />.</returns>
    /// <exception cref="FormatException"><paramref name="encoded" /> is not a valid scrypt PHC string.</exception>
    private static (int CostN, int BlockSizeR, int Parallelization, byte[] Salt, byte[] Hash) Decode(string encoded)
    {
        string[] fields = PhcString.SplitFields(encoded);

        // Expect: "", scrypt, ln=..,r=..,p=.., salt, hash
        if (fields.Length != 5 || fields[1] != "scrypt")
            throw PhcString.Invalid();

        int? logN = null, blockSizeR = null, parallelization = null;
        foreach (string part in fields[2].Split(','))
        {
            int eq = part.IndexOf('=', StringComparison.Ordinal);
            if (eq <= 0)
                throw PhcString.Invalid();

            string key = part[..eq];
            string value = part[(eq + 1)..];

            switch (key)
            {
                case "ln": logN = ParseInt(value); break;
                case "r": blockSizeR = ParseInt(value); break;
                case "p": parallelization = ParseInt(value); break;
                default: throw PhcString.Invalid();
            }
        }

        if (logN is null or < 1 or > 30 || blockSizeR is null || parallelization is null)
            throw PhcString.Invalid();

        byte[] salt = PhcString.DecodeBase64(fields[3]);
        byte[] hash = PhcString.DecodeBase64(fields[4]);

        return (1 << logN.Value, blockSizeR.Value, parallelization.Value, salt, hash);
    }

    /// <summary>
    /// Parses a non-negative decimal integer, throwing a <see cref="FormatException" /> on failure.
    /// </summary>
    /// <param name="value">The text to parse.</param>
    /// <returns>The parsed non-negative integer.</returns>
    private static int ParseInt(string value) =>
        int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out int result)
            ? result
            : throw PhcString.Invalid();
}
