// ---------------------------------------------------------------------------------------------------------------
// <copyright file="XmlDocFormatAnalyzer.cs" company="Bodu Pty. Ltd.">
//     Copyright (c) Bodu Pty. Ltd.. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading;
using Bodu.CodeStyle.XmlDocumentation;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Configuration;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Diagnostics;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers;

/// <summary>
/// Reports one of the <c>BODU1001</c>–<c>BODU1040</c> diagnostics when an XML documentation comment's
/// formatting differs from the active project policy. Each per-tag rule has its own diagnostic ID so that
/// individual tags can be silenced or re-targeted in <c>.editorconfig</c> independently.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class XmlDocFormatAnalyzer : DiagnosticAnalyzer
{
    /// <summary>
    /// Gets the property key used to surface the canonical formatted text on the emitted diagnostic.
    /// </summary>
    /// <returns>The property name consumed by the code fix provider.</returns>
    public static string FormattedTextPropertyKey => "FormattedText";

    /// <inheritdoc />
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        DiagnosticDescriptors.All;

    /// <inheritdoc />
    public override void Initialize(AnalysisContext context)
    {
        if (context is null) throw new ArgumentNullException(nameof(context));

        context.EnableConcurrentExecution();
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.RegisterCompilationStartAction(OnCompilationStart);
    }

    private static void OnCompilationStart(CompilationStartAnalysisContext compilationContext)
    {
        XmlDocFormatOptions compilationOptions = XmlDocConfigurationLoader.LoadCompilationOptions(
            compilationContext.Options.AdditionalFiles,
            compilationContext.CancellationToken);

        var formatter = new XmlDocFormatter();

        compilationContext.RegisterSyntaxTreeAction(treeContext =>
            AnalyzeTree(treeContext, compilationOptions, formatter));
    }

    private static void AnalyzeTree(
        SyntaxTreeAnalysisContext treeContext,
        XmlDocFormatOptions compilationOptions,
        XmlDocFormatter formatter)
    {
        if (GeneratedCodeFilters.IsGeneratedFileName(treeContext.Tree)) return;
        if (GeneratedCodeFilters.HasAutoGeneratedMarker(treeContext.Tree)) return;

        AnalyzerConfigOptions treeOptions = treeContext.Options.AnalyzerConfigOptionsProvider.GetOptions(treeContext.Tree);
        XmlDocFormatOptions options = XmlDocConfigurationLoader.ApplyEditorConfigOverrides(compilationOptions, treeOptions);
        var lineEnding = XmlDocConfigurationLoader.ResolveLineEnding(treeOptions);

        SyntaxNode root = treeContext.Tree.GetRoot(treeContext.CancellationToken);
        foreach (SyntaxTrivia trivia in root.DescendantTrivia(descendIntoTrivia: true))
        {
            treeContext.CancellationToken.ThrowIfCancellationRequested();

            if (!trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia))
            {
                continue;
            }

            var triviaText = trivia.ToFullString();
            var baseIndent = ResolveBaseIndent(trivia);

            var formatContext = new XmlDocFormatContext(baseIndent, lineEnding, XmlDocMemberKindHint.Unknown);
            XmlDocFormatResult result = formatter.FormatTrivia(triviaText, formatContext, options);

            if (!result.Changed) continue;

            ImmutableDictionary<string, string?> properties = ImmutableDictionary<string, string?>.Empty
                .Add(FormattedTextPropertyKey, result.FormattedText);

            // Use FullSpan to include the leading "///" characters in the diagnostic location so that the
            // editor squiggle covers the full doc trivia text rather than just the structured XML payload.
            var location = Location.Create(treeContext.Tree, trivia.FullSpan);

            // The attributor deduplicates per-tag changes; emit one diagnostic per attributed change so each
            // tag and the cross-cutting bucket can be silenced independently in .editorconfig.
            ImmutableArray<XmlDocFormattingChange> changes = result.Changes;
            if (changes.IsDefaultOrEmpty)
            {
                // Defensive: the formatter reported a change but the attributor produced no records — emit
                // the cross-cutting bucket so the diagnostic surfaces in the editor.
                treeContext.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.XmlDocCrossCutting, location, properties));
                continue;
            }

            foreach (XmlDocFormattingChange change in changes)
            {
                DiagnosticDescriptor descriptor = DiagnosticDescriptors.ForTag(change.TagName);
                treeContext.ReportDiagnostic(Diagnostic.Create(descriptor, location, properties));
            }
        }
    }

    private static string ResolveBaseIndent(SyntaxTrivia trivia)
    {
        SyntaxToken token = trivia.Token;
        SyntaxTriviaList leading = token.LeadingTrivia;
        var index = leading.IndexOf(trivia);
        if (index <= 0) return string.Empty;

        SyntaxTrivia previous = leading[index - 1];
        if (!previous.IsKind(SyntaxKind.WhitespaceTrivia)) return string.Empty;

        return previous.ToFullString();
    }
}
