<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Test\test\Bodu.Test.csproj" />
    <ProjectReference Include="..\src\Bodu.IO.Compound.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fixtures\*.xls">
      <LogicalName>Bodu.IO.Compound.Fixtures.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Fixtures\Reference\valid\*">
      <LogicalName>Bodu.IO.Compound.Fixtures.Reference.valid.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Fixtures\Reference\invalid\*">
      <LogicalName>Bodu.IO.Compound.Fixtures.Reference.invalid.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Fixtures\Reference\manifest.valid.json">
      <LogicalName>Bodu.IO.Compound.Fixtures.Reference.manifest.valid.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
