//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilteringResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilteringResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.FilteringResourceStrings", typeof(FilteringResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filter pattern must not be empty or whitespace..
        /// </summary>
        internal static string Arg_Invalid_PatternEmpty {
            get {
                return ResourceManager.GetString("Arg_Invalid_PatternEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The pattern collection must not contain null entries..
        /// </summary>
        internal static string Arg_Invalid_PatternsContainsNull {
            get {
                return ResourceManager.GetString("Arg_Invalid_PatternsContainsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filter pattern exceeds the maximum supported length of {0} characters..
        /// </summary>
        internal static string Arg_OutOfRange_PatternTooLong {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_PatternTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The regular expression pattern &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string Arg_Invalid_RegexPattern {
            get {
                return ResourceManager.GetString("Arg_Invalid_RegexPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The regular expression match timeout must be positive or Regex.InfiniteMatchTimeout..
        /// </summary>
        internal static string Arg_OutOfRange_RegexMatchTimeout {
            get {
                return ResourceManager.GetString("Arg_OutOfRange_RegexMatchTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; contains an unterminated character class; expected &apos;]&apos;..
        /// </summary>
        internal static string Arg_Invalid_UnterminatedCharacterClass {
            get {
                return ResourceManager.GetString("Arg_Invalid_UnterminatedCharacterClass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; contains an empty character class..
        /// </summary>
        internal static string Arg_Invalid_EmptyCharacterClass {
            get {
                return ResourceManager.GetString("Arg_Invalid_EmptyCharacterClass", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; contains an unterminated brace alternation; expected &apos;}&apos;..
        /// </summary>
        internal static string Arg_Invalid_UnterminatedBrace {
            get {
                return ResourceManager.GetString("Arg_Invalid_UnterminatedBrace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; ends with a dangling escape character..
        /// </summary>
        internal static string Arg_Invalid_DanglingEscape {
            get {
                return ResourceManager.GetString("Arg_Invalid_DanglingEscape", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; nests brace alternations deeper than the supported maximum of {1} levels..
        /// </summary>
        internal static string Arg_Invalid_BraceNestingTooDeep {
            get {
                return ResourceManager.GetString("Arg_Invalid_BraceNestingTooDeep", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The wildcard pattern &apos;{0}&apos; expands to more than the supported maximum of {1} alternatives..
        /// </summary>
        internal static string Arg_Invalid_BraceExpansionTooLarge {
            get {
                return ResourceManager.GetString("Arg_Invalid_BraceExpansionTooLarge", resourceCulture);
            }
        }
    }
}
