// ---------------------------------------------------------------------------------------------------------------
// <copyright file="GeneratedCodeFilters.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.IO;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers.Internal;

/// <summary>
/// Provides supplementary checks for filtering out generated source files when Roslyn's built-in generated-code
/// detection (configured via <c>ConfigureGeneratedCodeAnalysis</c>) misses a particular file.
/// </summary>
internal static class GeneratedCodeFilters
{
    /// <summary>Caches the combined generated-code verdict per syntax tree so syntax-node analyzers that run once per XML element do not re-read and re-scan the file text for every node. Keys are weakly held, so trees are not kept alive and the cache spans compilations without leaking.</summary>
    private static readonly ConditionalWeakTable<SyntaxTree, StrongBox<bool>> s_generatedCache = new();

    /// <summary>
    /// Returns whether the supplied syntax tree should be skipped as generated code, combining the filename and
    /// auto-generated-marker checks and caching the result per tree.
    /// </summary>
    /// <param name="tree">The syntax tree under analysis.</param>
    /// <returns>
    /// <see langword="true" /> when the tree is recognised as generated; otherwise <see langword="false" />.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="tree" /> is <see langword="null" />.
    /// </exception>
    public static bool IsGenerated(SyntaxTree tree)
    {
        if (tree is null) throw new ArgumentNullException(nameof(tree));

        StrongBox<bool> box = s_generatedCache.GetValue(
            tree,
            t => new StrongBox<bool>(IsGeneratedFileName(t) || HasAutoGeneratedMarker(t)));

        return box.Value;
    }

    /// <summary>
    /// Returns whether the supplied syntax tree should be skipped because its filename indicates generated code.
    /// </summary>
    /// <param name="tree">The syntax tree under analysis.</param>
    /// <returns>
    /// <see langword="true" /> when the filename matches a generated-code pattern; otherwise <see langword="false" />.
    /// </returns>
    public static bool IsGeneratedFileName(SyntaxTree tree)
    {
        if (tree is null) throw new ArgumentNullException(nameof(tree));

        var filePath = tree.FilePath;
        if (string.IsNullOrEmpty(filePath)) return false;

        var fileName = Path.GetFileName(filePath!);
        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith("AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns whether the supplied syntax tree contains the standard <c>&lt;auto-generated /&gt;</c> marker in its
    /// first few lines.
    /// </summary>
    /// <param name="tree">The syntax tree under analysis.</param>
    /// <returns><see langword="true" /> when the marker is found; otherwise <see langword="false" />.</returns>
    public static bool HasAutoGeneratedMarker(SyntaxTree tree)
    {
        if (tree is null) throw new ArgumentNullException(nameof(tree));

        SourceText text = tree.GetText();
        var linesToScan = Math.Min(text.Lines.Count, 4);
        for (var i = 0; i < linesToScan; i++)
        {
            var line = text.Lines[i].ToString();
            if (line.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return true;
            }
        }

        return false;
    }
}
