// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
namespace Bodu.Financial.Currencies;

/// <summary>
/// Identifies CAD (Canadian Dollar) at the type-system level.
/// </summary>
/// <remarks>
/// ISO 4217 numeric code <c>124</c>; minor-unit precision <c>2</c>.
/// </remarks>
public sealed class CAD : ICurrency
{
    /// <summary>
    /// Gets the ISO 4217 alphabetic code for the currency.
    /// </summary>
    /// <returns>The three-letter ISO 4217 code.</returns>
    public static string IsoCode => "CAD";

    /// <summary>
    /// Gets the ISO 4217 three-digit numeric code for the currency.
    /// </summary>
    /// <returns>The three-digit ISO 4217 numeric code.</returns>
    public static int NumericCode => 124;

    /// <summary>
    /// Gets the number of fractional digits in the currency's minor unit.
    /// </summary>
    /// <returns>The currency's minor-unit precision.</returns>
    public static int MinorUnits => 2;

    /// <summary>
    /// Gets the smallest cash denomination of the currency, in the major unit.
    /// </summary>
    /// <returns>The cash-rounding increment.</returns>
    public static decimal CashRoundingIncrement => 0.05m;

    /// <summary>
    /// Gets the English-language name of the currency.
    /// </summary>
    /// <returns>The currency's English name in singular Title Case.</returns>
    public static string EnglishName => "Canadian Dollar";

    /// <summary>
    /// Prevents instantiation of the <see cref="CAD" /> tag type.
    /// </summary>
    private CAD()
    {
    }
}
