// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
#nullable enable
namespace Bodu.Financial.Currencies;

using global::System.Collections.Generic;

/// <summary>
/// Source-generated registration list of the shipped currency catalogue, consumed by
/// <see cref="Bodu.Financial.Currencies.CurrencyRegistry" /> at static-constructor time.
/// </summary>
internal static class GeneratedCurrencyRegistration
{
    /// <summary>
    /// Enumerates the shipped <see cref="Bodu.Financial.Currencies.CurrencyInfo" /> entries.
    /// </summary>
    /// <returns>One entry per currency tag type under <c>Bodu.Financial.Currencies</c>.</returns>
    public static IEnumerable<global::Bodu.Financial.Currencies.CurrencyInfo> All()
    {
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AED", 2, 0m, false, null, null, "United Arab Emirates Dirham", 784);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AFN", 2, 0m, false, null, null, "Afghani", 971);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ALL", 2, 0m, false, null, null, "Lek", 8);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AMD", 2, 0m, false, null, null, "Armenian Dram", 51);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ANG", 2, 0m, false, null, null, "Netherlands Antillean Guilder", 532);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AOA", 2, 0m, false, null, null, "Kwanza", 973);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ARS", 2, 0m, false, null, null, "Argentine Peso", 32);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AUD", 2, 0.05m, false, null, null, "Australian Dollar", 36);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AWG", 2, 0m, false, null, null, "Aruban Florin", 533);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AZN", 2, 0m, false, null, null, "Azerbaijan Manat", 944);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BAM", 2, 0m, false, null, null, "Convertible Mark", 977);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BBD", 2, 0m, false, null, null, "Barbados Dollar", 52);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BDT", 2, 0m, false, null, null, "Taka", 50);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BGN", 2, 0m, false, null, null, "Bulgarian Lev", 975);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BHD", 3, 0m, false, null, null, "Bahraini Dinar", 48);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BIF", 0, 0m, false, null, null, "Burundi Franc", 108);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BMD", 2, 0m, false, null, null, "Bermudian Dollar", 60);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BND", 2, 0m, false, null, null, "Brunei Dollar", 96);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BOB", 2, 0m, false, null, null, "Boliviano", 68);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BRL", 2, 0m, false, null, null, "Brazilian Real", 986);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BSD", 2, 0m, false, null, null, "Bahamian Dollar", 44);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BTN", 2, 0m, false, null, null, "Ngultrum", 64);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BWP", 2, 0m, false, null, null, "Pula", 72);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BYN", 2, 0m, false, null, null, "Belarusian Ruble", 933);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BZD", 2, 0m, false, null, null, "Belize Dollar", 84);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CAD", 2, 0.05m, false, null, null, "Canadian Dollar", 124);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CDF", 2, 0m, false, null, null, "Congolese Franc", 976);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CHF", 2, 0.05m, false, null, null, "Swiss Franc", 756);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CLP", 0, 0m, false, null, null, "Chilean Peso", 152);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CNY", 2, 0m, false, null, null, "Yuan Renminbi", 156);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("COP", 2, 0m, false, null, null, "Colombian Peso", 170);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CRC", 2, 0m, false, null, null, "Costa Rican Colon", 188);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CUP", 2, 0m, false, null, null, "Cuban Peso", 192);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CVE", 2, 0m, false, null, null, "Cabo Verde Escudo", 132);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CZK", 2, 0m, false, null, null, "Czech Koruna", 203);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("DJF", 0, 0m, false, null, null, "Djibouti Franc", 262);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("DKK", 2, 0m, false, null, null, "Danish Krone", 208);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("DOP", 2, 0m, false, null, null, "Dominican Peso", 214);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("DZD", 2, 0m, false, null, null, "Algerian Dinar", 12);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("EGP", 2, 0m, false, null, null, "Egyptian Pound", 818);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ERN", 2, 0m, false, null, null, "Nakfa", 232);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ETB", 2, 0m, false, null, null, "Ethiopian Birr", 230);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("EUR", 2, 0m, false, null, null, "Euro", 978);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("FJD", 2, 0m, false, null, null, "Fiji Dollar", 242);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("FKP", 2, 0m, false, null, null, "Falkland Islands Pound", 238);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GBP", 2, 0m, false, null, null, "Pound Sterling", 826);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GEL", 2, 0m, false, null, null, "Lari", 981);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GHS", 2, 0m, false, null, null, "Ghana Cedi", 936);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GIP", 2, 0m, false, null, null, "Gibraltar Pound", 292);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GMD", 2, 0m, false, null, null, "Dalasi", 270);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GNF", 0, 0m, false, null, null, "Guinean Franc", 324);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GTQ", 2, 0m, false, null, null, "Quetzal", 320);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GYD", 2, 0m, false, null, null, "Guyana Dollar", 328);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("HKD", 2, 0m, false, null, null, "Hong Kong Dollar", 344);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("HNL", 2, 0m, false, null, null, "Lempira", 340);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("HTG", 2, 0m, false, null, null, "Gourde", 332);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("HUF", 2, 0m, false, null, null, "Forint", 348);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("IDR", 2, 0m, false, null, null, "Rupiah", 360);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ILS", 2, 0m, false, null, null, "New Israeli Sheqel", 376);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("INR", 2, 0m, false, null, null, "Indian Rupee", 356);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("IQD", 3, 0m, false, null, null, "Iraqi Dinar", 368);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("IRR", 2, 0m, false, null, null, "Iranian Rial", 364);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ISK", 0, 0m, false, null, null, "Iceland Krona", 352);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("JMD", 2, 0m, false, null, null, "Jamaican Dollar", 388);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("JOD", 3, 0m, false, null, null, "Jordanian Dinar", 400);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("JPY", 0, 0m, false, null, null, "Yen", 392);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KES", 2, 0m, false, null, null, "Kenyan Shilling", 404);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KGS", 2, 0m, false, null, null, "Som", 417);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KHR", 2, 0m, false, null, null, "Riel", 116);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KMF", 0, 0m, false, null, null, "Comorian Franc", 174);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KPW", 2, 0m, false, null, null, "North Korean Won", 408);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KRW", 0, 0m, false, null, null, "Won", 410);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KWD", 3, 0m, false, null, null, "Kuwaiti Dinar", 414);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KYD", 2, 0m, false, null, null, "Cayman Islands Dollar", 136);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("KZT", 2, 0m, false, null, null, "Tenge", 398);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LAK", 2, 0m, false, null, null, "Lao Kip", 418);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LBP", 2, 0m, false, null, null, "Lebanese Pound", 422);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LKR", 2, 0m, false, null, null, "Sri Lanka Rupee", 144);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LRD", 2, 0m, false, null, null, "Liberian Dollar", 430);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LSL", 2, 0m, false, null, null, "Loti", 426);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LYD", 3, 0m, false, null, null, "Libyan Dinar", 434);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MAD", 2, 0m, false, null, null, "Moroccan Dirham", 504);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MDL", 2, 0m, false, null, null, "Moldovan Leu", 498);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MGA", 2, 0m, false, null, null, "Malagasy Ariary", 969);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MKD", 2, 0m, false, null, null, "Denar", 807);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MMK", 2, 0m, false, null, null, "Kyat", 104);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MNT", 2, 0m, false, null, null, "Tugrik", 496);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MOP", 2, 0m, false, null, null, "Pataca", 446);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MRU", 2, 0m, false, null, null, "Ouguiya", 929);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MUR", 2, 0m, false, null, null, "Mauritius Rupee", 480);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MVR", 2, 0m, false, null, null, "Rufiyaa", 462);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MWK", 2, 0m, false, null, null, "Malawi Kwacha", 454);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MXN", 2, 0m, false, null, null, "Mexican Peso", 484);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MYR", 2, 0m, false, null, null, "Malaysian Ringgit", 458);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MZN", 2, 0m, false, null, null, "Mozambique Metical", 943);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NAD", 2, 0m, false, null, null, "Namibia Dollar", 516);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NGN", 2, 0m, false, null, null, "Naira", 566);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NIO", 2, 0m, false, null, null, "Cordoba Oro", 558);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NOK", 2, 1m, false, null, null, "Norwegian Krone", 578);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NPR", 2, 0m, false, null, null, "Nepalese Rupee", 524);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NZD", 2, 0.1m, false, null, null, "New Zealand Dollar", 554);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("OMR", 3, 0m, false, null, null, "Rial Omani", 512);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PAB", 2, 0m, false, null, null, "Balboa", 590);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PEN", 2, 0m, false, null, null, "Sol", 604);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PGK", 2, 0m, false, null, null, "Kina", 598);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PHP", 2, 0m, false, null, null, "Philippine Peso", 608);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PKR", 2, 0m, false, null, null, "Pakistan Rupee", 586);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PLN", 2, 0m, false, null, null, "Zloty", 985);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PYG", 0, 0m, false, null, null, "Guarani", 600);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("QAR", 2, 0m, false, null, null, "Qatari Rial", 634);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("RON", 2, 0m, false, null, null, "Romanian Leu", 946);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("RSD", 2, 0m, false, null, null, "Serbian Dinar", 941);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("RUB", 2, 0m, false, null, null, "Russian Ruble", 643);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("RWF", 0, 0m, false, null, null, "Rwanda Franc", 646);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SAR", 2, 0m, false, null, null, "Saudi Riyal", 682);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SBD", 2, 0m, false, null, null, "Solomon Islands Dollar", 90);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SCR", 2, 0m, false, null, null, "Seychelles Rupee", 690);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SDG", 2, 0m, false, null, null, "Sudanese Pound", 938);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SEK", 2, 1m, false, null, null, "Swedish Krona", 752);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SGD", 2, 0m, false, null, null, "Singapore Dollar", 702);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SHP", 2, 0m, false, null, null, "Saint Helena Pound", 654);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SLE", 2, 0m, false, null, null, "Leone", 925);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SOS", 2, 0m, false, null, null, "Somali Shilling", 706);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SRD", 2, 0m, false, null, null, "Surinam Dollar", 968);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SSP", 2, 0m, false, null, null, "South Sudanese Pound", 728);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("STN", 2, 0m, false, null, null, "Dobra", 930);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SVC", 2, 0m, false, null, null, "El Salvador Colon", 222);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SYP", 2, 0m, false, null, null, "Syrian Pound", 760);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SZL", 2, 0m, false, null, null, "Lilangeni", 748);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("THB", 2, 0m, false, null, null, "Baht", 764);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TJS", 2, 0m, false, null, null, "Somoni", 972);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TMT", 2, 0m, false, null, null, "Turkmenistan New Manat", 934);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TND", 3, 0m, false, null, null, "Tunisian Dinar", 788);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TOP", 2, 0m, false, null, null, "Pa’anga", 776);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TRY", 2, 0m, false, null, null, "Turkish Lira", 949);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TTD", 2, 0m, false, null, null, "Trinidad and Tobago Dollar", 780);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TWD", 2, 0m, false, null, null, "New Taiwan Dollar", 901);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TZS", 2, 0m, false, null, null, "Tanzanian Shilling", 834);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("UAH", 2, 0m, false, null, null, "Hryvnia", 980);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("UGX", 0, 0m, false, null, null, "Uganda Shilling", 800);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("USD", 2, 0m, false, null, null, "US Dollar", 840);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("UYU", 2, 0m, false, null, null, "Peso Uruguayo", 858);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("UZS", 2, 0m, false, null, null, "Uzbekistan Sum", 860);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("VES", 2, 0m, false, null, null, "Bolivar Soberano", 928);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("VND", 0, 0m, false, null, null, "Dong", 704);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("VUV", 0, 0m, false, null, null, "Vatu", 548);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("WST", 2, 0m, false, null, null, "Tala", 882);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("XAF", 0, 0m, false, null, null, "CFA Franc BEAC", 950);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("XCD", 2, 0m, false, null, null, "East Caribbean Dollar", 951);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("XOF", 0, 0m, false, null, null, "CFA Franc BCEAO", 952);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("XPF", 0, 0m, false, null, null, "CFP Franc", 953);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("YER", 2, 0m, false, null, null, "Yemeni Rial", 886);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ZAR", 2, 0m, false, null, null, "Rand", 710);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ZMW", 2, 0m, false, null, null, "Zambian Kwacha", 967);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ZWG", 2, 0m, false, null, null, "Zimbabwe Gold", 924);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ATS", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Austrian Schilling", 40);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("AZM", 2, 0m, true, new global::System.DateOnly(2006, 1, 1), "AZN", "Old Azerbaijan Manat", 31);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("BEF", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Belgian Franc", 56);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("CYP", 2, 0m, true, new global::System.DateOnly(2008, 1, 31), "EUR", "Cypriot Pound", 196);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("DEM", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Deutsche Mark", 276);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("EEK", 2, 0m, true, new global::System.DateOnly(2011, 1, 14), "EUR", "Estonian Kroon", 233);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ESP", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Spanish Peseta", 724);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("FIM", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Finnish Markka", 246);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("FRF", 2, 0m, true, new global::System.DateOnly(2002, 2, 17), "EUR", "French Franc", 250);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GHC", 2, 0m, true, new global::System.DateOnly(2007, 7, 1), "GHS", "Old Ghana Cedi", 288);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("GRD", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Greek Drachma", 300);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("HRK", 2, 0m, true, new global::System.DateOnly(2023, 1, 14), "EUR", "Croatian Kuna", 191);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("IEP", 2, 0m, true, new global::System.DateOnly(2002, 2, 9), "EUR", "Irish Pound", 372);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ITL", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Italian Lira", 380);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LTL", 2, 0m, true, new global::System.DateOnly(2015, 1, 15), "EUR", "Lithuanian Litas", 440);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LUF", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Luxembourg Franc", 442);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("LVL", 2, 0m, true, new global::System.DateOnly(2014, 1, 14), "EUR", "Latvian Lats", 428);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MTL", 2, 0m, true, new global::System.DateOnly(2008, 1, 31), "EUR", "Maltese Lira", 470);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("MZM", 2, 0m, true, new global::System.DateOnly(2006, 7, 1), "MZN", "Old Mozambican Metical", 508);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("NLG", 2, 0m, true, new global::System.DateOnly(2002, 1, 28), "EUR", "Netherlands Guilder", 528);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("PTE", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR", "Portuguese Escudo", 620);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ROL", 2, 0m, true, new global::System.DateOnly(2005, 7, 1), "RON", "Old Romanian Leu", 642);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SIT", 2, 0m, true, new global::System.DateOnly(2007, 1, 14), "EUR", "Slovenian Tolar", 705);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SKK", 2, 0m, true, new global::System.DateOnly(2009, 1, 16), "EUR", "Slovak Koruna", 703);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("SRG", 2, 0m, true, new global::System.DateOnly(2004, 1, 1), "SRD", "Suriname Guilder", 740);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("TMM", 0, 0m, true, new global::System.DateOnly(2009, 1, 1), "TMT", "Old Turkmenistan Manat", 795);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("VEB", 2, 0m, true, new global::System.DateOnly(2008, 1, 1), "VEF", "Venezuelan Bolívar", 862);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("VEF", 2, 0m, true, new global::System.DateOnly(2018, 8, 20), "VES", "Venezuelan Bolívar Fuerte", 937);
        yield return new global::Bodu.Financial.Currencies.CurrencyInfo("ZWL", 2, 0m, true, new global::System.DateOnly(2024, 4, 8), "ZWG", "Zimbabwe Dollar", 932);
    }
}
