// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
namespace Bodu.Financial.Currencies;

using global::System.Collections.Generic;

/// <summary>
/// Source-generated registration list of the shipped currency catalogue, consumed by
/// <see cref="Bodu.Financial.CurrencyRegistry" /> at static-constructor time.
/// </summary>
internal static class GeneratedCurrencyRegistration
{
    /// <summary>
    /// Enumerates the shipped <see cref="Bodu.Financial.CurrencyInfo" /> entries.
    /// </summary>
    /// <returns>One entry per currency tag type under <c>Bodu.Financial.Currencies</c>.</returns>
    public static IEnumerable<global::Bodu.Financial.CurrencyInfo> All()
    {
        yield return new global::Bodu.Financial.CurrencyInfo("AED", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AFN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ALL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AMD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ANG", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AOA", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ARS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AUD", 2, 0.05m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AWG", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("AZN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BAM", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BBD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BDT", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BGN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BHD", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BIF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BMD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BND", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BOB", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BRL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BSD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BTN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BWP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BYN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("BZD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CAD", 2, 0.05m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CDF", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CHF", 2, 0.05m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CLP", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CNY", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("COP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CRC", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CUP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CVE", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("CZK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("DJF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("DKK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("DOP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("DZD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("EGP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ERN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ETB", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("EUR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("FJD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("FKP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GBP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GEL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GHS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GIP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GMD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GNF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GTQ", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("GYD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("HKD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("HNL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("HTG", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("HUF", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("IDR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ILS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("INR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("IQD", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("IRR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ISK", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("JMD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("JOD", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("JPY", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KES", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KGS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KHR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KMF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KPW", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KRW", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KWD", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KYD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("KZT", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LAK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LBP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LKR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LRD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LSL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("LYD", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MAD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MDL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MGA", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MKD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MMK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MNT", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MOP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MRU", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MUR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MVR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MWK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MXN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MYR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("MZN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NAD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NGN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NIO", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NOK", 2, 1m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NPR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("NZD", 2, 0.1m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("OMR", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PAB", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PEN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PGK", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PHP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PKR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PLN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("PYG", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("QAR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("RON", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("RSD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("RUB", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("RWF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SAR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SBD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SCR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SDG", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SEK", 2, 1m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SGD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SHP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SLE", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SOS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SRD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SSP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("STN", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SVC", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SYP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("SZL", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("THB", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TJS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TMT", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TND", 3, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TOP", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TRY", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TTD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TWD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("TZS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("UAH", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("UGX", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("USD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("UYU", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("UZS", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("VES", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("VND", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("VUV", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("WST", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("XAF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("XCD", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("XOF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("XPF", 0, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("YER", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ZAR", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ZMW", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ZWG", 2, 0m, false, null, null);
        yield return new global::Bodu.Financial.CurrencyInfo("ATS", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("AZM", 2, 0m, true, new global::System.DateOnly(2006, 1, 1), "AZN");
        yield return new global::Bodu.Financial.CurrencyInfo("BEF", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("CYP", 2, 0m, true, new global::System.DateOnly(2008, 1, 31), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("DEM", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("EEK", 2, 0m, true, new global::System.DateOnly(2011, 1, 14), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("ESP", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("FIM", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("FRF", 2, 0m, true, new global::System.DateOnly(2002, 2, 17), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("GHC", 2, 0m, true, new global::System.DateOnly(2007, 7, 1), "GHS");
        yield return new global::Bodu.Financial.CurrencyInfo("GRD", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("HRK", 2, 0m, true, new global::System.DateOnly(2023, 1, 14), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("IEP", 2, 0m, true, new global::System.DateOnly(2002, 2, 9), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("ITL", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("LTL", 2, 0m, true, new global::System.DateOnly(2015, 1, 15), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("LUF", 2, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("LVL", 2, 0m, true, new global::System.DateOnly(2014, 1, 14), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("MTL", 2, 0m, true, new global::System.DateOnly(2008, 1, 31), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("MZM", 2, 0m, true, new global::System.DateOnly(2006, 7, 1), "MZN");
        yield return new global::Bodu.Financial.CurrencyInfo("NLG", 2, 0m, true, new global::System.DateOnly(2002, 1, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("PTE", 0, 0m, true, new global::System.DateOnly(2002, 2, 28), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("ROL", 2, 0m, true, new global::System.DateOnly(2005, 7, 1), "RON");
        yield return new global::Bodu.Financial.CurrencyInfo("SIT", 2, 0m, true, new global::System.DateOnly(2007, 1, 14), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("SKK", 2, 0m, true, new global::System.DateOnly(2009, 1, 16), "EUR");
        yield return new global::Bodu.Financial.CurrencyInfo("SRG", 2, 0m, true, new global::System.DateOnly(2004, 1, 1), "SRD");
        yield return new global::Bodu.Financial.CurrencyInfo("TMM", 0, 0m, true, new global::System.DateOnly(2009, 1, 1), "TMT");
        yield return new global::Bodu.Financial.CurrencyInfo("VEB", 2, 0m, true, new global::System.DateOnly(2008, 1, 1), "VEF");
        yield return new global::Bodu.Financial.CurrencyInfo("VEF", 2, 0m, true, new global::System.DateOnly(2018, 8, 20), "VES");
        yield return new global::Bodu.Financial.CurrencyInfo("ZWL", 2, 0m, true, new global::System.DateOnly(2024, 4, 8), "ZWG");
    }
}
