// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
#nullable enable
namespace Bodu.Financial.Currencies;

/// <summary>
/// Identifies YER (Yemeni Rial) at the type-system level.
/// </summary>
/// <remarks>
/// ISO 4217 numeric code <c>886</c>; minor-unit precision <c>2</c>.
/// </remarks>
public sealed class YER : ICurrency
{
    /// <summary>
    /// Gets the ISO 4217 alphabetic code for the currency.
    /// </summary>
    /// <returns>The three-letter ISO 4217 code.</returns>
    public static string IsoCode => "YER";

    /// <summary>
    /// Gets the number of fractional digits in the currency's minor unit.
    /// </summary>
    /// <returns>The currency's minor-unit precision.</returns>
    public static int MinorUnits => 2;

    /// <summary>
    /// Gets the English-language name of the currency.
    /// </summary>
    /// <returns>The currency's English name in singular Title Case.</returns>
    public static string EnglishName => "Yemeni Rial";

    /// <summary>
    /// Prevents instantiation of the <see cref="YER" /> tag type.
    /// </summary>
    private YER()
    {
    }
}
