// ---------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tools/CurrencyCatalogueGenerator from currencies.json. Do not edit by hand.
//     To regenerate: dotnet run --project tools/CurrencyCatalogueGenerator
// </auto-generated>
// ---------------------------------------------------------------------------------------------------------------
#nullable enable
namespace Bodu.Financial.Currencies;

/// <summary>
/// Identifies ZWL (Zimbabwe Dollar) at the type-system level.
/// </summary>
/// <remarks>
/// ISO 4217 numeric code <c>932</c>; minor-unit precision <c>2</c>.
/// Historic — demonetized on 2024-04-08, replaced by ZWG.
/// </remarks>
public sealed class ZWL : ICurrency
{
    /// <summary>
    /// Gets the ISO 4217 alphabetic code for the currency.
    /// </summary>
    /// <returns>The three-letter ISO 4217 code.</returns>
    public static string IsoCode => "ZWL";

    /// <summary>
    /// Gets the ISO 4217 three-digit numeric code for the currency.
    /// </summary>
    /// <returns>The three-digit ISO 4217 numeric code.</returns>
    public static int NumericCode => 932;

    /// <summary>
    /// Gets the number of fractional digits in the currency's minor unit.
    /// </summary>
    /// <returns>The currency's minor-unit precision.</returns>
    public static int MinorUnits => 2;

    /// <summary>
    /// Gets a value indicating that the currency has been demonetized.
    /// </summary>
    /// <returns><see langword="true" /> — this is a historic currency.</returns>
    public static bool IsHistoric => true;

    /// <summary>
    /// Gets the date the currency was withdrawn from circulation.
    /// </summary>
    /// <returns>The demonetization date.</returns>
    public static global::System.DateOnly? DemonetizedOn => new global::System.DateOnly(2024, 4, 8);

    /// <summary>
    /// Gets the ISO 4217 alphabetic code of the currency that replaced this one.
    /// </summary>
    /// <returns>The successor currency's ISO code.</returns>
    public static string? SuccessorIsoCode => "ZWG";

    /// <summary>
    /// Gets the English-language name of the currency.
    /// </summary>
    /// <returns>The currency's English name in singular Title Case.</returns>
    public static string EnglishName => "Zimbabwe Dollar";

    /// <summary>
    /// Prevents instantiation of the <see cref="ZWL" /> tag type.
    /// </summary>
    private ZWL()
    {
    }
}
