<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Bodu</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Security.Cryptography\AsconAead128.LWC_AEAD_KAT_128_128.txt" />
    <EmbeddedResource Include="Security.Cryptography\X25519.Wycheproof.txt" />
    <EmbeddedResource Include="Security.Cryptography\Ed25519.Wycheproof.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLKem.AcvpKeyGen.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLKem.AcvpEncapDecap.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLKem.AcvpKeyCheck.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLDsa.AcvpKeyGen.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLDsa.AcvpSigGen.txt" />
    <EmbeddedResource Include="Security.Cryptography\MLDsa.AcvpSigVer.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bodu.Test\test\Bodu.Test.csproj" />
    <ProjectReference Include="..\src\Bodu.Security.Cryptography.csproj" />
  </ItemGroup>

</Project>
