<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\bld\Bodu.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bodu</RootNamespace>
    <AssemblyName>Bodu.CoreLib.Test</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.0" />
    <PackageReference Include="MSTest.Analyzers" Version="4.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Exclude files that are not supported in .net standards -->

  <ItemGroup>
    <Compile Remove="Collections.Generic.Concurrent\ConcurrentCircularBufferTests.TrimExcess.cs" />
    <Compile Remove="Extensions\DateOnlyExtensionsTests.NextOccurrence.cs" />
  </ItemGroup>

  <!-- Exclude files that are incompatible with netstandard2.0 -->

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Bodu.Core.csproj" />
  </ItemGroup>
</Project>
