// ---------------------------------------------------------------------------------------------------------------
// <copyright file="XmlDocCodeRequiresCDataAnalyzer.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Immutable;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Diagnostics;
using Bodu.CodeStyle.XmlDocumentation.Analyzers.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Bodu.CodeStyle.XmlDocumentation.Analyzers;

/// <summary>
/// Reports <c>BODU1405</c> when a <c>&lt;code&gt;</c> documentation element does not begin with a
/// <c>&lt;![CDATA[…]]&gt;</c> section. Wrapping the body in CDATA preserves XML-significant characters and
/// language samples verbatim so that the generated documentation reproduces the example exactly.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class XmlDocCodeRequiresCDataAnalyzer : DiagnosticAnalyzer
{
    private const string CodeTagName = "code";

    /// <inheritdoc />
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(DiagnosticDescriptors.XmlDocCodeRequiresCData);

    /// <inheritdoc />
    public override void Initialize(AnalysisContext context)
    {
        if (context is null) throw new ArgumentNullException(nameof(context));

        context.EnableConcurrentExecution();
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.RegisterSyntaxNodeAction(AnalyzeXmlElement, SyntaxKind.XmlElement);
        context.RegisterSyntaxNodeAction(AnalyzeXmlEmptyElement, SyntaxKind.XmlEmptyElement);
    }

    private static void AnalyzeXmlElement(SyntaxNodeAnalysisContext context)
    {
        var element = (XmlElementSyntax)context.Node;
        if (!IsCodeElement(element.StartTag.Name)) return;
        if (IsInGeneratedCode(context)) return;

        foreach (XmlNodeSyntax child in element.Content)
        {
            if (IsWhitespaceOnly(child)) continue;

            if (child is XmlCDataSectionSyntax) return;

            // First non-whitespace child is not CDATA — flag the element.
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.XmlDocCodeRequiresCData,
                element.StartTag.GetLocation()));
            return;
        }

        // Element body contains nothing or only whitespace — no CDATA child present.
        context.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.XmlDocCodeRequiresCData,
            element.StartTag.GetLocation()));
    }

    private static void AnalyzeXmlEmptyElement(SyntaxNodeAnalysisContext context)
    {
        var element = (XmlEmptyElementSyntax)context.Node;
        if (!IsCodeElement(element.Name)) return;
        if (IsInGeneratedCode(context)) return;

        // A self-closing <code/> element has no children, so a CDATA child is impossible.
        context.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.XmlDocCodeRequiresCData,
            element.GetLocation()));
    }

    private static bool IsCodeElement(XmlNameSyntax name) =>
        name.Prefix is null
        && string.Equals(name.LocalName.ValueText, CodeTagName, StringComparison.Ordinal);

    private static bool IsWhitespaceOnly(XmlNodeSyntax node)
    {
        if (node is not XmlTextSyntax text) return false;

        foreach (SyntaxToken token in text.TextTokens)
        {
            if (token.IsKind(SyntaxKind.XmlTextLiteralNewLineToken)) continue;
            if (token.IsKind(SyntaxKind.XmlTextLiteralToken) && string.IsNullOrWhiteSpace(token.ValueText)) continue;

            return false;
        }

        return true;
    }

    private static bool IsInGeneratedCode(SyntaxNodeAnalysisContext context) =>
        GeneratedCodeFilters.IsGeneratedFileName(context.Node.SyntaxTree)
        || GeneratedCodeFilters.HasAutoGeneratedMarker(context.Node.SyntaxTree);
}
