<#
.SYNOPSIS
    Regenerates CrcStandard.Catalog.cs from crc-specs.json.

.DESCRIPTION
    Emits one `public static readonly CrcStandard FOO = new CrcStandard(...)` per catalogue entry,
    plus an `All` list, `FromName`, and `TryFromName` helpers. CRC standards listed in -Exclude are
    omitted from the generated declarations but still appear in `All` by referencing the externally
    defined constant of the same generated name (for example `CrcStandard.CRC32_ISOHDLC`, which is
    maintained directly in CrcStandard.cs).

.PARAMETER SpecsPath
    Path to the crc-specs.json input file.

.PARAMETER OutputPath
    Path of the C# file to write. Overwritten in place.

.PARAMETER Exclude
    Canonical CRC names to omit from emitted field declarations. These are expected to be defined
    elsewhere (typically in CrcStandard.cs) and are still referenced by the generated `All` list.

.EXAMPLE
    pwsh ./tools/Generate-CrcCatalog.ps1

.NOTES
    Requires PowerShell 7+.
#>
#Requires -Version 7
[CmdletBinding()]
param(
    [string]$SpecsPath = (Join-Path $PSScriptRoot '..' 'Bodu.Security.Cryptography' 'src' 'crc-specs.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..' 'Bodu.Security.Cryptography' 'src' 'Security.Cryptography' 'CrcStandard.Catalog.cs'),
    [string[]]$Exclude = @('CRC-32/ISO-HDLC')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function ConvertTo-ConstantName {
    param([string]$Name)
    $s = $Name -replace '/', '_'
    $s = $s -replace '[^A-Za-z0-9_]', ''
    return $s.ToUpperInvariant()
}

function Format-HexLiteral {
    param([string]$Value)
    $hex = ($Value -replace '^0[xX]', '').ToUpperInvariant()
    return "0x$hex" + 'UL'
}

$specs = Get-Content -LiteralPath $SpecsPath -Raw | ConvertFrom-Json
$excludeSet = [System.Collections.Generic.HashSet[string]]::new([string[]]$Exclude, [System.StringComparer]::Ordinal)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$sb.AppendLine('// <copyright file="CrcStandard.Catalog.cs" company="PlaceholderCompany">')
[void]$sb.AppendLine('//     Copyright (c) PlaceholderCompany. All rights reserved.')
[void]$sb.AppendLine('// </copyright>')
[void]$sb.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//     This file is regenerated by tools/Generate-CrcCatalog.ps1. Do not edit by hand.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace Bodu.Security.Cryptography')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    using System.Collections.Generic;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    /// <summary>')
[void]$sb.AppendLine('    /// Provides the catalogue of well-known CRC parameter sets sourced from the published CRC RevEng reference.')
[void]$sb.AppendLine('    /// </summary>')
[void]$sb.AppendLine('    public sealed partial class CrcStandard')
[void]$sb.AppendLine('    {')

foreach ($spec in $specs) {
    if ($excludeSet.Contains($spec.name)) { continue }

    $constName = ConvertTo-ConstantName $spec.name
    [void]$sb.AppendLine('        /// <summary>')
    [void]$sb.AppendLine("        /// Represents the <c>$($spec.name)</c> CRC standard.")
    [void]$sb.AppendLine('        /// </summary>')
    [void]$sb.AppendLine("        public static readonly CrcStandard $constName = new CrcStandard(")
    [void]$sb.AppendLine("            name: `"$($spec.name)`",")
    [void]$sb.AppendLine("            size: $($spec.size),")
    [void]$sb.AppendLine("            polynomial: $(Format-HexLiteral $spec.polynomial),")
    [void]$sb.AppendLine("            initialValue: $(Format-HexLiteral $spec.initialValue),")
    [void]$sb.AppendLine("            reflectIn: $($spec.reflectIn.ToString().ToLowerInvariant()),")
    [void]$sb.AppendLine("            reflectOut: $($spec.reflectOut.ToString().ToLowerInvariant()),")
    [void]$sb.AppendLine("            xOrOut: $(Format-HexLiteral $spec.xorOut));")
    [void]$sb.AppendLine()
}

# Emit the All array referencing every spec name (including excluded ones, which are defined in CrcStandard.cs).
[void]$sb.AppendLine('        private static readonly CrcStandard[] s_all = new[]')
[void]$sb.AppendLine('        {')
foreach ($spec in $specs) {
    $constName = ConvertTo-ConstantName $spec.name
    [void]$sb.AppendLine("            $constName,")
}
[void]$sb.AppendLine('        };')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        private static readonly Dictionary<string, CrcStandard> s_byName = BuildNameLookup();')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Gets an immutable snapshot of every CRC standard defined in the catalogue, in declaration order.')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        /// <value>A read-only list containing every <see cref="CrcStandard" /> entry.</value>')
[void]$sb.AppendLine('        public static IReadOnlyList<CrcStandard> All => s_all;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Resolves a catalogue entry by its canonical name (for example <c>"CRC-32/ISO-HDLC"</c>).')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        /// <param name="name">The canonical CRC standard name. Comparison is ordinal and case-sensitive.</param>')
[void]$sb.AppendLine('        /// <returns>The matching <see cref="CrcStandard" /> instance.</returns>')
[void]$sb.AppendLine('        /// <exception cref="ArgumentNullException"><paramref name="name" /> is <see langword="null" />.</exception>')
[void]$sb.AppendLine('        /// <exception cref="KeyNotFoundException">No catalogue entry with the specified <paramref name="name" /> exists.</exception>')
[void]$sb.AppendLine('        public static CrcStandard FromName(string name)')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            ThrowHelper.ThrowIfNull(name);')
[void]$sb.AppendLine('            if (!s_byName.TryGetValue(name, out CrcStandard? result))')
[void]$sb.AppendLine('                throw new KeyNotFoundException($"No CRC standard with the name ''{name}'' exists in the catalogue.");')
[void]$sb.AppendLine('            return result;')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Attempts to resolve a catalogue entry by its canonical name without throwing.')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        /// <param name="name">The canonical CRC standard name to look up.</param>')
[void]$sb.AppendLine('        /// <param name="standard">When this method returns, contains the matching <see cref="CrcStandard" /> if found; otherwise, <see langword="null" />.</param>')
[void]$sb.AppendLine('        /// <returns><see langword="true" /> if a catalogue entry was found; otherwise, <see langword="false" />.</returns>')
[void]$sb.AppendLine('        public static bool TryFromName(string? name, out CrcStandard? standard)')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            if (name is null)')
[void]$sb.AppendLine('            {')
[void]$sb.AppendLine('                standard = null;')
[void]$sb.AppendLine('                return false;')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine()
[void]$sb.AppendLine('            return s_byName.TryGetValue(name, out standard);')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        private static Dictionary<string, CrcStandard> BuildNameLookup()')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            var map = new Dictionary<string, CrcStandard>(s_all.Length, StringComparer.Ordinal);')
[void]$sb.AppendLine('            foreach (CrcStandard entry in s_all)')
[void]$sb.AppendLine('                map[entry.Name] = entry;')
[void]$sb.AppendLine('            return map;')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')

Set-Content -LiteralPath $OutputPath -Value $sb.ToString() -Encoding utf8
$emitted = ($specs | Where-Object { -not $excludeSet.Contains($_.name) }).Count
$total = $specs.Count
Write-Host "Wrote $OutputPath ($emitted emitted, $($total - $emitted) excluded, $total referenced in All)."
