<#
.SYNOPSIS
    Regenerates the CRC catalogue C# files (CrcStandards enum and CrcStandard.Catalog.cs) from
    crc-specs.json.

.DESCRIPTION
    Emits two files:
      * `CrcStandards.cs` — a `public enum CrcStandards` with one value per canonical catalogue
        entry, ordered to match the JSON. Published aliases are not exposed as enum values;
        they resolve to their canonical instance through `CrcStandard.FromName`.
      * `CrcStandard.Catalog.cs` — the packed data table (`CatalogEntry[] s_catalog`) and the
        lazy lookup plumbing: `Get(CrcStandards)`, `FromName(string)`, `TryFromName`, `All`.
        A per-entry cache publishes the first materialised `CrcStandard` via
        `Interlocked.CompareExchange` so reference equality is stable across threads.

    Filtering:
      -MaxSize    Upper bound on CRC width (default 64, matching `CrcStandard.MaxSize`).
                  Entries whose `size` exceeds this value are skipped entirely: no enum member,
                  no catalogue row, no name-lookup entry.
                  Currently only `CRC-82/DARC` is excluded by the default limit.

    Unlike the previous generator, this script no longer emits per-entry `public static readonly
    CrcStandard` fields or alias shortcut fields. Strongly-typed properties for the common
    standards are hand-maintained on `CrcStandard` itself (in `CrcStandard.cs`).

.PARAMETER SpecsPath
    Path to the crc-specs.json input file.

.PARAMETER EnumOutputPath
    Path of the enum C# file to write. Overwritten in place.

.PARAMETER CatalogOutputPath
    Path of the catalogue C# file to write. Overwritten in place.

.PARAMETER MaxSize
    Maximum CRC width (in bits).

.EXAMPLE
    pwsh ./tools/Generate-CrcCatalog.ps1

.NOTES
    Requires PowerShell 7+.
#>
#Requires -Version 7
[CmdletBinding()]
param(
    [string]$SpecsPath          = (Join-Path $PSScriptRoot '..' 'Bodu.IO.Hashing' 'src' 'crc-specs.json'),
    [string]$EnumOutputPath     = (Join-Path $PSScriptRoot '..' 'Bodu.IO.Hashing' 'src' 'IO.Hashing.Checksums' 'CrcStandards.cs'),
    [string]$CatalogOutputPath  = (Join-Path $PSScriptRoot '..' 'Bodu.IO.Hashing' 'src' 'IO.Hashing.Checksums' 'CrcStandard.Catalog.cs'),
    [int]$MaxSize = 64
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function ConvertTo-ConstantName {
    param([string]$Name)
    $s = $Name -replace '/', '_'
    $s = $s -replace '[^A-Za-z0-9_]', ''
    return $s.ToUpperInvariant()
}

function Format-HexLiteral {
    param([string]$Value)
    $hex = ($Value -replace '^0[xX]', '').ToUpperInvariant()
    return "0x$hex" + 'UL'
}

function Format-AnchorSlug {
    param([string]$Name)
    return 'crc.cat.' + ($Name -replace '/', '-').ToLowerInvariant()
}

function Format-EnglishList {
    param([string[]]$Items)
    if ($null -eq $Items -or $Items.Count -eq 0) { return '' }
    if ($Items.Count -eq 1) { return "<c>$($Items[0])</c>" }
    if ($Items.Count -eq 2) { return "<c>$($Items[0])</c> and <c>$($Items[1])</c>" }
    $head = ($Items[0..($Items.Count - 2)] | ForEach-Object { "<c>$_</c>" }) -join ', '
    return "$head, and <c>$($Items[-1])</c>"
}

function Get-AliasesFrom {
    param($Spec)
    if (-not $Spec.PSObject.Properties['aliases']) { return ,[string[]]@() }
    $value = $Spec.aliases
    if ($null -eq $value) { return ,[string[]]@() }
    $arr = @($value | Where-Object { $null -ne $_ })
    return ,[string[]]$arr
}

$specs = Get-Content -LiteralPath $SpecsPath -Raw | ConvertFrom-Json
$supported = @($specs | Where-Object { $_.size -le $MaxSize })

# ----- CrcStandards.cs -----
$enumBuilder = [System.Text.StringBuilder]::new()
[void]$enumBuilder.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$enumBuilder.AppendLine('// <copyright file="CrcStandards.cs" company="Bodu Pty. Ltd.">')
[void]$enumBuilder.AppendLine('//     Copyright (c) Bodu Pty. Ltd.. All rights reserved.')
[void]$enumBuilder.AppendLine('// </copyright>')
[void]$enumBuilder.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$enumBuilder.AppendLine('// <auto-generated>')
[void]$enumBuilder.AppendLine('//     This file is regenerated by tools/Generate-CrcCatalog.ps1. Do not edit by hand.')
[void]$enumBuilder.AppendLine('//     Source: Bodu.IO/src/crc-specs.json (derived from https://reveng.sourceforge.io/crc-catalogue/all.htm).')
[void]$enumBuilder.AppendLine('// </auto-generated>')
[void]$enumBuilder.AppendLine()
[void]$enumBuilder.AppendLine('namespace Bodu.IO.Hashing.Checksums')
[void]$enumBuilder.AppendLine('{')
[void]$enumBuilder.AppendLine('    /// <summary>')
[void]$enumBuilder.AppendLine('    /// Identifies a CRC parameter set defined in the <a href="https://reveng.sourceforge.io/crc-catalogue/all.htm">CRC RevEng catalogue</a>.')
[void]$enumBuilder.AppendLine('    /// Pass to <see cref="CrcStandard.Get(CrcStandards)" /> to materialise the corresponding <see cref="CrcStandard" /> on demand.')
[void]$enumBuilder.AppendLine('    /// </summary>')
[void]$enumBuilder.AppendLine('    /// <remarks>')
[void]$enumBuilder.AppendLine('    /// <para>The enum covers only canonical names. Published aliases (for example <c>CRC-32</c> or <c>PKZIP</c>) are not separate')
[void]$enumBuilder.AppendLine('    /// values — they resolve to their canonical instance through <see cref="CrcStandard.FromName(string)" />. Standards whose width')
[void]$enumBuilder.AppendLine('    /// exceeds 64 bits (currently only <c>CRC-82/DARC</c>) are omitted because they cannot be represented in a <see cref="ulong" />.</para>')
[void]$enumBuilder.AppendLine('    /// </remarks>')
[void]$enumBuilder.AppendLine('    public enum CrcStandards')
[void]$enumBuilder.AppendLine('    {')
for ($i = 0; $i -lt $supported.Count; $i++) {
    $spec = $supported[$i]
    $aliases = Get-AliasesFrom $spec
    $anchor = Format-AnchorSlug $spec.name
    $c = ConvertTo-ConstantName $spec.name

    $datesPart = ''
    $created = if ($spec.PSObject.Properties['created']) { [string]$spec.created } else { '' }
    $updated = if ($spec.PSObject.Properties['updated']) { [string]$spec.updated } else { '' }
    if ($created -and $updated) { $datesPart = " (Created: $created; Updated: $updated)" }
    elseif ($created)           { $datesPart = " (Created: $created)" }
    elseif ($updated)           { $datesPart = " (Updated: $updated)" }
    
    [void]$enumBuilder.AppendLine("        /// <summary>Represents the <c>$($spec.name)</c> CRC standard.</summary>")
    [void]$enumBuilder.AppendLine('        /// <remarks>')
    [void]$enumBuilder.AppendLine("        /// <para>The <c>$($spec.name)</c> standard is taken from the <a href=`"https://reveng.sourceforge.io/crc-catalogue/all.htm#$anchor`">CRC RevEng catalogue</a>$datesPart, with the following definition.</para>")
    [void]$enumBuilder.AppendLine('        /// <para>')
    [void]$enumBuilder.AppendLine('        /// <list type="bullet">')
    [void]$enumBuilder.AppendLine("        /// <item><description>Width: <c>$($spec.size)</c></description></item>")
    [void]$enumBuilder.AppendLine("        /// <item><description>Polynomial: <c>$(Format-HexLiteral $spec.polynomial)</c></description></item>")
    [void]$enumBuilder.AppendLine("        /// <item><description>Initial Value: <c>$(Format-HexLiteral $spec.initialValue)</c></description></item>")
    [void]$enumBuilder.AppendLine("        /// <item><description>Reflect In: <c>$($spec.reflectIn.ToString().ToLowerInvariant())</c></description></item>")
    [void]$enumBuilder.AppendLine("        /// <item><description>Reflect Out: <c>$($spec.reflectOut.ToString().ToLowerInvariant())</c></description></item>")
    [void]$enumBuilder.AppendLine("        /// <item><description>XOR Out: <c>$(Format-HexLiteral $spec.xorOut)</c></description></item>")
    [void]$enumBuilder.AppendLine('        /// </list>')
    [void]$enumBuilder.AppendLine('        /// </para>')
    if ($aliases.Count -gt 0) {
        $aliasList = Format-EnglishList -Items $aliases
        $verb = if ($aliases.Count -eq 1) { 'the alias' } else { 'the aliases' }
        [void]$enumBuilder.AppendLine("        /// <para>The <c>$($spec.name)</c> standard is also known by $verb $aliasList.</para>")
    }
    [void]$enumBuilder.AppendLine('        /// </remarks>')
    [void]$enumBuilder.AppendLine("        $c = $i,")
    [void]$enumBuilder.AppendLine()
}
[void]$enumBuilder.AppendLine('    }')
[void]$enumBuilder.AppendLine('}')

Set-Content -LiteralPath $EnumOutputPath -Value $enumBuilder.ToString() -Encoding utf8
Write-Host "Wrote $EnumOutputPath ($($supported.Count) enum members)"

# ----- CrcStandard.Catalog.cs -----
$catBuilder = [System.Text.StringBuilder]::new()
[void]$catBuilder.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$catBuilder.AppendLine('// <copyright file="CrcStandard.Catalog.cs" company="Bodu Pty. Ltd.">')
[void]$catBuilder.AppendLine('//     Copyright (c) Bodu Pty. Ltd.. All rights reserved.')
[void]$catBuilder.AppendLine('// </copyright>')
[void]$catBuilder.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$catBuilder.AppendLine('// <auto-generated>')
[void]$catBuilder.AppendLine('//     This file is regenerated by tools/Generate-CrcCatalog.ps1. Do not edit by hand.')
[void]$catBuilder.AppendLine('//     Source: Bodu.IO.Hashing/src/crc-specs.json (derived from https://reveng.sourceforge.io/crc-catalogue/all.htm).')
[void]$catBuilder.AppendLine('// </auto-generated>')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('namespace Bodu.IO.Hashing.Checksums;')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('using System;')
[void]$catBuilder.AppendLine('using System.Collections.Generic;')
[void]$catBuilder.AppendLine('using System.Collections.ObjectModel;')
[void]$catBuilder.AppendLine('using System.Threading;')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('public sealed partial class CrcStandard')
[void]$catBuilder.AppendLine('{')
[void]$catBuilder.AppendLine('#pragma warning disable CS8669 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.')
[void]$catBuilder.AppendLine('    /// <summary>Compact value-type row in the packed catalogue data table. Indexed by <see cref="CrcStandards" /> ordinal.</summary>')
[void]$catBuilder.AppendLine('    private readonly struct CatalogEntry')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        public CatalogEntry(string name, int size, ulong polynomial, ulong initialValue, bool reflectIn, bool reflectOut, ulong xOrOut)')
[void]$catBuilder.AppendLine('        {')
[void]$catBuilder.AppendLine('            Name = name;')
[void]$catBuilder.AppendLine('            Size = size;')
[void]$catBuilder.AppendLine('            Polynomial = polynomial;')
[void]$catBuilder.AppendLine('            InitialValue = initialValue;')
[void]$catBuilder.AppendLine('            XOrOut = xOrOut;')
[void]$catBuilder.AppendLine('            ReflectIn = reflectIn;')
[void]$catBuilder.AppendLine('            ReflectOut = reflectOut;')
[void]$catBuilder.AppendLine('        }')
[void]$catBuilder.AppendLine()   
[void]$catBuilder.AppendLine('        public readonly string Name;')
[void]$catBuilder.AppendLine('        public readonly int Size;')
[void]$catBuilder.AppendLine('        public readonly ulong Polynomial;')
[void]$catBuilder.AppendLine('        public readonly ulong InitialValue;')
[void]$catBuilder.AppendLine('        public readonly ulong XOrOut;')
[void]$catBuilder.AppendLine('        public readonly bool ReflectIn;')
[void]$catBuilder.AppendLine('        public readonly bool ReflectOut;')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    private static readonly CatalogEntry[] s_catalog = new CatalogEntry[]')
[void]$catBuilder.AppendLine('    {')
foreach ($spec in $supported) {
    $refIn  = $spec.reflectIn.ToString().ToLowerInvariant()
    $refOut = $spec.reflectOut.ToString().ToLowerInvariant()
    [void]$catBuilder.AppendLine("        new CatalogEntry(`"$($spec.name)`", $($spec.size), $(Format-HexLiteral $spec.polynomial), $(Format-HexLiteral $spec.initialValue), $refIn, $refOut, $(Format-HexLiteral $spec.xorOut)),")
}
[void]$catBuilder.AppendLine('    };')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    /// <summary>Lazy per-entry cache: index by <c>(int)CrcStandards</c> ordinal, materialised on first <see cref="Get(CrcStandards)" />.</summary>')
[void]$catBuilder.AppendLine('    private static readonly CrcStandard?[] s_cache = new CrcStandard?[s_catalog.Length];')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    /// <summary>Lazy map from canonical name or alias to the enum ordinal. Built on first <see cref="FromName(string)" /> call.</summary>')
[void]$catBuilder.AppendLine('    private static Dictionary<string, CrcStandards>? s_nameToEnum;')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    /// <summary>Lazy snapshot of every catalogue <see cref="CrcStandard" /> instance; materialised on first <see cref="All" /> access.</summary>')
[void]$catBuilder.AppendLine('    private static IReadOnlyList<CrcStandard>? s_all;')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    /// <summary>')
[void]$catBuilder.AppendLine('    /// Gets a snapshot of every supported CRC standard in the catalogue, in declaration order.')
[void]$catBuilder.AppendLine('    /// </summary>')
[void]$catBuilder.AppendLine('    /// <value>A read-only list containing one <see cref="CrcStandard" /> per canonical entry.</value>')
[void]$catBuilder.AppendLine('    /// <remarks>')
[void]$catBuilder.AppendLine('    /// <para>The backing array is built lazily on first access and then memoised, so merely loading this type does not construct any')
[void]$catBuilder.AppendLine('    /// <see cref="CrcStandard" /> instances. Aliases are not included as separate entries; use <see cref="FromName(string)" /> to')
[void]$catBuilder.AppendLine('    /// resolve an alias to its canonical instance.</para>')
[void]$catBuilder.AppendLine('    /// </remarks>')
[void]$catBuilder.AppendLine('    public static IReadOnlyList<CrcStandard> All')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        get')
[void]$catBuilder.AppendLine('        {')
[void]$catBuilder.AppendLine('            IReadOnlyList<CrcStandard>? cached = Volatile.Read(ref s_all);')
[void]$catBuilder.AppendLine('            if (cached is not null) return cached;')
[void]$catBuilder.AppendLine('            return BuildAll();')
[void]$catBuilder.AppendLine('         }')
[void]$catBuilder.AppendLine('   }')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    /// <summary>')
[void]$catBuilder.AppendLine('    /// Materialises — or retrieves from cache — the <see cref="CrcStandard" /> identified by the given enum value.')
[void]$catBuilder.AppendLine('    /// </summary>')
[void]$catBuilder.AppendLine('    /// <param name="standard">The catalogue entry to resolve. Must be a defined <see cref="CrcStandards" /> value.</param>')
[void]$catBuilder.AppendLine('    /// <returns>The shared <see cref="CrcStandard" /> instance for <paramref name="standard" />.</returns>')
[void]$catBuilder.AppendLine('    /// <exception cref="ArgumentOutOfRangeException"><paramref name="standard" /> is not a defined enum value.</exception>')
[void]$catBuilder.AppendLine('    /// <remarks>')
[void]$catBuilder.AppendLine('    /// <para>The first call for a given value constructs a new <see cref="CrcStandard" /> from the packed catalogue data and races')
[void]$catBuilder.AppendLine('    /// to publish it into the per-entry cache. Subsequent calls — including concurrent calls — return the same instance, so')
[void]$catBuilder.AppendLine('    /// reference equality is stable.</para>')
[void]$catBuilder.AppendLine('    /// </remarks>')
[void]$catBuilder.AppendLine('    public static CrcStandard Get(CrcStandards standard)')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        int index = (int)standard;')
[void]$catBuilder.AppendLine('        if ((uint)index >= (uint)s_catalog.Length)')
[void]$catBuilder.AppendLine('            throw new ArgumentOutOfRangeException(nameof(standard), standard, "The specified CrcStandards value is not defined.");')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('        CrcStandard? cached = Volatile.Read(ref s_cache[index]);')
[void]$catBuilder.AppendLine('        if (cached is not null) return cached;')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('        ref readonly CatalogEntry entry = ref s_catalog[index];')
[void]$catBuilder.AppendLine('        CrcStandard created = new CrcStandard(')
[void]$catBuilder.AppendLine('            name: entry.Name,')
[void]$catBuilder.AppendLine('            size: entry.Size,')
[void]$catBuilder.AppendLine('            polynomial: entry.Polynomial,')
[void]$catBuilder.AppendLine('            initialValue: entry.InitialValue,')
[void]$catBuilder.AppendLine('            reflectIn: entry.ReflectIn,')
[void]$catBuilder.AppendLine('            reflectOut: entry.ReflectOut,')
[void]$catBuilder.AppendLine('            xOrOut: entry.XOrOut);')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('        // Race-resolve: first writer wins; losers discard their copy and return the cached one for reference-equality stability.')
[void]$catBuilder.AppendLine('        CrcStandard? winner = Interlocked.CompareExchange(ref s_cache[index], created, null);')
[void]$catBuilder.AppendLine('        return winner ?? created;')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('    /// <summary>')
[void]$catBuilder.AppendLine('    /// Resolves a catalogue entry by its canonical name or any of its published aliases.')
[void]$catBuilder.AppendLine('    /// </summary>')
[void]$catBuilder.AppendLine('    /// <param name="name">The canonical CRC standard name, or an alias. Comparison is ordinal and case-sensitive.</param>')
[void]$catBuilder.AppendLine('    /// <returns>The shared <see cref="CrcStandard" /> instance for <paramref name="name" />.</returns>')
[void]$catBuilder.AppendLine('    /// <exception cref="ArgumentNullException"><paramref name="name" /> is <see langword="null" />.</exception>')
[void]$catBuilder.AppendLine('    /// <exception cref="KeyNotFoundException">No catalogue entry matching <paramref name="name" /> exists.</exception>')
[void]$catBuilder.AppendLine('    public static CrcStandard FromName(string name)')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        ThrowHelper.ThrowIfNull(name);')
[void]$catBuilder.AppendLine('        var map = GetNameToEnumMap();')
[void]$catBuilder.AppendLine('        if (!map.TryGetValue(name, out CrcStandards standard))')
[void]$catBuilder.AppendLine('            throw new KeyNotFoundException($"No CRC standard with the name ''{name}'' exists in the catalogue.");')
[void]$catBuilder.AppendLine('        return Get(standard);')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('    /// <summary>')
[void]$catBuilder.AppendLine('    /// Attempts to resolve a catalogue entry by its canonical name or alias without throwing.')
[void]$catBuilder.AppendLine('    /// </summary>')
[void]$catBuilder.AppendLine('    /// <param name="name">The canonical CRC standard name or alias to look up.</param>')
[void]$catBuilder.AppendLine('    /// <param name="standard">When this method returns, contains the matching <see cref="CrcStandard" /> if found; otherwise, <see langword="null" />.</param>')
[void]$catBuilder.AppendLine('    /// <returns><see langword="true" /> if a catalogue entry was found; otherwise, <see langword="false" />.</returns>')
[void]$catBuilder.AppendLine('    public static bool TryFromName(string? name, out CrcStandard? standard)')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        if (name is not null && GetNameToEnumMap().TryGetValue(name, out CrcStandards id))')
[void]$catBuilder.AppendLine('        {')
[void]$catBuilder.AppendLine('            standard = Get(id);')
[void]$catBuilder.AppendLine('            return true;')
[void]$catBuilder.AppendLine('        }')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('        standard = null;')
[void]$catBuilder.AppendLine('        return false;')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()  
[void]$catBuilder.AppendLine('    private static Dictionary<string, CrcStandards> GetNameToEnumMap()')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        Dictionary<string, CrcStandards>? map = Volatile.Read(ref s_nameToEnum);')
[void]$catBuilder.AppendLine('        if (map is not null) return map;')
[void]$catBuilder.AppendLine('        return BuildNameLookup();')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()

$entryCount = 0
foreach ($spec in $supported) {
    $entryCount++
    foreach ($a in (Get-AliasesFrom $spec)) { $entryCount++ }
}

[void]$catBuilder.AppendLine('    private static Dictionary<string, CrcStandards> BuildNameLookup()')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine("        var map = new Dictionary<string, CrcStandards>($entryCount, StringComparer.Ordinal);")
foreach ($spec in $supported) {
    $c = ConvertTo-ConstantName $spec.name
    [void]$catBuilder.AppendLine("        map[`"$($spec.name)`"] = CrcStandards.$c;")
    foreach ($a in (Get-AliasesFrom $spec)) {
        [void]$catBuilder.AppendLine("        map[`"$a`"] = CrcStandards.$c;")
    }
}
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('        Dictionary<string, CrcStandards>? winner = Interlocked.CompareExchange(ref s_nameToEnum, map, null);')
[void]$catBuilder.AppendLine('        return winner ?? map;')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('    private static IReadOnlyList<CrcStandard> BuildAll()')
[void]$catBuilder.AppendLine('    {')
[void]$catBuilder.AppendLine('        var array = new CrcStandard[s_catalog.Length];')
[void]$catBuilder.AppendLine('        for (int i = 0; i < array.Length; i++)')
[void]$catBuilder.AppendLine('            array[i] = Get((CrcStandards)i);')
[void]$catBuilder.AppendLine()
[void]$catBuilder.AppendLine('        var readOnly = new ReadOnlyCollection<CrcStandard>(array);')
[void]$catBuilder.AppendLine('        IReadOnlyList<CrcStandard>? winner = Interlocked.CompareExchange(ref s_all, readOnly, null);')
[void]$catBuilder.AppendLine('        return winner ?? readOnly;')
[void]$catBuilder.AppendLine('    }')
[void]$catBuilder.AppendLine('#pragma warning restore CS8669 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.')
[void]$catBuilder.AppendLine('}')

Set-Content -LiteralPath $CatalogOutputPath -Value $catBuilder.ToString() -Encoding utf8

Write-Host "Wrote $CatalogOutputPath"
Write-Host "  Catalogue rows:     $($supported.Count)"
Write-Host "  Name-lookup entries: $entryCount"
