<#
.SYNOPSIS
    Generates CrcTests.Catalog.cs: a data-driven test that asserts each catalogue entry's `check`
    vector (the CRC of ASCII "123456789").

.DESCRIPTION
    For every CRC standard in crc-specs.json (except those listed in -Exclude), emits a
    DynamicData row carrying the generated field reference and the expected check value. A single
    parameterised test computes `new Crc(standard).ComputeHash(Encoding.ASCII.GetBytes("123456789"))`
    and compares against the expected value, packed little-endian from the CRC width.

    Entries listed in -Exclude are omitted because they are expected to be covered by bespoke
    hand-written tests elsewhere.

.PARAMETER SpecsPath
    Path to the crc-specs.json input file.

.PARAMETER OutputPath
    Path of the C# file to write. Overwritten in place.

.PARAMETER Exclude
    Canonical CRC names to omit from the generated test rows.

.EXAMPLE
    pwsh ./tools/Generate-CrcCatalogTests.ps1

.NOTES
    Requires PowerShell 7+.
#>
#Requires -Version 7
[CmdletBinding()]
param(
    [string]$SpecsPath = (Join-Path $PSScriptRoot '..' 'Bodu.Security.Cryptography' 'src' 'crc-specs.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..' 'Bodu.Security.Cryptography' 'test' 'Security.Cryptography' 'CrcTests.Catalog.cs'),
    [string[]]$Exclude = @('CRC-32/ISO-HDLC')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function ConvertTo-ConstantName {
    param([string]$Name)
    $s = $Name -replace '/', '_'
    $s = $s -replace '[^A-Za-z0-9_]', ''
    return $s.ToUpperInvariant()
}

function Format-HexLiteral {
    param([string]$Value)
    $hex = ($Value -replace '^0[xX]', '').ToUpperInvariant()
    return "0x$hex" + 'UL'
}

$specs = Get-Content -LiteralPath $SpecsPath -Raw | ConvertFrom-Json
$excludeSet = [System.Collections.Generic.HashSet[string]]::new([string[]]$Exclude, [System.StringComparer]::Ordinal)
$emitted = @($specs | Where-Object { -not $excludeSet.Contains($_.name) })

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$sb.AppendLine('// <copyright file="CrcTests.Catalog.cs" company="PlaceholderCompany">')
[void]$sb.AppendLine('//     Copyright (c) PlaceholderCompany. All rights reserved.')
[void]$sb.AppendLine('// </copyright>')
[void]$sb.AppendLine('// ---------------------------------------------------------------------------------------------------------------')
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//     This file is regenerated by tools/Generate-CrcCatalogTests.ps1. Do not edit by hand.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('using System.Collections.Generic;')
[void]$sb.AppendLine('using System.Text;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace Bodu.Security.Cryptography')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    public partial class CrcTests')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        private static readonly byte[] CatalogCheckInput = Encoding.ASCII.GetBytes("123456789");')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Yields one test row per catalogue CRC standard: the <see cref="CrcStandard" /> instance and the expected')
[void]$sb.AppendLine('        /// <c>check</c> value from the RevEng catalogue (the CRC of the ASCII bytes <c>"123456789"</c>).')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        /// <returns>Test data rows for use with <c>[DynamicData]</c>.</returns>')
[void]$sb.AppendLine('        public static IEnumerable<object[]> CatalogCheckVectors()')
[void]$sb.AppendLine('        {')
foreach ($spec in $emitted) {
    $constName = ConvertTo-ConstantName $spec.name
    $expected = Format-HexLiteral $spec.check
    [void]$sb.AppendLine("            yield return new object[] { CrcStandard.$constName, $expected };")
}
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        /// <summary>')
[void]$sb.AppendLine('        /// Verifies that every catalogue CRC standard hashes the reference input <c>"123456789"</c> to the')
[void]$sb.AppendLine('        /// <c>check</c> value published in the RevEng catalogue.')
[void]$sb.AppendLine('        /// </summary>')
[void]$sb.AppendLine('        /// <param name="standard">The catalogue <see cref="CrcStandard" /> under test.</param>')
[void]$sb.AppendLine('        /// <param name="expectedCheck">The expected CRC value, packed little-endian from the CRC width.</param>')
[void]$sb.AppendLine('        [DataTestMethod]')
[void]$sb.AppendLine('        [DynamicData(nameof(CatalogCheckVectors), DynamicDataSourceType.Method)]')
[void]$sb.AppendLine('        public void ComputeHash_WhenInputIsCheckVector_ForCatalogStandard_ShouldMatchPublishedCheck(CrcStandard standard, ulong expectedCheck)')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            using var crc = new Crc(standard);')
[void]$sb.AppendLine('            byte[] hash = crc.ComputeHash(CatalogCheckInput);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('            ulong actual = 0UL;')
[void]$sb.AppendLine('            for (int i = 0; i < hash.Length; i++)')
[void]$sb.AppendLine('                actual |= (ulong)hash[i] << (i * 8);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('            Assert.AreEqual(expectedCheck, actual, $"Check vector mismatch for {standard.Name}: expected 0x{expectedCheck:X}, got 0x{actual:X}.");')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')

Set-Content -LiteralPath $OutputPath -Value $sb.ToString() -Encoding utf8
Write-Host "Wrote $OutputPath ($($emitted.Count) check vectors; $($excludeSet.Count) excluded)."
