using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

namespace Bodu.Rosyln.Generators
{
    internal static class CrcCodeEmitter
    {
        public static string Emit(IReadOnlyList<CrcSpec> specs, string ns)
        {
            var sb = new StringBuilder(32_000);

            sb
                .AppendLine("// <auto-generated/>")
                .AppendLine($"namespace {ns}")
                .AppendLine("{")
                .AppendLine("    public sealed partial class CrcStandard")
                .AppendLine("    {");

            // --- fields ------------------------------------------------------
            foreach (var s in specs.Where(s => s.Size <= 64).OrderBy(s => s.Size).ThenBy(s => s.Name))
            {
                sb.AppendLine($"        private static readonly Lazy<CrcStandard> {Field(s)} = new(() =>")
                  .AppendLine("             new CrcStandard(")
                  .AppendLine($"                \"{s.Name}\",")
                  .AppendLine($"                {s.Size},")
                  .AppendLine($"                0x{GenerateHexValue(s.Polynomial, s.Size)}UL,")
                  .AppendLine($"                0x{GenerateHexValue(s.InitialValue, s.Size)}UL,")
                  .AppendLine($"                {s.ReflectIn.ToString().ToLower()},")
                  .AppendLine($"                {s.ReflectOut.ToString().ToLower()},")
                  .AppendLine($"                0x{GenerateHexValue(s.XorOut, s.Size)}UL));")
                  .AppendLine();
            }

            // --- properties --------------------------------------------------
            foreach (var s in specs.Where(s=>s.Size<=64).OrderBy(s => s.Size).ThenBy(s => s.Name))
            {

                sb
                    .AppendLine($"        /// <summary>Gets the <see cref=\"CrcStandard\"/> that defines the <c>{s.Name}</c> cyclic redundancy check algorithm standard.</summary>")
                    .AppendLine($"        /// <value>A <see cref=\"CrcStandard\"/> object with the properties set to the <c>{s.Name}</c> definition.</value>")
                    .AppendLine($"        /// <remarks>");
                if (!(s.Class == "confirmed" | s.Class == "attested"))
                    sb.AppendLine($"        /// <note type=\"note\">The parameters for the <c>{s.Name}</c> standard are not widely tested or confirmed.</note>");

                sb.Append($"        /// <para>The <c>{s.Name}</c> standard was taken from <a href=\"http://reveng.sourceforge.net/crc-catalogue/all.htm#crc.cat.{s.Name.Replace('/', '-').ToLowerInvariant()}\">http://reveng.sourceforge.net/crc-catalogue/</a> (Created: {(!string.IsNullOrEmpty(s.Created) ? DateTime.Parse(s.Created) : DateTime.MinValue):d MMMM yyyy}");
                if (!string.IsNullOrEmpty(s.Updated))
                {
                    sb.Append($", Updated: {DateTime.Parse(s.Updated):d MMMM yyyy}");
                }
                sb
                    .AppendLine("), with the following definition.</para>")
                    .AppendLine($"        /// <para>")
                    .AppendLine($"        /// <list type=\"bullet\">")
                    .AppendLine($"        /// <item><description>Width: <c>{s.Size}</c></description></item>")
                    .AppendLine($"        /// <item><description>Polynomial: <c>0x{GenerateHexValue(s.Polynomial, s.Size).ToUpperInvariant()}</c></description></item>")
                    .AppendLine($"        /// <item><description>Initial Value: <c>0x{GenerateHexValue(s.InitialValue, s.Size).ToUpperInvariant()}</c></description></item>")
                    .AppendLine($"        /// <item><description>Reflect In: <c>{s.ReflectIn.ToString()}</c></description></item>")
                    .AppendLine($"        /// <item><description>Reflect Out: <c>{s.ReflectOut.ToString()}</c></description></item>")
                    .AppendLine($"        /// <item><description>XOR Out: <c>0x{GenerateHexValue(s.XorOut, s.Size).ToUpperInvariant()}</c></description></item>")
                    .AppendLine($"        /// </list>")
                    .AppendLine($"        /// </para>");
                if (s.Aliases != null && s.Aliases.Count() > 0)
                {
                    var lastAlias = s.Aliases.Last();
                    sb.AppendLine($"        /// <para>The <c>{s.Name}</c> standard is also known by the {(s.Aliases.Count() > 1 ? "aliases" : "alias")} {string.Join(", ", s.Aliases.Select(a => (s.Aliases.Count() > 1 && a == lastAlias ? "and " : string.Empty) + "<c>" + a + "</c>"))}.</para>");
                }
                sb.AppendLine("        /// </remarks>");
                foreach (var alias in s.Aliases)
                {
                    sb.AppendLine($"        /// <seealso cref=\"CrcStandards.{alias.Replace("-", "").Replace("/", "_")}\"/>");
                }
                sb
                    .AppendLine($"        public static CrcStandard {TypeName(s.Name)} => {Field(s)}.Value;");

                foreach (var alias in s.Aliases)
                {
                    sb
                        .AppendLine()
                        .AppendLine($"        /// <summary>Gets the <see cref=\"CrcStandard\"/> that defines the <c>{alias}</c> cyclic redundancy check algorithm standard.</summary>")
                        .AppendLine($"        /// <value>A <see cref=\"CrcStandard\"/> object with the properties set to the <c>{alias}</c> definition.</value>")
                        .AppendLine($"        /// <remarks>")
                        .AppendLine($"        /// <para>The <c>{TypeName(alias)}</c> is an alias of the <see cref=\"CrcStandards.{TypeName(s.Name)}\"/> standard.</para>")
                        .AppendLine($"        /// </remarks>");
                    sb.AppendLine($"        /// <seealso cref=\"CrcStandards.{TypeName(s.Name)}\"/>");
                    foreach (var a in s.Aliases.Where(n => n != alias))
                    {
                        sb.AppendLine($"        /// <seealso cref=\"CrcStandards.{TypeName(a)}\"/>");
                    }
                    sb
                        .AppendLine($"        public static CrcStandard {TypeName(alias)} => {Field(s)}.Value;");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();

            static string TypeName(string n) => n.Replace("-", "").Replace("/", "_");
            static string Field(CrcSpec s) => "this.crc" + TypeName(s.Name).Substring(3);
        }

        private static string GenerateHexValue(string polynomial, int size)
        {
            var span = polynomial.AsSpan().Trim();
            if (span.StartsWith("0x".AsSpan(), StringComparison.OrdinalIgnoreCase))
                span = span.Slice(2); 
            
            ulong value = ulong.Parse(new string(span.ToArray()), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            switch (size)
            {
                case int s when s <= 8: return $"{value.ToString("x2")}";
                case int s when s <= 16: return $"{value.ToString("x4")}";
                case int s when s <= 32: return $"{value.ToString("x8")}";
                default: return $"{value.ToString("x16")}";
            }
        }
    }
}
