//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodu.Formats.Outlook {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutlookPstResourceStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlookPstResourceStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodu.Formats.Outlook.OutlookPstResourceStrings", typeof(OutlookPstResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The compressed RTF payload does not begin with a valid MS-OXRTFCP header..
        /// </summary>
        internal static string Format_Invalid_RtfCompressedHeader {
            get {
                return ResourceManager.GetString("Format_Invalid_RtfCompressedHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The compressed RTF payload&apos;s declared sizes are inconsistent with its length..
        /// </summary>
        internal static string Format_Invalid_RtfCompressedData {
            get {
                return ResourceManager.GetString("Format_Invalid_RtfCompressedData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The compressed RTF payload failed its checksum; the content is corrupt..
        /// </summary>
        internal static string Format_Invalid_RtfCompressedCrc {
            get {
                return ResourceManager.GetString("Format_Invalid_RtfCompressedCrc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node {0} is not a folder node..
        /// </summary>
        internal static string Format_Invalid_PstFolderNode {
            get {
                return ResourceManager.GetString("Format_Invalid_PstFolderNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node {0} is not a message node..
        /// </summary>
        internal static string Format_Invalid_PstMessageNode {
            get {
                return ResourceManager.GetString("Format_Invalid_PstMessageNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Row {0} of table {1} does not reference a valid node..
        /// </summary>
        internal static string Format_Invalid_PstTableRowNode {
            get {
                return ResourceManager.GetString("Format_Invalid_PstTableRowNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attachment {0} of message {1} does not carry a valid attachment object..
        /// </summary>
        internal static string Format_Invalid_PstAttachmentObject {
            get {
                return ResourceManager.GetString("Format_Invalid_PstAttachmentObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attachment does not carry an embedded message object..
        /// </summary>
        internal static string Format_Invalid_PstEmbeddedMessage {
            get {
                return ResourceManager.GetString("Format_Invalid_PstEmbeddedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attachment&apos;s method ({0}) does not expose a binary content stream..
        /// </summary>
        internal static string Op_NotSupported_PstAttachmentContent {
            get {
                return ResourceManager.GetString("Op_NotSupported_PstAttachmentContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attachment does not carry its by-value content payload..
        /// </summary>
        internal static string Format_Invalid_PstAttachmentContent {
            get {
                return ResourceManager.GetString("Format_Invalid_PstAttachmentContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attachment&apos;s method ({0}) does not carry an embedded message..
        /// </summary>
        internal static string Op_NotSupported_PstEmbeddedMessage {
            get {
                return ResourceManager.GetString("Op_NotSupported_PstEmbeddedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name-to-id map is malformed..
        /// </summary>
        internal static string Format_Invalid_PstNamedPropertyMap {
            get {
                return ResourceManager.GetString("Format_Invalid_PstNamedPropertyMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The multi-valued property 0x{0:X4} has an inconsistent count or offset table..
        /// </summary>
        internal static string Format_Invalid_PstMultiValue {
            get {
                return ResourceManager.GetString("Format_Invalid_PstMultiValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The property 0x{0:X4} carries an undecodable value..
        /// </summary>
        internal static string Format_Invalid_PstPropertyValue {
            get {
                return ResourceManager.GetString("Format_Invalid_PstPropertyValue", resourceCulture);
            }
        }
    }
}
