// ---------------------------------------------------------------------------------------------------------------
// <copyright file="PstReferenceFixtures.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Text.Json;
using System.Text.Json.Serialization;
using Bodu.Test.Kat;

namespace Bodu.IO.Pst;

/// <summary>
/// Loads the embedded reference-corpus fixtures and their seed expectations manifest.
/// </summary>
/// <remarks>
/// The corpus files and <c>manifest.seed.json</c> are embedded resources under the
/// <c>Bodu.IO.Pst.Fixtures.Reference</c> logical-name prefix; provenance is recorded in the
/// <c>Fixtures/Reference/NOTICE.md</c> alongside them. The manifest expectations were generated by an independent
/// implementation (libpst's <c>lspst</c>), so corpus-driven assertions are a cross-implementation check.
/// </remarks>
internal static class PstReferenceFixtures
{
    /// <summary>The logical-name prefix of the embedded reference resources.</summary>
    private const string ResourcePrefix = "Bodu.IO.Pst.Fixtures.Reference.";

    /// <summary>The lazily deserialized manifest.</summary>
    private static readonly Lazy<PstReferenceManifest> s_manifest = new(LoadManifest);

    /// <summary>
    /// Gets the deserialized seed manifest.
    /// </summary>
    /// <value>The manifest carrying one row per corpus file.</value>
    internal static PstReferenceManifest Manifest =>
        s_manifest.Value;

    /// <summary>
    /// Opens a corpus fixture as a seekable stream.
    /// </summary>
    /// <param name="relativePath">The manifest-relative fixture path, for example <c>unicode/sample1.pst</c>.</param>
    /// <returns>A stream positioned at the start of the fixture bytes.</returns>
    /// <exception cref="InvalidOperationException">The embedded resource does not exist.</exception>
    internal static MemoryStream OpenStream(string relativePath)
    {
        string resourceName = ResourcePrefix + relativePath.Replace('/', '.');
        using Stream stream = typeof(PstReferenceFixtures).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Missing embedded fixture '{resourceName}'.");

        var buffer = new MemoryStream();
        stream.CopyTo(buffer);
        buffer.Position = 0;
        return buffer;
    }

    /// <summary>
    /// Opens a corpus fixture as an open <see cref="PstFile" /> session.
    /// </summary>
    /// <param name="relativePath">The manifest-relative fixture path.</param>
    /// <param name="validationLevel">The validation level to open under.</param>
    /// <returns>The open session, owning the fixture stream.</returns>
    internal static PstFile OpenFile(string relativePath, PstValidationLevel validationLevel = PstValidationLevel.Compatible) =>
        PstFile.Open(OpenStream(relativePath), new PstFileOptions { ValidationLevel = validationLevel });

    /// <summary>
    /// Deserializes the embedded manifest.
    /// </summary>
    /// <returns>The manifest.</returns>
    private static PstReferenceManifest LoadManifest()
    {
        using Stream stream = typeof(PstReferenceFixtures).Assembly.GetManifestResourceStream(ResourcePrefix + "manifest.seed.json")
            ?? throw new InvalidOperationException("Missing embedded reference manifest.");

        return JsonSerializer.Deserialize<PstReferenceManifest>(stream)
            ?? throw new InvalidOperationException("The reference manifest deserialized to null.");
    }
}

/// <summary>
/// Represents the reference-corpus seed manifest.
/// </summary>
/// <param name="Source">The upstream corpus source and license.</param>
/// <param name="GeneratedBy">The independent implementation that generated the expectations.</param>
/// <param name="GeneratedAtUtc">When the manifest was generated.</param>
/// <param name="Purpose">The manifest's stated purpose.</param>
/// <param name="Fixtures">The per-file expectation rows.</param>
internal sealed record PstReferenceManifest(
    [property: JsonPropertyName("source")] string Source,
    [property: JsonPropertyName("generatedBy")] string GeneratedBy,
    [property: JsonPropertyName("generatedAtUtc")] string GeneratedAtUtc,
    [property: JsonPropertyName("purpose")] string Purpose,
    [property: JsonPropertyName("fixtures")] IReadOnlyList<PstReferenceFixture> Fixtures);

/// <summary>
/// Represents one corpus file's seed expectations. Implements <see cref="IKat" /> so data-driven rows display the
/// file path in failure diagnostics.
/// </summary>
/// <param name="File">The manifest-relative fixture path.</param>
/// <param name="Format">The format variant: <c>unicode</c> or <c>ansi</c>.</param>
/// <param name="WVer">The header's <c>wVer</c> value.</param>
/// <param name="Sha256">The SHA-256 of the fixture bytes.</param>
/// <param name="SizeBytes">The fixture size in bytes.</param>
/// <param name="FolderCount">The user-visible folder count <c>lspst</c> reported.</param>
/// <param name="MessageCount">The message count <c>lspst</c> reported.</param>
/// <param name="LspstListing">The raw <c>lspst</c> listing lines.</param>
public sealed record PstReferenceFixture(
    [property: JsonPropertyName("file")] string File,
    [property: JsonPropertyName("format")] string Format,
    [property: JsonPropertyName("wVer")] int WVer,
    [property: JsonPropertyName("sha256")] string Sha256,
    [property: JsonPropertyName("sizeBytes")] long SizeBytes,
    [property: JsonPropertyName("folderCount")] int FolderCount,
    [property: JsonPropertyName("messageCount")] int MessageCount,
    [property: JsonPropertyName("lspstListing")] IReadOnlyList<string> LspstListing) : IKat
{
    /// <summary>
    /// Gets the display label for data-driven rows.
    /// </summary>
    /// <value>The fixture path.</value>
    public string Name =>
        File;
}
