// ---------------------------------------------------------------------------------------------------------------
// <copyright file="HinduObservanceVectors.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using Bodu.Test.Kat;

namespace Bodu.Globalization.Calendar;

/// <summary>
/// Loads the embedded Hindu observance vector table — fifty Gregorian years of dates for every <c>global-hindu</c>
/// catalogue observance — as KAT rows for <c>[DynamicData]</c> binding.
/// </summary>
/// <remarks>
/// <para>
/// The vectors are generated by <c>tools/HinduObservanceVectorGenerator</c> and are engine-pinned: they freeze the
/// in-repo <c>HinduLunarCalculator</c> / catalogue output as a regression baseline, braced by the independent
/// tithi-proximity and seasonal-window checks in <c>tools/verify-hindu-observance-vectors.py</c> and the
/// published-panchanga rows in <see cref="GlobalHinduCatalogueKnownAnswerTests" />; the file's provenance header
/// records the details and the deliberately limited exactness claim.
/// </para>
/// </remarks>
internal static class HinduObservanceVectors
{
    /// <summary>The logical name of the embedded vector file.</summary>
    private const string ResourceName = "Bodu.Globalization.Calendar.Fixtures.Vectors.HinduObservances-1990-2039.csv";

    /// <summary>
    /// Gets the vector rows, one per (Gregorian year, observance) pair, each carrying the expected date.
    /// </summary>
    /// <value>The KAT rows for <c>[DynamicData]</c> binding.</value>
    public static IEnumerable<object[]> Rows
    {
        get
        {
            using Stream stream = typeof(HinduObservanceVectors).Assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"Embedded vector file '{ResourceName}' not found.");
            using StreamReader reader = new(stream);

            while (reader.ReadLine() is { } line)
            {
                if (line.Length == 0 || line.StartsWith('#'))
                    continue;

                string[] fields = line.Split(',');
                var year = int.Parse(fields[0], CultureInfo.InvariantCulture);
                string observanceId = fields[1];
                var expected = DateOnly.Parse(fields[2], CultureInfo.InvariantCulture);

                yield return
                [
                    new ValidKat<(int Year, string ObservanceId), DateOnly>(
                        $"{observanceId} {year}",
                        (year, observanceId),
                        expected),
                ];
            }
        }
    }
}
