// ---------------------------------------------------------------------------------------------------------------
// <copyright file="HinduReferenceCorpusRow.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

namespace Bodu.Globalization.Calendar;

/// <summary>
/// One row of the calcal Modern Hindu Reference corpus (<c>corpus/hindu/data/normalized/hindu-reference-daily.csv</c>):
/// one Gregorian civil date under one calendar model, as generated by the pinned executable oracle.
/// </summary>
/// <param name="GregorianDate">The Gregorian civil date.</param>
/// <param name="FixedDate">The Rata Die fixed-day number reported by the oracle.</param>
/// <param name="CalendarModel">The calendar model, for example <c>modern-hindu-lunar</c>.</param>
/// <param name="LunarYear">The Hindu lunar year, or <see langword="null" /> for solar models.</param>
/// <param name="LunarMonth">The one-based amanta lunar month, or <see langword="null" />.</param>
/// <param name="LunarDay">The lunar day (tithi ordinal 1-30), or <see langword="null" />.</param>
/// <param name="IsLeapMonth">Whether the lunar month is intercalary (adhika), or <see langword="null" />.</param>
/// <param name="SolarYear">The Hindu solar year, or <see langword="null" /> for lunar models.</param>
/// <param name="SolarMonth">The one-based solar month (1 = Vaisakha / Mesha), or <see langword="null" />.</param>
/// <param name="SolarDay">The solar day of month, or <see langword="null" />.</param>
/// <param name="SourceVersion">The oracle package version recorded by the generator.</param>
internal sealed record HinduReferenceCorpusRow(
    DateOnly GregorianDate,
    long FixedDate,
    string CalendarModel,
    int? LunarYear,
    int? LunarMonth,
    int? LunarDay,
    bool? IsLeapMonth,
    int? SolarYear,
    int? SolarMonth,
    int? SolarDay,
    string SourceVersion);
