// ---------------------------------------------------------------------------------------------------------------
// <copyright file="PersianObservanceVectors.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using Bodu.Test.Kat;

namespace Bodu.Globalization.Calendar;

/// <summary>
/// Loads the embedded Persian-calendar observance vector table — fifty Gregorian years of independently computed dates
/// for every <c>global-persian</c> catalogue observance — as KAT rows for <c>[DynamicData]</c> binding.
/// </summary>
/// <remarks>
/// <para>
/// The vectors are generated by <c>tools/generate-persian-observance-vectors.py</c>, an independent implementation of
/// the official Solar Hijri new-year rule (the Meeus vernal-equinox series reduced to apparent solar time at the
/// Iranian standard meridian), and were cross-verified at generation time against the
/// <see cref="System.Globalization.PersianCalendar" /> projection; the file's provenance header records the details.
/// </para>
/// </remarks>
internal static class PersianObservanceVectors
{
    /// <summary>The logical name of the embedded vector file.</summary>
    private const string ResourceName = "Bodu.Globalization.Calendar.Fixtures.Vectors.PersianObservances-1990-2039.csv";

    /// <summary>
    /// Gets the vector rows, one per (Gregorian year, observance) pair, each carrying the expected date.
    /// </summary>
    /// <value>The KAT rows for <c>[DynamicData]</c> binding.</value>
    public static IEnumerable<object[]> Rows
    {
        get
        {
            using Stream stream = typeof(PersianObservanceVectors).Assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"Embedded vector file '{ResourceName}' not found.");
            using StreamReader reader = new(stream);

            while (reader.ReadLine() is { } line)
            {
                if (line.Length == 0 || line.StartsWith('#'))
                    continue;

                string[] fields = line.Split(',');
                var year = int.Parse(fields[0], CultureInfo.InvariantCulture);
                string observanceId = fields[1];
                var expected = DateOnly.Parse(fields[2], CultureInfo.InvariantCulture);

                yield return
                [
                    new ValidKat<(int Year, string ObservanceId), DateOnly>(
                        $"{observanceId} {year}",
                        (year, observanceId),
                        expected),
                ];
            }
        }
    }
}
