// ---------------------------------------------------------------------------------------------------------------
// <copyright file="UmmAlQuraObservanceVectors.cs" company="Bodu Pty. Ltd.">
// Copyright (c) Bodu Pty. Ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------------------------------------------------

using System.Globalization;
using Bodu.Test.Kat;

namespace Bodu.Globalization.Calendar;

/// <summary>
/// Loads the embedded Umm al-Qura observance vector table — fifty Gregorian years of dates for every
/// <c>global-islamic-umm-al-qura</c> catalogue observance — as KAT rows for <c>[DynamicData]</c> binding.
/// </summary>
/// <remarks>
/// <para>
/// The vectors are generated by <c>tools/IslamicObservanceVectorGenerator</c> from the official KACST Umm al-Qura
/// month table embedded in <see cref="System.Globalization.UmAlQuraCalendar" />, and every underlying Hijri month
/// start was cross-checked astronomically at generation time by the independent Meeus lunar-conjunction series in
/// <c>tools/verify-islamic-observance-vectors.py</c>; the file's provenance header records the details.
/// </para>
/// <para>
/// A short lunar date can land twice in one Gregorian year, so each KAT row carries the full ordered occurrence list
/// for its (year, observance) pair rather than a single date.
/// </para>
/// </remarks>
internal static class UmmAlQuraObservanceVectors
{
    /// <summary>The logical name of the embedded vector file.</summary>
    private const string ResourceName = "Bodu.Globalization.Calendar.Fixtures.Vectors.UmmAlQuraObservances-1990-2039.csv";

    /// <summary>
    /// Gets the vector rows, one per (Gregorian year, observance) pair, each carrying the expected ordered occurrence
    /// list for the year.
    /// </summary>
    /// <value>The KAT rows for <c>[DynamicData]</c> binding.</value>
    public static IEnumerable<object[]> Rows
    {
        get
        {
            Dictionary<(int Year, string ObservanceId), List<DateOnly>> table = new();

            using (Stream stream = typeof(UmmAlQuraObservanceVectors).Assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"Embedded vector file '{ResourceName}' not found."))
            using (StreamReader reader = new(stream))
            {
                while (reader.ReadLine() is { } line)
                {
                    if (line.Length == 0 || line.StartsWith('#'))
                        continue;

                    string[] fields = line.Split(',');
                    var year = int.Parse(fields[0], CultureInfo.InvariantCulture);
                    string observanceId = fields[1];
                    var date = DateOnly.Parse(fields[2], CultureInfo.InvariantCulture);

                    if (!table.TryGetValue((year, observanceId), out List<DateOnly>? dates))
                        table[(year, observanceId)] = dates = [];

                    dates.Add(date);
                }
            }

            foreach (((int year, string observanceId), List<DateOnly> dates) in table)
            {
                dates.Sort();

                yield return
                [
                    new ValidKat<(int Year, string ObservanceId), IReadOnlyList<DateOnly>>(
                        $"{observanceId} {year}",
                        (year, observanceId),
                        dates),
                ];
            }
        }
    }
}
